[[Submissions]]
  Id = 1252457115
  StatusDisplay = "Accepted"
  Lang = "python3"
  QuestionId = 506
  TitleSlug = "relative-ranks"
  Code = "import heapq\n\nclass Solution:\n    def findRelativeRanks(self, score: List[int]) -> List[str]:\n        heap = []\n        for i, athlete_score in enumerate(score):\n            heapq.heappush(heap, (-athlete_score, i))\n        i = 0\n        ranks = {0: \"Gold Medal\", 1: \"Silver Medal\", 2: \"Bronze Medal\"}\n        while heap:\n            _, athlete = heapq.heappop(heap)\n            rank = ranks.get(i, str(i + 1))\n            score[athlete] = rank\n            i += 1\n        return score"
  Title = "Relative Ranks"
  Url = "/submissions/detail/1252457115/"
  LangName = "Python3"
  Timestamp = 1715153948
  Status = 10
  Runtime = "72 ms"
  IsPending = "Not Pending"
  Memory = "18.2 MB"
  CompareResult = "111111111111111111"
  HasNotes = false
  FlagType = 1
