load("@rules_docs//docs:defs.bzl", "docs_filegroup")
load("@rules_pkg//pkg:mappings.bzl", "pkg_filegroup")

docs_filegroup(
    name = "docs",
    srcs = glob(["*.md"]),
    prefix = "content/docs/misc/rfc",
    visibility = ["//projects/alwaldend.com/content/docs/misc:__pkg__"],
    deps = [
        ":rfcs",
    ],
)

pkg_filegroup(
    name = "rfcs",
    srcs = ["@com_alwaldend_src_tools_rfc//:filegroup"],
    prefix = "content/docs/misc/rfc",
)
