[[Submissions]]
  Id = 1046677697
  StatusDisplay = "Accepted"
  Lang = "python3"
  QuestionId = 160
  TitleSlug = "intersection-of-two-linked-lists"
  Code = "class Solution:\n    def getIntersectionNode(self, headA: ListNode, headB: ListNode) -> Optional[ListNode]:\n        if not headA or not headB:\n            return None\n        \n        tail1, tail2 = headA, headB\n        while tail1 != tail2:\n            tail1 = tail1.next if tail1 else headB\n            tail2 = tail2.next if tail2 else headA\n        \n        return tail2\n    "
  Title = "Intersection of Two Linked Lists"
  Url = "/submissions/detail/1046677697/"
  LangName = "Python3"
  Timestamp = 1694449936
  Status = 10
  Runtime = "119 ms"
  IsPending = "Not Pending"
  Memory = "31.8 MB"
  CompareResult = "111111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
