note_id = 1520716968951
guid = "ueiG_ASqVl"
note_type_id = 1496733135171
note_type = "chinese"
tags = ["B1", "Grammatical_Structures", "SentencePatterns"]

[[cards]]
id = 1520716974815
ordinal = 0

[fields]
article-title = 'Expressing "when" with "dengdao"'
english = 'I will make arrangements when the boss signs the paper.'
example-sentence = ''
example-type = ''
grammar-construct = '等(到) + Time / Event ，Subj. + 再 / 就 + Predicate'
hanzi = '等到老板签了字，我再做安排。'
notes = ''
pinyin = 'Děngdào lǎobǎn qiān le zì, wǒ zài zuò ānpái.'
source = 'https://resources.allsetlearning.com/chinese/grammar/ASG68F61'
