load("@rules_docs//docs:defs.bzl", "docs_filegroup")
load("//tools/release/main/bzl:al_release_binary.bzl", "al_release_binary")

docs_filegroup(
    name = "docs",
    srcs = glob(["*.md"]),
    visibility = ["//:__pkg__"],
    deps = subpackages(
        include = ["*"],
        allow_empty = True,
        exclude = ["rules_*"],
    ) + [
        "@rules_binary_toolchain//:docs",
        "@rules_docs//:docs",
        "@rules_docs_gazelle//:docs",
        "@rules_promptfoo//:docs",
        "@rules_promptfoo_gazelle//:docs",
        "@rules_skill//:docs",
        "@rules_skill_gazelle//:docs",
        "@rules_template//:docs",
    ],
)

al_release_binary(
    name = "deploy_heads",
    srcs = [
        "//projects/{}/releases:head".format(package)
        for package in subpackages(
            include = ["*"],
            exclude = [
                "xray_manager",
                "cgit",
                "agents",
                "alwaldend.com",
                "ansible_collection",
                "bazel_registry",
                "bazel_agent",
                "useless_qt_gui",
                "rules_template",
                "rules_binary_toolchain",
                "rules_docs",
                "rules_docs_gazelle",
                "rules_promptfoo",
                "rules_promptfoo_gazelle",
                "rules_skill",
                "rules_skill_gazelle",
            ],
        )
    ] + [],
)
