"Project packages that receive reusable landing pages and GitHub Pages repos."

PROJECTS = [
    "al",
    "android_launcher",
    "ansible_collection",
    "autoscroll",
    "bazel_agent",
    "cgit",
    "ci_platform",
    "dotfiles",
    "goal",
    "infinitime",
    "kustomization",
    "leetcode_downloader",
    "mcp_cordis",
    "nexus_security_plugin",
    "rules_binary_toolchain",
    "rules_docs",
    "rules_docs_gazelle",
    "rules_hugo",
    "rules_promptfoo",
    "rules_promptfoo_gazelle",
    "rules_skill",
    "rules_skill_gazelle",
    "rules_template",
    "sri",
    "tf_modules",
    "useless_qt_gui",
    "xray_manager",
]
