load("//tools/docs:defs.bzl", "docs_filegroup")
load("//tools/terraform:defs.bzl", "terraform_binary_map")

docs_filegroup(
    name = "docs",
    srcs = glob(["*.md"]),
    visibility = ["//infra/openstack:__pkg__"],
)

terraform_binary_map(
    name = "tf",
    configs = ["//infra/openstack:al"],
    data = glob(["*.tf"]) + [
        ".terraform.lock.hcl",
        "//infra/openstack/ansible:group_vars",
        "//infra/openstack/ansible:inventory",
        "//tools/vault/tf_backend",
        "//tools/vault/injector",
    ],
    run_args = [
        "--plugin_label",
        "tf",
    ],
)
