load("@rules_docs//docs:defs.bzl", "docs_filegroup")

exports_files([
    "agent_operations.json",
    "extensions.bzl",
])

docs_filegroup(
    name = "docs",
    srcs = ["README.md"],
    prefix = "content/docs/tools/rules_terraform",
    visibility = ["//visibility:public"],
    deps = [
        "//cmd/terraform:docs",
        "//openspec:docs",
    ],
)
