- tags:
    - update_all_packages
  block:
    - name: Update all packages
      ansible.builtin.package:
        name: "*"
        state: latest
    - name: Check if a reboot is required.
      register: update_all_packages_required_file_result
      ansible.builtin.stat:
        path: /var/run/reboot-required
        get_checksum: no
    - name: Reboot the server
      ansible.builtin.reboot:
      when: update_all_packages_required_file_result.stat.exists
