load("@rules_docs//docs:defs.bzl", "docs_filegroup")

docs_filegroup(
    name = "docs",
    srcs = glob(["*.md"]),
    prefix = "content/docs/misc",
    visibility = ["//projects/alwaldend.com/content/docs:__pkg__"],
    deps = [
        "//{}/{}:docs".format(
            package_name(),
            subpackage,
        )
        for subpackage in subpackages(include = ["*"])
    ],
)
