load("//tools/bzl/main/bzl:al_bzl_library_map.bzl", "al_bzl_library_map")
load("//tools/docs:defs.bzl", "docs_filegroup")

al_bzl_library_map(
    name = "libs",
    libs = {
        "al_http_server_binary": [
            "@bazel_skylib//lib:shell",
            "@rules_pkg//pkg:bzl_srcs",
        ],
    },
    visibility = ["//:__subpackages__"],
)

docs_filegroup(
    name = "docs",
    srcs = glob(["*.md"]),
    visibility = ["//tools/http_server:__pkg__"],
    deps = [
        ":libs.stardoc",
    ],
)
