[[Submissions]]
  Id = 1062853417
  StatusDisplay = "Accepted"
  Lang = "python3"
  QuestionId = 56
  TitleSlug = "merge-intervals"
  Code = "class Solution:\n    def merge(self, intervals: List[List[int]]) -> List[List[int]]:\n\n        intervals.sort(key=lambda item: item[0])\n\n        merged = []\n        for start, end in intervals:\n            # if the list of merged intervals is empty or if the current\n            # interval does not overlap with the previous, simply append it.\n            if not merged or merged[-1][1] < start:\n                merged.append([start, end])\n            else:\n            # otherwise, there is overlap, so we merge the current and previous\n            # intervals.\n                merged[-1][1] = max(merged[-1][1], end)\n\n        return merged"
  Title = "Merge Intervals"
  Url = "/submissions/detail/1062853417/"
  LangName = "Python3"
  Timestamp = 1696058246
  Status = 10
  Runtime = "140 ms"
  IsPending = "Not Pending"
  Memory = "21.4 MB"
  CompareResult = "11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
