note_id = 1031
guid = "tHCf1KOcU#"
note_type_id = 1496733135171
note_type = "chinese"
tags = ["Reverend_Insanity"]

[[cards]]
id = 1062
ordinal = 0

[fields]
article-title = ''
english = 'right;	correct;	couple;	pair;	towards;	at;	for;	to face;	opposite;	to treat (sb a certain way);	to match together;	to adjust;	to fit;	to suit;	to answer;	to reply;	classifier: couple.'
example-sentence = ' 方源对局势洞若观火,不过即便死亡将临,他仍旧是面不改色,神情平淡'
example-type = ''
grammar-construct = ''
hanzi = '对'
notes = ''
pinyin = '<span class="tone4">duì</span>	 <!-- dui -->'
source = ''
