note_id = 3049
guid = "Q8uun6k-6c"
note_type_id = 1496733135171
note_type = "chinese"
tags = ["leech", "Reverend_Insanity"]

[[cards]]
id = 3100
ordinal = 0

[fields]
article-title = ''
english = 'to foresee;	to predict;	to forecast;	to envision;	foresight;	intuition;	vision.'
example-sentence = ' 这种结果,他也早有预见'
example-type = ''
grammar-construct = ''
hanzi = '预见'
notes = ''
pinyin = '<span class="tone4">yù</span><span class="tone4">jiàn</span>	 <!-- yu jian -->'
source = ''
