note_id = 6015
guid = "nF:UTM8V:7"
note_type_id = 1496733135171
note_type = "chinese"
tags = ["Reverend_Insanity"]

[[cards]]
id = 6035
ordinal = 0

[fields]
article-title = ''
english = 'to leave (a room etc);	to go out through (a door etc).'
example-sentence = ' 大典完毕,众人慢慢地从地板上站起身来,静静地走出庄严的祠堂'
example-type = ''
grammar-construct = ''
hanzi = '走出'
notes = ''
pinyin = '<span class="tone3">zǒu</span><span class="tone1">chū</span>	 <!-- zou chu -->'
source = ''
