note_id = 6996
guid = "Ozx{#e?[B&"
note_type_id = 1496733135171
note_type = "chinese"
tags = ["Reverend_Insanity"]

[[cards]]
id = 6998
ordinal = 0

[fields]
article-title = ''
english = 'to emerge in large numbers;	to spring up;	to emerge prominently.'
example-sentence = '不错,白家寨、熊家寨这些年都有天才涌现'
example-type = ''
grammar-construct = ''
hanzi = '涌现'
notes = ''
pinyin = '<span class="tone3">yǒng</span><span class="tone4">xiàn</span>	 <!-- yong xian -->'
source = ''
