note_id = 7042
guid = "k_jb|jy_l|"
note_type_id = 1496733135171
note_type = "chinese"
tags = ["Reverend_Insanity"]

[[cards]]
id = 7090
ordinal = 0

[fields]
article-title = ''
english = 'to walk;	to go;	to run;	to move (of vehicle);	to visit;	to leave;	to go away;	to die (euph.);	from;	through;	away (in compound verbs, such as 撤走);	to change (shape, form, meaning).'
example-sentence = '三月能言,四月能走'
example-type = ''
grammar-construct = ''
hanzi = '走'
notes = ''
pinyin = '<span class="tone3">zǒu</span>	 <!-- zou -->'
source = ''
