note_id = 8012
guid = "mEsw_U9rfr"
note_type_id = 1496733135171
note_type = "chinese"
tags = ["Reverend_Insanity"]

[[cards]]
id = 8031
ordinal = 0

[fields]
article-title = ''
english = 'final;	last;	finally;	ultimate.'
example-sentence = '  古月族长最后一个走出宗祖祠堂,慢慢地关上门,便听到走廊中家老们的议论声音'
example-type = ''
grammar-construct = ''
hanzi = '最后'
notes = ''
pinyin = '<span class="tone4">zuì</span><span class="tone4">hòu</span>	 <!-- zui hou -->'
source = ''
