note_id = 9034
guid = "y,C@Yz]Q2l"
note_type_id = 1496733135171
note_type = "chinese"
tags = ["Reverend_Insanity"]

[[cards]]
id = 9076
ordinal = 0

[fields]
article-title = ''
english = 'every year;	each year;	yearly.'
example-sentence = ' 每年为了争夺这些天才后辈,家老们彼此之间都是争的面红耳赤,头破血流'
example-type = ''
grammar-construct = ''
hanzi = '每年'
notes = ''
pinyin = '<span class="tone3">měi</span><span class="tone2">nián</span>	 <!-- mei nian -->'
source = ''
