[[Submissions]]
  Id = 1715690764
  StatusDisplay = "Accepted"
  Lang = "python3"
  QuestionId = 2498
  TitleSlug = "smallest-subarrays-with-maximum-bitwise-or"
  Code = "class Solution:\n    def smallestSubarrays(self, nums: List[int]) -> List[int]:\n        n = len(nums)\n        pos = [-1] * 31\n        ans = [0] * n\n        for i in range(n - 1, -1, -1):\n            j = i\n            for bit in range(31):\n                if (nums[i] & (1 << bit)) == 0:\n                    if pos[bit] != -1:\n                        j = max(j, pos[bit])\n                else:\n                    pos[bit] = i\n            ans[i] = j - i + 1\n        return ans"
  Title = "Smallest Subarrays With Maximum Bitwise OR"
  Url = "/submissions/detail/1715690764/"
  LangName = "Python3"
  Timestamp = 1753786788
  Status = 10
  Runtime = "985 ms"
  IsPending = "Not Pending"
  Memory = "29 MB"
  CompareResult = "11111111111111111111111111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
