load("@bazel_skylib//:bzl_library.bzl", "bzl_library")
load("//tools/docs:defs.bzl", "docs_filegroup")

bzl_library(
    name = "defs",
    srcs = ["defs.bzl"],
    visibility = ["//:__subpackages__"],
    deps = ["@rules_pkg//pkg:bzl_srcs"],
)

docs_filegroup(
    name = "docs",
    srcs = glob(["*.md"]),
    visibility = ["//tools:__pkg__"],
)
