[[Submissions]]
  Id = 1090492801
  StatusDisplay = "Accepted"
  Lang = "golang"
  QuestionId = 1552
  TitleSlug = "build-an-array-with-stack-operations"
  Code = "func buildArray(target []int, n int) []string {\n    ops := []string{}\n    length := len(target)\n    matchNext, matchNextVal := 0, target[0]\n    for i := 1; i <= n; i++ {\n        if i == matchNextVal {\n            ops = append(ops, \"Push\")\n            matchNext += 1\n            if matchNext == length {\n                break\n            }\n            matchNextVal = target[matchNext]\n        } else {\n            ops = append(ops, \"Push\", \"Pop\")\n        }\n    }\n    return ops\n}"
  Title = "Build an Array With Stack Operations"
  Url = "/submissions/detail/1090492801/"
  LangName = "Go"
  Timestamp = 1699002886
  Status = 10
  Runtime = "0 ms"
  IsPending = "Not Pending"
  Memory = "2.4 MB"
  CompareResult = "1111111111111111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
