note_id = 1520716967438
guid = "c.ObS/*&f^"
note_type_id = 1496733135171
note_type = "chinese"
tags = ["AdverbswithAdjectives", "B1", "Parts_of_Speech"]

[[cards]]
id = 1520716973302
ordinal = 0

[fields]
article-title = 'Expressing "quite" with "ting"'
english = 'We all miss you a lot.'
example-sentence = ''
example-type = ''
grammar-construct = '挺 + [Verb Phrase] + 的'
hanzi = '我们都挺想你的。'
notes = ''
pinyin = 'Wǒmen dōu tǐng xiǎng nǐ de.'
source = 'https://resources.allsetlearning.com/chinese/grammar/ASGDF1F7'
