[[Submissions]]
  Id = 1000208581
  StatusDisplay = "Accepted"
  Lang = "python3"
  QuestionId = 459
  TitleSlug = "repeated-substring-pattern"
  Code = "class Solution:\n    def repeatedSubstringPattern(self, s: str) -> bool:\n        length = len(s)\n        for i in range(1, length // 2 + 1):\n            if length % i != 0:\n                continue\n            \n            if s == s[:i] * (length // i):\n                return True\n        \n        return False"
  Title = "Repeated Substring Pattern"
  Url = "/submissions/detail/1000208581/"
  LangName = "Python3"
  Timestamp = 1689947734
  Status = 10
  Runtime = "62 ms"
  IsPending = "Not Pending"
  Memory = "16.3 MB"
  CompareResult = "111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
