load("@rules_openspec_npm//:@fission-ai/openspec/package_json.bzl", openspec = "bin")
load("//main/bzl:openspec.bzl", "OPENSPEC_ENV")

package(default_visibility = ["//visibility:public"])

openspec.openspec_binary(
    name = "openspec",
    chdir = "$${BUILD_WORKSPACE_DIRECTORY}/$${OPENSPEC_PROJECT:-infra/src}",
    data = ["//:node_modules/@fission-ai/openspec"],
    env = OPENSPEC_ENV,
)
