load("@rules_pkg//pkg:mappings.bzl", "pkg_filegroup", "pkg_files", "strip_prefix")
load("//tools/docs:defs.bzl", "docs_filegroup")

docs_filegroup(
    name = "docs",
    srcs = glob(["*.md"]) + ["galaxy.yml"],
    visibility = ["//projects:__pkg__"],
    deps = [
        "//projects/ansible_collection/playbooks:docs",
        "//projects/ansible_collection/roles:docs",
    ],
)

pkg_files(
    name = "galaxy",
    srcs = [":galaxy.yml"],
)

pkg_filegroup(
    name = "collection",
    srcs = [
        ":galaxy",
        "//projects/ansible_collection/playbooks",
        "//projects/ansible_collection/roles",
    ],
    prefix = "alwaldend/main",
    visibility = ["//:__subpackages__"],
)

pkg_filegroup(
    name = "collection_prefix",
    srcs = [":collection"],
    prefix = "collections/ansible_collections",
)

pkg_filegroup(
    name = "collections",
    srcs = [
        ":collection_prefix",
        "@com_ansible_galaxy",
    ],
    visibility = ["//:__subpackages__"],
)
