load("@rules_docs//docs:defs.bzl", "docs_filegroup")
load("@rules_pkg//pkg:mappings.bzl", "pkg_filegroup", "pkg_files", "strip_prefix")
load("//projects/al/rules/al:al_config.bzl", "al_config")
load("//tools/vault:defs.bzl", "vault_binary_map")

docs_filegroup(
    name = "docs",
    srcs = glob(["*.md"]) + ["galaxy.yml"],
    visibility = [
        "//projects:__pkg__",
        "//projects/ansible_collection/landing:__pkg__",
    ],
    deps = [
        "//projects/ansible_collection/playbooks:docs",
        "//projects/ansible_collection/roles:docs",
        "//projects/ansible_collection/tf:docs",
    ],
)

pkg_files(
    name = "galaxy",
    srcs = [":galaxy.yml"],
)

pkg_filegroup(
    name = "collection",
    srcs = [
        ":galaxy",
        "//projects/ansible_collection/playbooks",
        "//projects/ansible_collection/roles",
    ],
    prefix = "alwaldend/main",
    visibility = ["//:__subpackages__"],
)

pkg_filegroup(
    name = "collection_prefix",
    srcs = [":collection"],
    prefix = "collections/ansible_collections",
)

pkg_filegroup(
    name = "collections",
    srcs = [
        ":collection_prefix",
        "@com_ansible_galaxy",
    ],
    visibility = ["//:__subpackages__"],
)

filegroup(
    name = "dnsconfig",
    srcs = ["dnsconfig.json"],
    visibility = [
        "//infra:__pkg__",
        "//infra/dns:__pkg__",
        "//projects/alwaldend.com:__subpackages__",
        "//projects/ansible_collection/tf:__pkg__",
    ],
)

al_config(
    name = "al",
    srcs = ["al.lua"],
    visibility = ["//projects/ansible_collection/tf:__pkg__"],
    deps = ["//infra:al"],
)

vault_binary_map(
    name = "vault",
    configs = [":al"],
)
