load("@bazel_skylib//rules:build_test.bzl", "build_test")
load("@rules_pkg//pkg:mappings.bzl", "pkg_filegroup", "pkg_files")
load(
    "@rules_qt//:qt.bzl",
    "qt_cc_binary",
    "qt_cc_library",
    "qt_resource_via_qrc",
    "qt_ui_library",
)

build_test(
    name = "build_test",
    targets = [
        ":useless_qt_gui",
    ],
)

pkg_filegroup(
    name = "docs",
    srcs = [":docs_files"],
    visibility = ["//projects:__pkg__"],
)

pkg_files(
    name = "docs_files",
    srcs = glob(["*.md"]),
    prefix = "content/docs/{}".format(package_name()),
)

qt_resource_via_qrc(
    name = "resources",
    files = ["//projects/useless_qt_gui/main/res:images"],
    qrc_file = "resources.qrc",
)

qt_ui_library(
    name = "mainwindow_ui",
    includes = ["."],
    ui = "mainwindow.ui",
    deps = ["@rules_qt//:qt_widgets"],
)

qt_cc_library(
    name = "application",
    srcs = [
        "main/cpp/mainwindow.cpp",
        "main/cpp/menubutton.cpp",
        "main/cpp/systembutton.cpp",
    ],
    hdrs = [
        "main/cpp/mainwindow.h",
        "main/cpp/menubutton.h",
        "main/cpp/systembutton.h",
    ],
    includes = ["main/cpp"],
    deps = [
        ":mainwindow_ui",
        "@rules_qt//:qt_widgets",
    ],
)

qt_cc_binary(
    name = "useless_qt_gui",
    srcs = ["main/cpp/main.cpp"],
    deps = [
        ":application",
        ":resources",
        "@rules_qt//:qt_widgets",
    ],
)
