[[Submissions]]
  Id = 1000087386
  StatusDisplay = "Accepted"
  Lang = "python3"
  QuestionId = 1603
  TitleSlug = "running-sum-of-1d-array"
  Code = "class Solution:\r\n    def runningSum(self, nums: List[int]) -> List[int]:\r\n        for i in range(1, len(nums)):\r\n            nums[i] += nums[i-1]\r\n        return nums"
  Title = "Running Sum of 1d Array"
  Url = "/submissions/detail/1000087386/"
  LangName = "Python3"
  Timestamp = 1689934986
  Status = 10
  Runtime = "48 ms"
  IsPending = "Not Pending"
  Memory = "16.7 MB"
  CompareResult = "11111111111111111111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
