[[Submissions]]
  Id = 1050711409
  StatusDisplay = "Accepted"
  Lang = "python3"
  QuestionId = 1753
  TitleSlug = "path-with-minimum-effort"
  Code = "class Solution:\r\n\r\n    def minimumEffortPath(self, heights: List[List[int]]) -> int:\r\n        rows, cols = len(heights), len(heights[0])\r\n        directions = [(0, 1), (0, -1), (1, 0), (-1, 0)]\r\n        dist = [[math.inf for _ in range(cols)] for _ in range(rows)]\r\n        dist[0][0] = 0\r\n        minHeap = [(0, 0, 0)] \r\n        while minHeap:\r\n            effort, x, y = heappop(minHeap)\r\n            if x == rows - 1 and y == cols - 1:\r\n                return effort\r\n            for dx, dy in directions:\r\n                nx, ny = x + dx, y + dy\r\n                if 0 <= nx < rows and 0 <= ny < cols:\r\n                    new_effort = max(effort, abs(heights[x][y] - heights[nx][ny]))\r\n                    if new_effort < dist[nx][ny]:\r\n                        dist[nx][ny] = new_effort\r\n                        heappush(minHeap, (new_effort, nx, ny))"
  Title = "Path With Minimum Effort"
  Url = "/submissions/detail/1050711409/"
  LangName = "Python3"
  Timestamp = 1694852754
  Status = 10
  Runtime = "521 ms"
  IsPending = "Not Pending"
  Memory = "17.7 MB"
  CompareResult = "111111111111111111111111111111111111111111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
