load("@rules_docs//docs:defs.bzl", "docs_filegroup")

filegroup(
    name = "editorconfig",
    srcs = ["//:.editorconfig"],
    visibility = ["//:__subpackages__"],
)

alias(
    name = "shfmt",
    actual = "//third_party/com_github_mvdan_sh:shfmt",
    visibility = ["//:__subpackages__"],
)

docs_filegroup(
    name = "docs",
    srcs = glob(["*.md"]),
    visibility = ["//tools:__pkg__"],
)
