load("@rules_go//go:def.bzl", "go_binary")
load("@rules_pkg//pkg:mappings.bzl", "pkg_filegroup", "pkg_files")

go_binary(
    name = "fixture_binary",
    srcs = ["main.go"],
)

pkg_files(
    name = "files",
    srcs = [":fixture_binary"],
    prefix = "collections/ansible_collections/molecule/fixture/files",
    renames = {":fixture_binary": "renamed_executable"},
)

pkg_filegroup(
    name = "mapping",
    srcs = [":files"],
    visibility = ["//tools/molecule/test:__pkg__"],
)
