load("@rules_docs//docs:defs.bzl", "docs_filegroup")
load("@rules_openspec//main/bzl:workspace.bzl", "openspec_workspace")

openspec_workspace(
    name = "source",
    srcs = ["config.yaml"] + glob(
        [
            "specs/**/*.md",
            "changes/**",
        ],
        allow_empty = True,
    ),
    visibility = ["//infra/src/openspec/validation"],
)

docs_filegroup(
    name = "docs",
    srcs = glob(
        [
            "*.md",
            "specs/**/*.md",
        ],
        allow_empty = True,
    ),
    visibility = ["//projects/bazel_agent:__pkg__"],
)
