[[Submissions]]
  Id = 1039602903
  StatusDisplay = "Accepted"
  Lang = "python3"
  QuestionId = 73
  TitleSlug = "set-matrix-zeroes"
  Code = "class Solution:\n    def setZeroes(self, matrix: List[List[int]]) -> None:\n        \"\"\"\n        Do not return anything, modify matrix in-place instead.\n        \"\"\"\n        rows_count, cols_count = len(matrix), len(matrix[0])\n        flip_rows, flip_cols = set(), set()\n\n        for row in range(rows_count):\n            for col in range(cols_count):\n                if matrix[row][col] == 0:\n                    flip_rows.add(row)\n                    flip_cols.add(col)\n\n        while flip_rows:\n            row = flip_rows.pop()\n            for col in range(cols_count):\n                if matrix[row][col] != 0:\n                    matrix[row][col] = 0\n        \n        while flip_cols:\n            col = flip_cols.pop()\n            for row in range(rows_count):\n                if matrix[row][col] != 0:\n                    matrix[row][col] = 0\n        \n            \n"
  Title = "Set Matrix Zeroes"
  Url = "/submissions/detail/1039602903/"
  LangName = "Python3"
  Timestamp = 1693759778
  Status = 10
  Runtime = "121 ms"
  IsPending = "Not Pending"
  Memory = "17.3 MB"
  CompareResult = "111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
