load("@rules_docs//docs:defs.bzl", "docs_filegroup")
load("//projects/leetcode_downloader/main/bzl:al_leetcode_submissions.bzl", "al_leetcode_submissions")

docs_filegroup(
    name = "docs",
    srcs = glob(["*.md"]),
    visibility = ["//data:__pkg__"],
)

al_leetcode_submissions(
    name = "leetcode_submissions",
    srcs = glob(["languages/*/questions/*/submissions/*/submission.toml"]),
    visibility = ["//projects/alwaldend.com/content/docs/misc/leetcode_submissions:__pkg__"],
)
