note_id = 1520716965418
guid = "RdDVR4kl)C"
note_type_id = 1496733135171
note_type = "chinese"
tags = ["A1", "Parts_of_Speech", "Verbphrases"]

[[cards]]
id = 1520716971282
ordinal = 0

[fields]
article-title = 'How to do something with "zenme"'
english = 'How do you study Chinese?'
example-sentence = ''
example-type = ''
grammar-construct = 'Subj. + 怎么 + Verb + Obj.'
hanzi = '你们怎么学中文？'
notes = ''
pinyin = 'Nǐmen zěnme xué Zhōngwén?'
source = 'https://resources.allsetlearning.com/chinese/grammar/ASGH2MNO'
