note_id = 1520716969435
guid = "oyQf~UhdS7"
note_type_id = 1496733135171
note_type = "chinese"
tags = ["B1", "Comparisons", "TimeWords"]

[[cards]]
id = 1520716975299
ordinal = 0

[fields]
article-title = 'Comparing "gang" and "gangcai"'
english = "She just didn't ask me this question."
example-sentence = ''
example-type = 'invalid'
grammar-construct = '刚 + Adj.'
hanzi = '她刚没问我这个问题。'
notes = "Don't use 刚 with 没 in the past."
pinyin = ''
source = 'https://resources.allsetlearning.com/chinese/grammar/ASGJFFWG'
