note_id = 1634415221914
guid = "mM$]Y+e8-J"
note_type_id = 1630447360003
note_type = "python-basic-and-reversed"
tags = []

[[cards]]
id = 1634415221915
ordinal = 0

[fields]
additional-info = ''
answer = '<i>file</i>.read()'
example = ''
question = '<b>File method</b>&nbsp;that returns all the files content as a single string.'
version = ''
with-options = ''
