note_id = 1634417139731
guid = "hTpF!HO)eF"
note_type_id = 1630447360003
note_type = "python-basic-and-reversed"
tags = []

[[cards]]
id = 1634417139733
ordinal = 0

[fields]
additional-info = ''
answer = '<i>file</i>.seekable()'
example = ''
question = "<b>File method</b>&nbsp;that returns True if a file allows us to change it's position, else False."
version = ''
with-options = ''
