apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: acme
spec:
  acme:
    email: 5e4789ef-3404-403a-9@simplelogin.alwaldend.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: acme-private-key
    solvers:
      - selector:
          dnsZones:
            - alwaldend.com
        dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cert-manager-secret
              key: CLOUDFLAREAPI_API_TOKEN
