load("@rules_docs//docs:defs.bzl", "docs_filegroup")
load("//tools/ansible/main/bzl:al_ansible_role.bzl", "al_ansible_role")

docs_filegroup(
    name = "docs",
    srcs = glob(["*.md"]),
    visibility = ["//projects/ansible_collection/roles:__pkg__"],
    deps = [
        ":role.docs",
    ],
)

al_ansible_role(
    name = "role",
    srcs = glob(["**"]) + [
        "@com_alwaldend_src_tools_vault_linux_x86_64//:vault_filegroup",
    ],
    renames = {
        "@com_alwaldend_src_tools_vault_linux_x86_64//:vault_filegroup": "files/vault",
    },
    visibility = ["//:__subpackages__"],
)
