[[Submissions]]
  Id = 693605291
  StatusDisplay = "Accepted"
  Lang = "golang"
  QuestionId = 283
  TitleSlug = "move-zeroes"
  Code = "func moveZeroes(numbers []int) {\n\tindex_zero := -1\n\t// sliding window algorithm\n\tfor index, number := range numbers {\n\t\t// if index_zero is not set, then the first zero is index_zero\n\t\tif index_zero == -1 && number == 0 {\n\t\t\tindex_zero = index\n\t\t}\n\t\t// there is no need to move numbers if there were no zeros before\n\t\t// there is no need to move zeros\n\t\tif index_zero == -1 || number == 0 {\n\t\t\tcontinue\n\t\t}\n\t\t// after some zeros we encounter a non-zero number\n\t\t// moving that number to the beginning of zeros\n\t\tnumbers[index_zero] = number\n\t\t// current number becomes zero\n\t\tnumbers[index] = 0\n\t\t// moving the index\n\t\tindex_zero++\n\t}\n}"
  Title = "Move Zeroes"
  Url = "/submissions/detail/693605291/"
  LangName = "Go"
  Timestamp = 1651747170
  Status = 10
  Runtime = "36 ms"
  IsPending = "Not Pending"
  Memory = "8.6 MB"
  CompareResult = "11111111111111111111111111111111111111111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
