note_id = 1520716970759
guid = "v]wpybAki|"
note_type_id = 1496733135171
note_type = "chinese"
tags = ["B2", "Comparisons", "Prepositions"]

[[cards]]
id = 1520716976623
ordinal = 0

[fields]
article-title = 'Comparing "duiyu" and "zhiyu"'
english = "For this topic, I don't think there is anything to be discussed."
example-sentence = ''
example-type = ''
grammar-construct = '对于 + Modifier， Subj. + Predicate'
hanzi = '对于这个话题，我觉得没什么可讨论的。'
notes = ''
pinyin = ''
source = 'https://resources.allsetlearning.com/chinese/grammar/ASGC01S0'
