note_id = 1520716965407
guid = "N;RhXkeGk^"
note_type_id = 1496733135171
note_type = "chinese"
tags = ["A1", "Auxiliaryverbs", "Parts_of_Speech"]

[[cards]]
id = 1520716971271
ordinal = 0

[fields]
article-title = 'Expressing permission with "keyi"'
english = 'None of us may go.'
example-sentence = ''
example-type = ''
grammar-construct = 'Subj. + 不 + 可以 + Verb + Obj.'
hanzi = '我们都不可以去。'
notes = ''
pinyin = 'Wǒmen dōu bù kěyǐ qù.'
source = 'https://resources.allsetlearning.com/chinese/grammar/ASG6SPYK'
