repo(
    default_package_metadata = [
        "//data/license:default",
    ],
    default_visibility = ["//visibility:private"],
)

ignore_directories(
    [
        # Keep legitimate nested packages whose names start with "bazel-".
        "bazel-*",
        "**/external",
        "**/node_modules",
        "**/compile_commands.json",
        "**/out",
        "**/.bzlenv",
        "**/.aspect",
        "**/.cache",
        "**/.venv"
    ],
)
