- name: Setup laptop
  become: true
  force_handlers: true
  hosts: laptop01.laptops.alwaldend.com
  roles:
    - role: firewall
    - role: users
    - role: wireguard
    - role: ssh_port_forward
    - role: devsec.hardening.ssh_hardening
      tags:
        - hardening
  tasks:
    - name: Setup wireguard
      tags:
        - wireguard
      block:
        - name: ping vpn
          ansible.builtin.command:
            argv:
              - ping
              - -c
              - 1
              - "{{ hostvars.vpn1.wg_ipv4 }}"
        - name: ping cloudflare
          ansible.builtin.command:
            argv:
              - ping
              - -c
              - 1
              - 1.1.1.1
    - name: Update all packages
      tags:
        - packages
      ansible.builtin.package:
        name: "*"
        state: latest
