- name: Generate wireguard keys
  tags:
    - wireguard
    - local
  hosts: localhost
  become: false
  tasks:
    - name: Generate wireguard keys
      loop: "{{ groups['all'] }}"
      ansible.builtin.shell:
        chdir: "{{ wg_key_dir }}"
        creates: "{{ wg_key_dir }}/{{ hostvars[item].wg_interface }}.pub"
        cmd: >-
          umask 077 && 
            wg genkey | 
            tee '{{ hostvars[item].wg_interface }}.key' | 
            wg pubkey >'{{ hostvars[item].wg_interface }}.pub'
