package main

import (
	"context"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"time"

	"git.alwaldend.com/alwaldend/src/projects/al/api/al_proto"
	"git.alwaldend.com/alwaldend/src/projects/al/pkg/al"
	"git.alwaldend.com/alwaldend/src/projects/al/pkg/fp"
	"git.alwaldend.com/alwaldend/src/tools/vault/injector/injector_proto"
	"github.com/google/uuid"
)

type VaultSshFetcher struct {
	ctx       *al.CmdCtx
	config    *al_proto.Config
	vault     *al.VaultStore
	opFetcher *OpFetcher
	cleaner   *Cleaner
}

func NewVaultSshFetcher(ctx *al.CmdCtx, config *al_proto.Config, vault *al.VaultStore, opFetcher *OpFetcher, cleaner *Cleaner) *VaultSshFetcher {
	return &VaultSshFetcher{ctx, config, vault, opFetcher, cleaner}
}

var _ ResourceFetcher = (*VaultSshFetcher)(nil)

func (self *VaultSshFetcher) String() string {
	return "com.alwaldend.src.tools.vault.injector.VaultSshFetcher"
}

// Create an ssh key and sign it
func (self *VaultSshFetcher) Get(ctx context.Context, r *injector_proto.Resource, d []*ResourceResult) (result *ResourceResult, resultErr error) {
	client, err := fp.Get(self.vault.Client(ctx, r.VaultConn, r.VaultAuth))
	if err != nil {
		return nil, fmt.Errorf("could not create vault client: %w", al.SanitizeVaultError(err))
	}
	ssh := r.GetVaultSsh()
	if ssh == nil {
		return nil, fmt.Errorf("missing ssh config")
	}
	if ssh.Backend == "" {
		return nil, fmt.Errorf("empty backend")
	}
	dir, err := os.MkdirTemp("", fmt.Sprintf("%s_*", self.String()))
	if err != nil {
		return nil, fmt.Errorf("could not create a temporary directory: %w", al.SanitizeVaultError(err))
	}
	successful := false
	defer func() {
		if !successful {
			resultErr = errors.Join(resultErr, os.RemoveAll(dir))
		}
	}()

	privateKey := filepath.Join(dir, "private_key")
	passphrase := uuid.New().String()
	publicKey := fmt.Sprintf("%s.pub", privateKey)
	publicKeySigned := fmt.Sprintf("%s.pub", privateKey)
	passphraseScript := fmt.Sprintf("%s.sh", privateKey)
	if err := os.WriteFile(passphraseScript, []byte(fmt.Sprintf("#!/usr/bin/env sh\necho '%s'", passphrase)), 0o700); err != nil {
		return nil, fmt.Errorf("could not write the passphrase script: %w", al.SanitizeVaultError(err))
	}
	cmd := exec.CommandContext(
		ctx,
		"ssh-keygen",
		"-t",
		"Ed25519",
		"-C",
		fmt.Sprintf("Automatically generated by %s at %s", self.String(), time.Now().String()),
		"-N",
		"", // ssh-keygen does not support passing the passphrase using stdin or env, and it's hard to provide the passphrase automatically
		"-f",
		privateKey,
	)
	cmd.Stderr = self.ctx.Stderr
	cmd.Stdout = self.ctx.Stderr
	cmd.Stdin = self.ctx.Stdin
	if err := cmd.Run(); err != nil {
		return nil, fmt.Errorf("could not generate a key: %w", al.SanitizeVaultError(err))
	}
	publicKeyContent, err := os.ReadFile(publicKey)
	if err != nil {
		return nil, fmt.Errorf("could not read the generated public key: %w", al.SanitizeVaultError(err))
	}
	data := map[string]any{
		"public_key": fmt.Sprintf("%s\n", publicKeyContent),
	}
	if ssh.Ttl != 0 {
		data["ttl"] = ssh.Ttl
	}
	resp, err := client.Client.Logical().WriteWithContext(ctx, ssh.Backend, data)
	if err != nil {
		return nil, fmt.Errorf("could not sign the key: %w", al.SanitizeVaultError(err))
	}
	if resp == nil {
		return nil, fmt.Errorf("empty signing response")
	}
	publicKeySignedAny, ok := resp.Data["signed_key"]
	if !ok {
		return nil, fmt.Errorf("vault response is missing the signed key")
	}
	publicKeySignedContent, ok := publicKeySignedAny.(string)
	if !ok {
		return nil, fmt.Errorf("signed public key is not a string")
	}
	if err := os.WriteFile(publicKeySigned, []byte(publicKeySignedContent), 0o600); err != nil {
		return nil, fmt.Errorf("could not write signed public key to file: %w", al.SanitizeVaultError(err))
	}
	res := &ResourceResult{
		Name: r.Name,
		Data: map[string]string{
			"passphrase":        passphrase,
			"passphrase_script": passphraseScript,
			"private_key":       privateKey,
			"public_key":        publicKey,
			"public_key_signed": publicKeySigned,
		},
	}
	if err := self.cleaner.Add(dir); err != nil {
		return nil, err
	}
	successful = true
	return res, nil
}
