[[Submissions]]
  Id = 1091201779
  StatusDisplay = "Accepted"
  Lang = "golang"
  QuestionId = 162
  TitleSlug = "find-peak-element"
  Code = "func findPeakElement(nums []int) int {\n    left := 0\n    right := len(nums) - 1\n    \n    for left < right {\n        mid := left + (right - left) / 2\n        \n        if nums[mid] > nums[mid+1] {\n            // The peak is in the left half\n            right = mid\n        } else {\n            // The peak is in the right half\n            left = mid + 1\n        }\n    }\n    \n    return left\n}"
  Title = "Find Peak Element"
  Url = "/submissions/detail/1091201779/"
  LangName = "Go"
  Timestamp = 1699093828
  Status = 10
  Runtime = "3 ms"
  IsPending = "Not Pending"
  Memory = "2.7 MB"
  CompareResult = "111111111111111111111111111111111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
