[[Submissions]]
  Id = 1087492568
  StatusDisplay = "Accepted"
  Lang = "golang"
  QuestionId = 103
  TitleSlug = "binary-tree-zigzag-level-order-traversal"
  Code = "/**\n * Definition for a binary tree node.\n * type TreeNode struct {\n *     Val int\n *     Left *TreeNode\n *     Right *TreeNode\n * }\n */\nfunc zigzagLevelOrder(root *TreeNode) [][]int {\n    if root == nil {\n        return [][]int{}\n    }\n\n    queue, answer := []*TreeNode{root}, [][]int{}\n    leftToRight := true\n\n    for length := len(queue); length != 0; length = len(queue) {\n        answerRow := []int{}\n\n        for i := 0; i < length; i++ {\n            node := queue[0]\n            queue = queue[1:]\n\n            answerRow = append(answerRow, node.Val)\n            if left := node.Left; left != nil {\n                queue = append(queue, left)\n            }\n            if right := node.Right; right != nil {\n                queue = append(queue, right)\n            }\n        }\n        if !leftToRight {\n            slices.Reverse(answerRow)\n        }\n        leftToRight = !leftToRight\n        answer = append(answer, answerRow)\n    }\n\n    return answer\n}"
  Title = "Binary Tree Zigzag Level Order Traversal"
  Url = "/submissions/detail/1087492568/"
  LangName = "Go"
  Timestamp = 1698664488
  Status = 10
  Runtime = "1 ms"
  IsPending = "Not Pending"
  Memory = "2.5 MB"
  CompareResult = "111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
