[[Submissions]]
  Id = 1087501208
  StatusDisplay = "Accepted"
  Lang = "golang"
  QuestionId = 103
  TitleSlug = "binary-tree-zigzag-level-order-traversal"
  Code = "/**\n * Definition for a binary tree node.\n * type TreeNode struct {\n *     Val int\n *     Left *TreeNode\n *     Right *TreeNode\n * }\n */\nfunc zigzagLevelOrder(root *TreeNode) [][]int {\n    if root == nil {\n        return [][]int{}\n    }\n\n    queue, answer := []*TreeNode{root}, [][]int{}\n    ltr := true\n\n    for length := len(queue); length != 0; length = len(queue) {\n        answerRow := []int{}\n        for i := 0; i < length; i++ {\n            node := queue[i]\n            if node.Left != nil {\n                queue = append(queue, node.Left)\n            }\n            if node.Right != nil {\n                queue = append(queue, node.Right)\n            }\n            answerRow = append(answerRow, node.Val)\n        }\n        if !ltr {\n            slices.Reverse(answerRow)\n        }\n        queue = queue[length:]\n        ltr = !ltr\n        answer = append(answer, answerRow)\n    }\n\n    return answer\n}"
  Title = "Binary Tree Zigzag Level Order Traversal"
  Url = "/submissions/detail/1087501208/"
  LangName = "Go"
  Timestamp = 1698665567
  Status = 10
  Runtime = "2 ms"
  IsPending = "Not Pending"
  Memory = "2.6 MB"
  CompareResult = "111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
