[[Submissions]]
  Id = 1103345965
  StatusDisplay = "Accepted"
  Lang = "cpp"
  QuestionId = 1925
  TitleSlug = "count-nice-pairs-in-an-array"
  Code = "class Solution {\npublic:\n    int countNicePairs(vector<int>& nums) {\n        std::unordered_map<int, int> diffs{};\n        for (const int& num : nums) {\n            int revNum{};\n            int tempNum{num};\n            while(tempNum) {\n                revNum = (revNum * 10) + (tempNum % 10);\n                tempNum /= 10;\n            }\n            ++diffs[num - revNum];\n        }\n        int ans{};\n        double mod{std::pow(10, 9) + 7};\n        for (const auto& [num, count] : diffs) {\n            long pairs{(1L * count * count - count) / 2};\n            ans = std::fmod(ans + pairs, mod);\n        }\n        return ans;\n    }\n\n};"
  Title = "Count Nice Pairs in an Array"
  Url = "/submissions/detail/1103345965/"
  LangName = "C++"
  Timestamp = 1700559193
  Status = 10
  Runtime = "91 ms"
  IsPending = "Not Pending"
  Memory = "57.3 MB"
  CompareResult = "111111111111111111111111111111111111111111111111111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
