[[Submissions]]
  Id = 1068473154
  StatusDisplay = "Accepted"
  Lang = "python3"
  QuestionId = 343
  TitleSlug = "integer-break"
  Code = "class Solution:\n    def integerBreak(self, n: int) -> int:\n        if n < 4:\n            return n - 1\n        \n        @cache\n        def dp(num: int) -> int:\n            if num <= 3:\n                return num\n            ans = num\n            for i in range(2, num):\n                ans = max(ans, i * dp(num - i))\n            return ans\n\n        return dp(n)"
  Title = "Integer Break"
  Url = "/submissions/detail/1068473154/"
  LangName = "Python3"
  Timestamp = 1696584279
  Status = 10
  Runtime = "42 ms"
  IsPending = "Not Pending"
  Memory = "16.3 MB"
  CompareResult = "11111111111111111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
