node = use_extension("@rules_nodejs//nodejs:extensions.bzl", "node")
node.toolchain(
    node_version = "24.13.0",
)

pnpm = use_extension("@aspect_rules_js//npm:extensions.bzl", "pnpm")
pnpm.pnpm(
    name = "com_alwaldend_src_pnpm",
    pnpm_version = "10.22.0",
)
use_repo(pnpm, "com_alwaldend_src_pnpm")

npm = use_extension("@aspect_rules_js//npm:extensions.bzl", "npm")
npm.npm_translate_lock(
    name = "com_alwaldend_src_npm",
    bins = {
        "@fission-ai/openspec": ["openspec=./bin/openspec.js"],
        "typescript": [
            "tsc=./bin/tsc",
            "tsserver=./bin/tsserver",
        ],
        "lv_font_conv": ["lv_font_conv=./lv_font_conv.js"],
        "@mermaid-js/mermaid-cli": ["mmdc=./src/cli.js"],
        "prettier": ["prettier=./bin/prettier.cjs"],
        "postcss-cli": ["postcss=./index.js"],
    },
    data = [
        "//tools:pnpm-workspace.yaml",
    ],
    pnpm_lock = "//tools:pnpm-lock.yaml",
    public_hoist_packages = {
        "autoprefixer": ["tools"],
        "postcss-cli": ["tools"],
    },
    run_lifecycle_hooks = False,
    verify_node_modules_ignored = "//:.bazelignore",
)
use_repo(npm, "com_alwaldend_src_npm")
