# gazelle:java_extension disabled

load("@rules_docs//docs:defs.bzl", "docs_filegroup")

docs_filegroup(
    name = "docs",
    srcs = glob(["*.md"]),
    visibility = [
        "//projects:__pkg__",
        "//projects/android_launcher/landing:__pkg__",
    ],
    deps = [
        "//projects/android_launcher/releases:docs",
    ],
)

filegroup(
    name = "manifest",
    srcs = ["AndroidManifest.xml"],
    visibility = [":__subpackages__"],
)

filegroup(
    name = "proguard",
    srcs = ["proguard_rules.pro"],
    visibility = [":__subpackages__"],
)

filegroup(
    name = "dnsconfig",
    srcs = ["dnsconfig.json"],
    visibility = [
        "//infra:__pkg__",
        "//infra/dns:__pkg__",
        "//projects/alwaldend.com:__subpackages__",
    ],
)
