[[Submissions]]
  Id = 1177761223
  StatusDisplay = "Accepted"
  Lang = "python3"
  QuestionId = 1762
  TitleSlug = "furthest-building-you-can-reach"
  Code = "class Solution:\n   def furthestBuilding(self, h: List[int], b: int, l: int) -> int:\n       p = []\n       \n       i = 0\n       for i in range(len(h) - 1):\n           diff = h[i + 1] - h[i]\n           \n           if diff <= 0:\n               continue\n           \n           b -= diff\n           x = heapq.heappush(p, -diff)\n           print(x)\n           if b < 0:\n               b += -heapq.heappop(p)\n               l -= 1\n               \n           if l < 0:\n               return i\n       return len(h)-1\n  \n\n"
  Title = "Furthest Building You Can Reach"
  Url = "/submissions/detail/1177761223/"
  LangName = "Python3"
  Timestamp = 1708171432
  Status = 10
  Runtime = "457 ms"
  IsPending = "Not Pending"
  Memory = "31 MB"
  CompareResult = "111111111111111111111111111111111111111111111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
