// Command update generates the root module's include list from its owning files.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path"
	"path/filepath"
	"sort"
	"strings"

	"github.com/bazelbuild/rules_go/go/runfiles"
)

const header = `# Generated by //tools/bazel_module:update. Do not edit.
module(
    name = "com_alwaldend_src",
    version = "0.0.0",
    bazel_compatibility = [">=8.5.1"],
)
`

func main() {
	git := flag.String("git", "", "Git executable runfile")
	check := flag.Bool("check", false, "check without writing")
	flag.Parse()
	if err := update(os.Getenv("BUILD_WORKSPACE_DIRECTORY"), *git, *check); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func update(root, git string, check bool) error {
	if root == "" {
		return fmt.Errorf("run with bazel run //tools/bazel_module:update")
	}
	gitPath, err := runfiles.Rlocation(git)
	if err != nil {
		return err
	}
	cmd := exec.Command(gitPath, "--git-dir", filepath.Join(root, ".git"), "-C", root, "ls-files", "-z", "--cached", "--others", "--exclude-standard")
	output, err := cmd.Output()
	if err != nil {
		return fmt.Errorf("discover module files: %w", err)
	}
	var files []string
	for _, name := range strings.Split(string(output), "\x00") {
		if name == "" {
			continue
		}
		info, err := os.Lstat(filepath.Join(root, filepath.FromSlash(name)))
		if os.IsNotExist(err) {
			continue // Git still lists unstaged deletions.
		}
		if err != nil {
			return err
		}
		if info.Mode().IsRegular() {
			files = append(files, name)
		}
	}
	ignored, err := os.ReadFile(filepath.Join(root, ".bazelignore"))
	if err != nil && !os.IsNotExist(err) {
		return err
	}
	want := generate(files, string(ignored))
	filename := filepath.Join(root, "MODULE.bazel")
	got, err := os.ReadFile(filename)
	if err != nil {
		return err
	}
	if bytes.Equal(got, want) {
		return nil
	}
	if check {
		return fmt.Errorf("MODULE.bazel is stale; run bazel run //tools/bazel_module:update")
	}
	return os.WriteFile(filename, want, 0o644)
}

func generate(files []string, bazelignore string) []byte {
	var boundaries []string
	for _, file := range files {
		switch path.Base(file) {
		case "MODULE.bazel", "WORKSPACE", "WORKSPACE.bazel":
			if dir := path.Dir(file); dir != "." {
				boundaries = append(boundaries, dir)
			}
		}
	}
	for _, line := range strings.Split(bazelignore, "\n") {
		line = strings.TrimSpace(strings.SplitN(line, "#", 2)[0])
		if line != "" {
			boundaries = append(boundaries, strings.TrimSuffix(line, "/"))
		}
	}
	owners := make(map[string]bool)
	for _, file := range files {
		if path.Base(file) != "include.MODULE.bazel" {
			continue
		}
		excluded := false
		for _, boundary := range boundaries {
			if strings.HasPrefix(file, boundary+"/") {
				excluded = true
				break
			}
		}
		if !excluded {
			owners[path.Dir(file)] = true
		}
	}
	var sorted []string
	for owner := range owners {
		sorted = append(sorted, owner)
	}
	// Preserve the existing dependency/toolchain precedence between trees.
	group := func(owner string) int {
		switch strings.SplitN(owner, "/", 2)[0] {
		case "third_party":
			return 0
		case "tools":
			return 1
		case "projects":
			return 2
		default:
			return 3
		}
	}
	sort.Slice(sorted, func(i, j int) bool {
		if a, b := group(sorted[i]), group(sorted[j]); a != b {
			return a < b
		}
		return sorted[i] < sorted[j]
	})
	var result bytes.Buffer
	result.WriteString(header)
	for _, owner := range sorted {
		if owner == "." {
			owner = ""
		}
		fmt.Fprintf(&result, "\ninclude(\"//%s:include.MODULE.bazel\")", owner)
	}
	result.WriteByte('\n')
	return result.Bytes()
}
