load("//tools/ansible/main/bzl:al_ansible_role.bzl", "al_ansible_role")
load("//tools/docs:defs.bzl", "docs_filegroup")

al_ansible_role(
    name = "role",
    srcs = glob(["**"]),
    visibility = ["//:__subpackages__"],
)

docs_filegroup(
    name = "docs",
    srcs = glob(["*.md"]),
    visibility = ["//projects/ansible_collection/roles:__pkg__"],
    deps = [
        ":role.docs",
    ],
)
