[[Submissions]]
  Id = 995847615
  StatusDisplay = "Accepted"
  Lang = "python3"
  QuestionId = 104
  TitleSlug = "maximum-depth-of-binary-tree"
  Code = "# Definition for a binary tree node.\n# class TreeNode:\n#     def __init__(self, val=0, left=None, right=None):\n#         self.val = val\n#         self.left = left\n#         self.right = right\nclass Solution:\n    def maxDepth(self, root: Optional[TreeNode], count: int = 0) -> int:\n        if not root:\n            return 0\n        \n        if not root.left and not root.right:\n            return count + 1\n\n        return max(self.maxDepth(root.left, count + 1), self.maxDepth(root.right, count + 1))\n        "
  Title = "Maximum Depth of Binary Tree"
  Url = "/submissions/detail/995847615/"
  LangName = "Python3"
  Timestamp = 1689509076
  Status = 10
  Runtime = "58 ms"
  IsPending = "Not Pending"
  Memory = "18.8 MB"
  CompareResult = "111111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
