note_id = 1520716967606
guid = "F8JerP`sGZ"
note_type_id = 1496733135171
note_type = "chinese"
tags = ["B1", "Conjunctions", "Parts_of_Speech"]

[[cards]]
id = 1520716973470
ordinal = 0

[fields]
article-title = 'Using "lai" to connect two verb phrases'
english = "It's easier to use this application to study Chinese characters."
example-sentence = ''
example-type = ''
grammar-construct = '通过 / 用 + Agent + 来 + [Verb Phrase]'
hanzi = '用这个app来学汉字更容易。'
notes = ''
pinyin = 'Yòng zhège app lái xué Hànzì gèng róngyì.'
source = 'https://resources.allsetlearning.com/chinese/grammar/ASGBZ578'
