note_id = 1520716967610
guid = "yV7v^I%tPp"
note_type_id = 1496733135171
note_type = "chinese"
tags = ["B1", "Conjunctions", "Parts_of_Speech"]

[[cards]]
id = 1520716973474
ordinal = 0

[fields]
article-title = 'Using "lai" to connect two verb phrases'
english = 'Through what platform did you promote the new product?'
example-sentence = ''
example-type = ''
grammar-construct = '通过 / 用 + Agent + 来 + [Verb Phrase]'
hanzi = '你们是通过什么平台来推广新产品的？'
notes = ''
pinyin = 'Nǐmen shì tōngguò shénme píngtái lái tuīguǎng xīn chǎnpǐn de?'
source = 'https://resources.allsetlearning.com/chinese/grammar/ASGBZ578'
