[[Submissions]]
  Id = 1001849755
  StatusDisplay = "Accepted"
  Lang = "python3"
  QuestionId = 930
  TitleSlug = "all-possible-full-binary-trees"
  Code = "# Definition for a binary tree node.\n# class TreeNode:\n#     def __init__(self, val=0, left=None, right=None):\n#         self.val = val\n#         self.left = left\n#         self.right = right\nclass Solution:\n    def allPossibleFBT(self, n: int) -> List[TreeNode]:\n        if n % 2 == 0:\n            return []\n        if n == 1:\n            return [TreeNode()]\n\n        res = []\n        for i in range(1, n, 2):\n            left = self.allPossibleFBT(i)\n            right = self.allPossibleFBT(n - i - 1)\n\n            for l in left:\n                for r in right:\n                    root = TreeNode(0, l, r)\n                    res.append(root)\n\n        return res"
  Title = "All Possible Full Binary Trees"
  Url = "/submissions/detail/1001849755/"
  LangName = "Python3"
  Timestamp = 1690120234
  Status = 10
  Runtime = "213 ms"
  IsPending = "Not Pending"
  Memory = "26 MB"
  CompareResult = "11111111111111111111"
  HasNotes = false
  FlagType = 1
