load("@hedron_compile_commands//:refresh_compile_commands.bzl", "refresh_compile_commands")
load("@rules_docs//docs:defs.bzl", "docs_filegroup")

refresh_compile_commands(
    name = "refresh_compile_commands",
    targets = {
        "//projects/sri/main/c/...": "",
    },
    visibility = ["//:__pkg__"],
)

docs_filegroup(
    name = "docs",
    srcs = glob(["*.md"]),
    visibility = ["//tools:__pkg__"],
)
