[[Submissions]]
  Id = 1171379827
  StatusDisplay = "Accepted"
  Lang = "python3"
  QuestionId = 647
  TitleSlug = "palindromic-substrings"
  Code = "class Solution:\n    def countSubstrings(self, s: str) -> int:\n        n = len(s)\n        palindrome = [[False] * n for _ in range(n)]\n        ans = 0\n\n        for i in range(n):\n            palindrome[i][i] = True\n            ans += 1\n\n        for i in range(n - 1):\n            if s[i] == s[i + 1]:\n                palindrome[i][i + 1] = True\n                ans += 1\n\n        for length in range(3, n + 1):\n            for i in range(n - length + 1):\n                if s[i] == s[i + length - 1] and palindrome[i + 1][i + length - 2]:\n                    palindrome[i][i + length - 1] = True\n                    ans += 1\n\n        return ans"
  Title = "Palindromic Substrings"
  Url = "/submissions/detail/1171379827/"
  LangName = "Python3"
  Timestamp = 1707567174
  Status = 10
  Runtime = "159 ms"
  IsPending = "Not Pending"
  Memory = "24.4 MB"
  CompareResult = "1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
