load("@rules_docs//docs:defs.bzl", "docs_filegroup")
load("//projects/al/rules/al:al_binary.bzl", "al_binary_run", "al_binary_run_map")
load("//projects/al/rules/al:al_config.bzl", "al_config")
load("//tools/vault:defs.bzl", "vault_binary_map")

_OPENCODE = "$(rootpath //tools/opencode)"

al_binary_run(
    name = "gen_client_cert",
    args = [
        "$(rootpath //tools/vault/gen_client_cert)",
        "--vault",
        "$(rootpath //tools/vault)",
        "--user",
        "simeonwarren",
    ],
    configs = ["//users/simeonwarren:al"],
    data = [
        "//tools/vault",
        "//tools/vault/gen_client_cert",
        "//tools/vault/injector",
    ],
    run_args = [
        "--plugin_label",
        "vault_env=default_no_auth",
    ],
)

filegroup(
    name = "dnsconfig",
    srcs = ["dnsconfig.json"],
    visibility = [
        "//infra/dns:__pkg__",
        "//users:__pkg__",
        "//users/simeonwarren:__subpackages__",
    ],
)

docs_filegroup(
    name = "docs",
    srcs = glob(["*.md"]),
    visibility = ["//users:__pkg__"],
    deps = subpackages(
        include = ["*"],
        allow_empty = True,
    ),
)

vault_binary_map(
    name = "vault",
    configs = [":al"],
)

al_binary_run_map(
    name = "opencode",
    args = {
        "": [
            _OPENCODE,
            "$(GIT_ROOT)",
        ],
        "serve": [
            _OPENCODE,
            "serve",
            "$(GIT_ROOT)",
        ],
        "direct": [
            _OPENCODE,
        ],
        "remote": [
            _OPENCODE,
            "attach",
            "https://opencode.simeonwarren.users.alwaldend.com",
        ],
    },
    configs = [":al"],
    data = [
        "//tools/opencode",
        "//tools/vault/injector",
    ],
    run_args = [
        "--plugin_label",
        "opencode",
    ],
    toolchains = ["//tools/git/main/bzl:toolchain_resolved"],
)

al_config(
    name = "al",
    srcs = ["al.lua"],
    visibility = ["//users/simeonwarren:__subpackages__"],
    deps = ["//infra:al"],
)
