note_id = 1692896292953
guid = "FN&kdmt5gE"
note_type_id = 1496733135171
note_type = "chinese"
tags = []

[[cards]]
id = 1692896292953
ordinal = 0

[fields]
article-title = ''
english = 'Using Spring and Autumn Cicada to be reborn, I went back to 500 years ago!'
example-sentence = ''
example-type = ''
grammar-construct = ''
hanzi = '利用春秋蝉重生了,回到了500年前！'
notes = ''
pinyin = ''
source = ''
