note_id = 1692894692735
guid = "iCd4F;7D>k"
note_type_id = 1496733135171
note_type = "chinese"
tags = []

[[cards]]
id = 1692894692736
ordinal = 0

[fields]
article-title = ''
english = 'The group of heroes rushed over, just at this moment, with a bang, Fang Yuan blew himself up brazenly.'
example-sentence = ''
example-type = ''
grammar-construct = ''
hanzi = '群雄逼迫而来,恰在这时,轰的一声,方源悍然自爆。'
notes = ''
pinyin = ''
source = ''
