note_id = 1692894315457
guid = "mBa#/WVBJo"
note_type_id = 1496733135171
note_type = "chinese"
tags = []

[[cards]]
id = 1692894315457
ordinal = 0

[fields]
article-title = ''
english = 'It really is like blue silk in the morning and snow in the evening, right and wrong, success or failure, turning your head empty.'
example-sentence = ''
example-type = ''
grammar-construct = ''
hanzi = '当真是朝如青丝暮成雪,是非成败转头空。'
notes = ''
pinyin = ''
source = ''
