note_id = 1692895605124
guid = "Da+ghDWF;j"
note_type_id = 1496733135171
note_type = "chinese"
tags = []

[[cards]]
id = 1692895605124
ordinal = 0

[fields]
article-title = ''
english = "Well, it's precocious and has big ambitions."
example-sentence = ''
example-type = ''
grammar-construct = ''
hanzi = '嗯,这是有早智的,而且有大志向。'
notes = ''
pinyin = ''
source = ''
