note_id = 1692895191204
guid = "r=#df|3Iy6"
note_type_id = 1496733135171
note_type = "chinese"
tags = []

[[cards]]
id = 1692895191204
ordinal = 0

[fields]
article-title = ''
english = 'For a moment, the clan ancestral hall was filled with the soft sound of forehead hitting the floor.'
example-sentence = ''
example-type = ''
grammar-construct = ''
hanzi = '一时间,宗族祠堂中尽是额头碰撞地板的轻响。'
notes = ''
pinyin = ''
source = ''
