note_id = 1692894207696
guid = "m{Fa|C#azq"
note_type_id = 1496733135171
note_type = "chinese"
tags = []

[[cards]]
id = 1692894207697
ordinal = 0

[fields]
article-title = ''
english = 'Just like this tense confrontation for three hours, the setting sun set in the west, and the afterglow of the setting sun ignited the sunset glow on the mountain side, and it was gorgeous like fire for a while.'
example-sentence = ''
example-type = ''
grammar-construct = ''
hanzi = '就这样紧张地对峙了三个时辰,夕阳西下,落日的余晖将山边的晚霞点燃,一时间绚烂如火。'
notes = ''
pinyin = ''
source = ''
