note_id = 1520716970526
guid = "lX9+&WN;iQ"
note_type_id = 1496733135171
note_type = "chinese"
tags = ["B2", "Grammatical_Structures", "SentencePatterns"]

[[cards]]
id = 1520716976390
ordinal = 0

[fields]
article-title = 'Expressing "the more... the more..." with "yue… yue…"'
english = 'The more she talks, the angrier I get.'
example-sentence = ''
example-type = ''
grammar-construct = 'Subj. 1 + 越 + Verb 1，Subj. 2 + 越 + Verb 2'
hanzi = '她越说，我越生气。'
notes = ''
pinyin = 'Tā yuè shuō,  wǒ yuè shēngqì.'
source = 'https://resources.allsetlearning.com/chinese/grammar/ASGB44F6'
