[[Submissions]]
  Id = 1276335480
  StatusDisplay = "Accepted"
  Lang = "python3"
  QuestionId = 2572
  TitleSlug = "append-characters-to-string-to-make-subsequence"
  Code = "class Solution:\n    def appendCharacters(self, s: str, t: str) -> int:\n        i, j = 0, 0  # Start both pointers at the beginning of s and t\n        \n        while i < len(s) and j < len(t):  # Continue until one of the strings is fully scanned\n            if s[i] == t[j]:  # If characters match\n                j += 1  # Move the pointer in t forward\n            i += 1  # Always move the pointer in s forward\n        \n        return len(t) - j  # The number of characters in t not matched in s\n               "
  Title = "Append Characters to String to Make Subsequence"
  Url = "/submissions/detail/1276335480/"
  LangName = "Python3"
  Timestamp = 1717418420
  Status = 10
  Runtime = "75 ms"
  IsPending = "Not Pending"
  Memory = "17.6 MB"
  CompareResult = "1111111111111111111111111111111111111111111111111111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
