note_id = 1520716970282
guid = "m=Qf3KNYD`"
note_type_id = 1496733135171
note_type = "chinese"
tags = ["B2", "Cause/EffectStatements", "Grammatical_Structures"]

[[cards]]
id = 1520716976146
ordinal = 0

[fields]
article-title = 'Expressing "due to…" with "youyu"'
english = 'Due to the rapid growth of population, social problems in big cities are getting more and more serious.'
example-sentence = ''
example-type = ''
grammar-construct = '由于 + Cause，Effect'
hanzi = '由于人口的快速增加，大城市的社会问题越来越严重。'
notes = ''
pinyin = ''
source = 'https://resources.allsetlearning.com/chinese/grammar/ASGL90MR'
