load("@rules_docs//docs:defs.bzl", "docs_filegroup")

docs_filegroup(
    name = "docs",
    srcs = glob(["*.md"]),
    visibility = ["//tools:__pkg__"],
    deps = subpackages(
        include = ["*"],
        allow_empty = True,
    ) + ["//tools/drawio/main/bzl:docs"],
)

alias(
    name = "drawio",
    actual = "//third_party/com_drawio_desktop_bin",
    visibility = ["//:__subpackages__"],
)
