load("@rules_docs//docs:defs.bzl", "docs_filegroup")
load("//tools/ansible/main/bzl:al_ansible_role.bzl", "al_ansible_role")

docs_filegroup(
    name = "docs",
    srcs = glob(["*.md"]),
    visibility = ["//projects/ansible_collection/roles:__pkg__"],
    deps = [
        ":role.docs",
    ],
)

al_ansible_role(
    name = "role",
    srcs = glob(["**"]) + [
        "//data/ssl/alwaldend.com:ica_servers",
        "//data/ssl/alwaldend.com:root_ca",
    ],
    renames = {
        "//data/ssl/alwaldend.com:root_ca": "files/pki_ca_root.crt",
        "//data/ssl/alwaldend.com:ica_servers": "files/pki_ca_servers.crt",
    },
    visibility = ["//:__subpackages__"],
)
