# gazelle:java_extension disabled

load("@rules_docs//docs:defs.bzl", "docs_filegroup")
load("//projects/al/rules/al:al_config.bzl", "al_config")
load("//tools/vault:defs.bzl", "vault_binary_map")

exports_files(
    ["maven_lock.json"],
    visibility = ["//projects/activitywatch_ingester_android:__subpackages__"],
)

filegroup(
    name = "manifest",
    srcs = ["AndroidManifest.xml"],
    visibility = [":__subpackages__"],
)

filegroup(
    name = "test_manifest",
    srcs = ["//projects/activitywatch_ingester_android/androidTest:manifest"],
    visibility = [":__subpackages__"],
)

filegroup(
    name = "proguard",
    srcs = ["proguard_rules.pro"],
    visibility = [":__subpackages__"],
)

filegroup(
    name = "dnsconfig",
    srcs = ["dnsconfig.json"],
    visibility = [
        "//infra:__pkg__",
        "//infra/dns:__pkg__",
        "//projects/activitywatch_ingester_android/tf:__pkg__",
        "//projects/alwaldend.com:__subpackages__",
    ],
)

filegroup(
    name = "fastlane_metadata",
    srcs = glob(
        ["fastlane/metadata/android/**/*.txt"],
    ),
    visibility = ["//visibility:public"],
)

docs_filegroup(
    name = "docs",
    srcs = glob(["*.md"]),
    visibility = [
        "//projects:__pkg__",
        "//projects/activitywatch_ingester_android/landing:__pkg__",
    ],
    deps = [
        "//projects/activitywatch_ingester_android/releases:docs",
        "//projects/activitywatch_ingester_android/tf:docs",
    ],
)

al_config(
    name = "al",
    srcs = ["al.lua"],
    visibility = ["//projects/activitywatch_ingester_android/tf:__pkg__"],
    deps = ["//infra:al"],
)

vault_binary_map(
    name = "vault",
    configs = [":al"],
)
