note_id = 1520716970382
guid = "rMI?H*L=*^"
note_type_id = 1496733135171
note_type = "chinese"
tags = ["B2", "Complements", "Grammatical_Structures"]

[[cards]]
id = 1520716976246
ordinal = 0

[fields]
article-title = 'Advanced result complements'
english = 'Can you tell how old I am?'
example-sentence = ''
example-type = ''
grammar-construct = ''
hanzi = '菜里面有味精，我能吃出来。'
notes = ''
pinyin = ''
source = 'https://resources.allsetlearning.com/chinese/grammar/ASG4OM4T'
