note_id = 1520716970360
guid = "Got+bq<EFz"
note_type_id = 1496733135171
note_type = "chinese"
tags = ["B2", "Complements", "Grammatical_Structures"]

[[cards]]
id = 1520716976224
ordinal = 0

[fields]
article-title = 'Advanced result complements'
english = "Stop! You can't go!"
example-sentence = ''
example-type = ''
grammar-construct = ''
hanzi = '站住！你不能走！'
notes = ''
pinyin = ''
source = 'https://resources.allsetlearning.com/chinese/grammar/ASG4OM4T'
