load("@rules_docs//docs:defs.bzl", "docs_filegroup")

docs_filegroup(
    name = "docs",
    srcs = glob(["*.md"]),
    prefix = "content",
    visibility = ["//projects/alwaldend.com:__pkg__"],
    deps = [
        "//projects/alwaldend.com/content/docs",
        "//projects/alwaldend.com/content/projects:docs",
    ],
)
