[[Submissions]]
  Id = 1228441521
  StatusDisplay = "Accepted"
  Lang = "golang"
  QuestionId = 987
  TitleSlug = "reveal-cards-in-increasing-order"
  Code = "func deckRevealedIncreasing(deck []int) []int {\n\tn := len(deck)\n\tsort.Ints(deck)\n\n\tres := make([]int, n)\n\tqueue := make([]int, n)\n\n\tfor i := range queue {\n\t\tqueue[i] = i\n\t}\n\n\tfor _, card := range deck {\n\t\tidx := queue[0]\n\t\tqueue = queue[1:]\n\t\tres[idx] = card\n\n\t\tif len(queue) > 0 {\n\t\t\tqueue = append(queue, queue[0])\n\t\t\tqueue = queue[1:]\n\t\t}\n\t}\n\n\treturn res\n}"
  Title = "Reveal Cards In Increasing Order"
  Url = "/submissions/detail/1228441521/"
  LangName = "Go"
  Timestamp = 1712744718
  Status = 10
  Runtime = "3 ms"
  IsPending = "Not Pending"
  Memory = "3.4 MB"
  CompareResult = "111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
