[[Submissions]]
  Id = 1002517384
  StatusDisplay = "Accepted"
  Lang = "python3"
  QuestionId = 414
  TitleSlug = "third-maximum-number"
  Code = "class Solution:\n    def thirdMax(self, nums: List[int]) -> int:\n        nums.sort(reverse=True)\n        number_max = nums[0]\n        count = 1\n        for i in range(1, len(nums)):\n            number = nums[i]\n            if number == nums[i-1]:\n                continue\n            \n            count += 1\n\n            if count == 3:\n                return number \n\n            if number > number_max:\n                number_max = number\n        \n        return number_max"
  Title = "Third Maximum Number"
  Url = "/submissions/detail/1002517384/"
  LangName = "Python3"
  Timestamp = 1690193011
  Status = 10
  Runtime = "73 ms"
  IsPending = "Not Pending"
  Memory = "17.3 MB"
  CompareResult = "1111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
