[[Submissions]]
  Id = 1051798721
  StatusDisplay = "Accepted"
  Lang = "python3"
  QuestionId = 676
  TitleSlug = "implement-magic-dictionary"
  Code = "class MagicDictionary:\n\n    def __init__(self):\n        self.dict = []\n\n    def buildDict(self, dictionary: List[str]) -> None:\n        self.dict = dictionary\n\n    def search(self, searchWord: str) -> bool:\n        target_length = len(searchWord)\n        for word in self.dict:\n            if len(word) != target_length or word == searchWord:\n                continue\n            found_diff = False\n            for i in range(target_length):\n                if word[i] == searchWord[i]:\n                    continue\n                if found_diff:\n                    break\n\n                found_diff = True\n            else:\n                return True\n\n        return False\n\n# Your MagicDictionary object will be instantiated and called as such:\n# obj = MagicDictionary()\n# obj.buildDict(dictionary)\n# param_2 = obj.search(searchWord)"
  Title = "Implement Magic Dictionary"
  Url = "/submissions/detail/1051798721/"
  LangName = "Python3"
  Timestamp = 1694957225
  Status = 10
  Runtime = "66 ms"
  IsPending = "Not Pending"
  Memory = "16.5 MB"
  CompareResult = "11111111111111111111111111111111111111111111111111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
