load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "admission",
    srcs = ["admission.go"],
    importpath = "git.alwaldend.com/alwaldend/src/tools/agents/admission",
    visibility = ["//:__subpackages__"],
    deps = ["//tools/agents/api/v1alpha1"],
)

go_test(
    name = "admission_test",
    size = "small",
    srcs = ["admission_test.go"],
    embed = [":admission"],
    deps = ["//tools/agents/api/v1alpha1"],
)
