note_id = 1520716967199
guid = "P$5A4y86:V"
note_type_id = 1496733135171
note_type = "chinese"
tags = ["Adverbs", "B1", "Parts_of_Speech"]

[[cards]]
id = 1520716973063
ordinal = 0

[fields]
article-title = 'Expressing "had better" with "zuihao"'
english = "It is raining so heavily. You'd better not leave the house."
example-sentence = ''
example-type = ''
grammar-construct = 'Subj. + 最好 + 别 / 不要 + [Verb Phrase]'
hanzi = '雨这么大，最好别出门。'
notes = ''
pinyin = ''
source = 'https://resources.allsetlearning.com/chinese/grammar/ASG35CD7'
