[[Submissions]]
  Id = 1046482817
  StatusDisplay = "Accepted"
  Lang = "python3"
  QuestionId = 1407
  TitleSlug = "group-the-people-given-the-group-size-they-belong-to"
  Code = "class Solution:\n    def groupThePeople(self, groupSizes: List[int]) -> List[List[int]]:\n        answer = []\n        cur_groups = defaultdict(list)\n        \n        for i in range(len(groupSizes)):\n            size = groupSizes[i]\n            group = cur_groups[size]\n            group.append(i)\n            if len(group) == size:\n                answer.append(group)\n                del cur_groups[size]\n        \n        return answer"
  Title = "Group the People Given the Group Size They Belong To"
  Url = "/submissions/detail/1046482817/"
  LangName = "Python3"
  Timestamp = 1694434015
  Status = 10
  Runtime = "69 ms"
  IsPending = "Not Pending"
  Memory = "16.3 MB"
  CompareResult = "1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
