[Unit]
Description=Opencode server
After=network.target
Wants=network.target

[Service]
EnvironmentFile={{ opencode_env_path }}
Type=simple
User={{ opencode_user }}
Group={{ opencode_user }}
WorkingDirectory={{ opencode_work_dir }}
ExecStart={{ opencode_bin_path }} serve --print-logs --log-level WARN --port "{{ opencode_port }}" --hostname 127.0.0.1 --cors "{{ opencode_domain }}" --cors "{{ inventory_hostname }}"
ExecReload=/bin/kill --signal HUP $MAINPID
Restart=on-failure
RestartSec=5s

[Install]
WantedBy=multi-user.target
