note_id = 1520716969910
guid = "EUkj~hz-,-"
note_type_id = 1496733135171
note_type = "chinese"
tags = ["B2", "Particles", "Parts_of_Speech"]

[[cards]]
id = 1520716975774
ordinal = 0

[fields]
article-title = 'Taiwanese "you"'
english = 'I have studied this word.'
example-sentence = ''
example-type = ''
grammar-construct = 'Subj. + 有 + Verb + 过 + Obj.'
hanzi = '我有学过这个词。'
notes = ''
pinyin = ''
source = 'https://resources.allsetlearning.com/chinese/grammar/ASGY2D79'
