note_id = 1520716969904
guid = "qaN%es%GN%"
note_type_id = 1496733135171
note_type = "chinese"
tags = ["B2", "Particles", "Parts_of_Speech"]

[[cards]]
id = 1520716975768
ordinal = 0

[fields]
article-title = 'Taiwanese "you"'
english = 'He has eaten steamed dumplings.'
example-sentence = ''
example-type = ''
grammar-construct = 'Subj. + 有 + Verb + 过 + Obj.'
hanzi = '他有吃过小笼包。'
notes = ''
pinyin = ''
source = 'https://resources.allsetlearning.com/chinese/grammar/ASGY2D79'
