note_id = 1520716966154
guid = "BePm%RHr@c"
note_type_id = 1496733135171
note_type = "chinese"
tags = ["A2", "Particles", "Parts_of_Speech"]

[[cards]]
id = 1520716972018
ordinal = 0

[fields]
article-title = 'Expressing "now" with "le"'
english = 'Class begins now!'
example-sentence = ''
example-type = ''
grammar-construct = '[New Situation] + 了'
hanzi = '上课了！'
notes = ''
pinyin = 'Shàngkè le!'
source = 'https://resources.allsetlearning.com/chinese/grammar/ASGE5Q4J'
