[[Submissions]]
  Id = 1087472492
  StatusDisplay = "Accepted"
  Lang = "golang"
  QuestionId = 637
  TitleSlug = "average-of-levels-in-binary-tree"
  Code = "/**\n * Definition for a binary tree node.\n * type TreeNode struct {\n *     Val int\n *     Left *TreeNode\n *     Right *TreeNode\n * }\n */\nfunc averageOfLevels(root *TreeNode) []float64 {\n    if root == nil {\n        return []float64{}\n    }\n    queue, answer := []*TreeNode{root}, []float64{}\n\n    for length := len(queue); length != 0; length = len(queue) {\n        av := 0\n        for i := 0; i < length; i++ {\n            node := queue[0]\n            queue = queue[1:]\n            av += node.Val\n            if left := node.Left; left != nil {\n                queue = append(queue, left)\n            }\n            if right := node.Right; right != nil {\n                queue = append(queue, right)\n            }\n        }\n        answer = append(answer, float64(av) / float64(length))\n    }\n\n    return answer\n}"
  Title = "Average of Levels in Binary Tree"
  Url = "/submissions/detail/1087472492/"
  LangName = "Go"
  Timestamp = 1698661999
  Status = 10
  Runtime = "3 ms"
  IsPending = "Not Pending"
  Memory = "6.2 MB"
  CompareResult = "111111111111111111111111111111111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
