load("@rules_docs//docs:defs.bzl", "docs_filegroup")
load("@tools_com_github_bazelbuild_buildtools//buildifier:def.bzl", "buildifier", "buildifier_test")
# gazelle:resolve go golang.org/x/tools/go/cfg @tools_com_github_bazelbuild_buildtools_org_golang_x_tools//go/cfg:go_default_library
# gazelle:resolve go github.com/bazelbuild/buildtools/buildifier/config @tools_com_github_bazelbuild_buildtools//buildifier/config:go_default_library

alias(
    name = "buildifier",
    actual = "@tools_com_github_bazelbuild_buildtools//buildifier",
    visibility = ["//:__subpackages__"],
)

buildifier(
    name = "workspace",
    exclude_patterns = ["./out/*"],
    visibility = ["//:__subpackages__"],
)

buildifier_test(
    name = "workspace_test",
    size = "small",
    exclude_patterns = ["./out/*"],
    no_sandbox = True,
    visibility = ["//:__pkg__"],
    workspace = "//:BUILD.bazel",
)

docs_filegroup(
    name = "docs",
    srcs = glob(["*.md"]),
    visibility = ["//tools:__pkg__"],
)
