load("@rules_docs//docs:defs.bzl", "docs_filegroup")
load("@rules_go//go:def.bzl", "go_binary", "go_library")

docs_filegroup(
    name = "docs",
    srcs = glob(["*.md"]),
    visibility = ["//tools:__pkg__"],
)

go_binary(
    name = "fdroid_wrapper",
    embed = [":fdroid_lib"],
    visibility = ["//visibility:public"],
)

go_library(
    name = "fdroid_lib",
    srcs = ["main.go"],
    importpath = "git.alwaldend.com/alwaldend/src/tools/fdroid",
    visibility = ["//visibility:private"],
)
