load(
    "@rules_pkg//pkg:mappings.bzl",
    "pkg_filegroup",
    "pkg_files",
    "strip_prefix",
)
load("//projects/al/rules/al:al_binary.bzl", "al_binary_run")
load("//tools/ansible/main/bzl:al_ansible_binary.bzl", "al_ansible_binary")

al_binary_run(
    name = "ansible",
    args = ["$(rootpath :ansible_bin)"],
    configs = ["//infra/openstack:al"],
    data = [
        ":ansible_bin",
        "//tools/vault/injector",
    ],
    run_args = [
        "--plugin_label",
        "vault_env=default_default",
        "--plugin_label",
        "ansible",
    ],
)

al_ansible_binary(
    name = "ansible_bin",
    arguments = [
        "--inventory",
        "inventory.yaml",
        "playbook.yaml",
    ],
    data = [
        ":srcs",
        "//infra:ansible_cfg",
        "//projects/ansible_collection:collections",
    ],
    process_name = "ansible_playbook",
)

filegroup(
    name = "inventory",
    srcs = ["inventory.yaml"],
    visibility = ["//infra/openstack:__subpackages__"],
)

filegroup(
    name = "group_vars",
    srcs = glob(["group_vars/*.yaml"]),
    visibility = ["//infra/openstack:__subpackages__"],
)

filegroup(
    name = "host_vars",
    srcs = glob(["host_vars/*.yaml"]),
    visibility = ["//infra/openstack:__subpackages__"],
)

pkg_filegroup(
    name = "srcs",
    srcs = [":srcs_files"],
)

pkg_files(
    name = "srcs_files",
    srcs = [
        "inventory.yaml",
        "network.sh",
        "playbook.yaml",
        "storage_validate.sh",
    ] + glob([
        "group_vars/*.yaml",
        "host_vars/*.yaml",
    ]),
    strip_prefix = strip_prefix.from_pkg(),
)
