load("@rules_pkg//pkg:mappings.bzl", "pkg_filegroup", "pkg_files", "strip_prefix")
load("@rules_python//python:defs.bzl", "py_test")
load("//projects/al/rules/al:al_binary.bzl", "al_binary_run_map")
load("//tools/ansible/main/bzl:al_ansible_binary.bzl", "al_ansible_binary")
load("//tools/docs:defs.bzl", "docs_filegroup")

_ANSIBLE_ARGS = [
    "$(rootpath :ansible_bin)",
    "--inventory",
    "inventory.yaml",
    "playbook_deploy.yaml",
]

al_binary_run_map(
    name = "ansible",
    args = {
        "": _ANSIBLE_ARGS + [
            "--extra-vars",
            "openstack_action=deploy",
        ],
        "deploy": _ANSIBLE_ARGS + [
            "--extra-vars",
            "openstack_action=deploy",
        ],
        "post_deploy": _ANSIBLE_ARGS + [
            "--extra-vars",
            "openstack_action=post-deploy",
        ],
        "prechecks": _ANSIBLE_ARGS + [
            "--extra-vars",
            "openstack_action=prechecks",
        ],
        "reconfigure": _ANSIBLE_ARGS + [
            "--extra-vars",
            "openstack_action=reconfigure",
        ],
    },
    configs = ["//infra/openstack:al"],
    data = [
        ":ansible_bin",
        "//infra/openstack:kolla_passwords_template",
        "//tools/vault/injector",
    ],
    run_args = [
        "--plugin_label",
        "vault_env=default_default",
        "--plugin_label",
        "ansible",
    ],
)

al_ansible_binary(
    name = "ansible_bin",
    data = [
        ":srcs",
        "//infra:ansible_cfg",
        "//projects/ansible_collection:collections",
    ],
    process_name = "ansible_playbook",
)

pkg_filegroup(
    name = "srcs",
    srcs = [":srcs_files"],
)

pkg_files(
    name = "srcs_files",
    srcs = ["inventory.yaml"] + glob([
        "group_vars/**/*.yaml",
        "playbook_*.yaml",
        "roles/**",
    ]),
    strip_prefix = strip_prefix.from_pkg(),
)

py_test(
    name = "render_inventory_test",
    srcs = [
        "roles/openstack_kolla/files/render_inventory.py",
        "roles/openstack_kolla/files/render_inventory_test.py",
    ],
    main = "roles/openstack_kolla/files/render_inventory_test.py",
)

docs_filegroup(
    name = "docs",
    srcs = glob(["*.md"]),
    visibility = ["//infra/openstack:__pkg__"],
)
