services:
  hiddify:
    image: "${HIDDIFY_MANAGER_IMAGE}" 
    ports:
      - 443:443
      - 80:80
      - "11000-60000"
    privileged: true
    cap_add:
      - NET_ADMIN
    volumes:
       - ./docker-data/:/hiddify-data/
    environment:
      REDIS_URI_MAIN: "redis://:${HIDDIFY_MANAGER_REDIS_PASSWORD}@redis:6379/0"
      REDIS_URI_SSH: "redis://:${HIDDIFY_MANAGER_REDIS_PASSWORD}@redis:6379/1"
      SQLALCHEMY_DATABASE_URI: "mysql+mysqldb://hiddifypanel:${HIDDIFY_MANAGER_MYSQL_PASSWORD}@mariadb/hiddifypanel?charset=utf8mb4"
    depends_on: 
      - mariadb
      - redis
  mariadb:
    image: "${HIDDIFY_MANAGER_MARIADB_IMAGE}" 
    container_name: mariadb_container
    restart: always
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: hiddifypanel
      MYSQL_USER: hiddifypanel
      MYSQL_PASSWORD: "${HIDDIFY_MANAGER_MARIADB_PASSWORD}"
    volumes:
      - ./docker-data/mariadb_data:/var/lib/mysql
  redis:
    image: "${HIDDIFY_MANAGER_REDIS_IMAGE}" 
    container_name: redis_container
    restart: always
    command: ["redis-server", "--requirepass", "REDIS_STRONG_PASS"]
    volumes:
      - ./docker-data/redis_data:/data
    
