load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "model",
    srcs = [
        "collection.go",
        "deck.go",
        "note.go",
        "state.go",
    ],
    importpath = "git.alwaldend.com/alwaldend/src/projects/anki_as_code/internal/model",
    visibility = ["//projects/anki_as_code/internal:__subpackages__"],
    deps = [
        "//projects/anki_as_code/api/collection",
        "//third_party/com_github_ankitects_anki:notetypes",
    ],
)
