load("@bazel_skylib//rules:build_test.bzl", "build_test")
load("@rules_docs//docs:defs.bzl", "docs_filegroup")

alias(
    name = "hugo_worker",
    actual = "//cmd/hugo_worker",
    visibility = ["//visibility:public"],
)

build_test(
    name = "build_test",
    targets = [
        "//pkg/bzl:al_hugo_archives",
        "//pkg/bzl:al_hugo_binary",
        "//pkg/bzl:al_hugo_extension",
        "//pkg/bzl:al_hugo_module",
        "//pkg/bzl:al_hugo_module_info",
        "//pkg/bzl:al_hugo_run_binary",
        "//pkg/bzl:al_hugo_site",
        "//pkg/bzl:al_hugo_site_info",
        "//pkg/bzl:al_hugo_theme",
        "//pkg/bzl:al_hugo_theme_info",
        "//pkg/bzl:al_hugo_toolchain",
        "//pkg/bzl:al_hugo_worker",
        "//pkg/bzl:toolchain_type",
        "//tests:hugo_site_action_test",
        "//tests/toolchain:toolchain_impl",
    ],
)

docs_filegroup(
    name = "docs",
    srcs = glob(["*.md"]),
    prefix = "content/docs/projects/rules_hugo",
    visibility = ["//visibility:public"],
    deps = subpackages(
        include = ["**"],
        allow_empty = True,
        exclude = [
            "bazel-*",
            "tests/**",
        ],
    ),
)

filegroup(
    name = "dnsconfig",
    srcs = ["dnsconfig.json"],
    visibility = ["//visibility:public"],
)
