[[Submissions]]
  Id = 1091198577
  StatusDisplay = "Accepted"
  Lang = "golang"
  QuestionId = 57
  TitleSlug = "insert-interval"
  Code = "func insert(intervals [][]int, new []int) [][]int {\n    n := len(intervals)\n    i := sort.Search(n, func(i int) bool { return intervals[i][0] > new[0] })\n    j := sort.Search(n, func(j int) bool { return intervals[j][1] > new[1] })\n    if i >= 1 && new[0] <= intervals[i-1][1] {\n        new[0] = intervals[i-1][0]\n        i--\n    }\n    if j < n && new[1] >= intervals[j][0] {\n        new[1] = intervals[j][1]\n        j++\n    }\n    return append(intervals[:i], append([][]int{new}, intervals[j:]...)...)\n}"
  Title = "Insert Interval"
  Url = "/submissions/detail/1091198577/"
  LangName = "Go"
  Timestamp = 1699093410
  Status = 10
  Runtime = "7 ms"
  IsPending = "Not Pending"
  Memory = "4.3 MB"
  CompareResult = "111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
