[[Submissions]]
  Id = 1206182999
  StatusDisplay = "Accepted"
  Lang = "golang"
  QuestionId = 57
  TitleSlug = "insert-interval"
  Code = "func insert(intervals [][]int, newInterval []int) [][]int {\n\tvar result [][]int\n\n    // Iterate through intervals and add non-overlapping intervals before newInterval\n\ti := 0\n\tfor i < len(intervals) && intervals[i][1] < newInterval[0] {\n\t\tresult = append(result, intervals[i])\n\t\ti++\n\t}\n\n    // Merge overlapping intervals\n\tfor i < len(intervals) && intervals[i][0] <= newInterval[1] {\n\t\tnewInterval[0] = int(math.Min(float64(newInterval[0]), float64(intervals[i][0])))\n\t\tnewInterval[1] = int(math.Max(float64(newInterval[1]), float64(intervals[i][1])))\n\t\ti++\n\t}\n\n    // Add merged newInterval\n\tresult = append(result, newInterval)\n\n    // Add non-overlapping intervals after newInterval\n\tfor i < len(intervals) {\n\t\tresult = append(result, intervals[i])\n\t\ti++\n\t}\n\n\treturn result\n}\n"
  Title = "Insert Interval"
  Url = "/submissions/detail/1206182999/"
  LangName = "Go"
  Timestamp = 1710667926
  Status = 10
  Runtime = "7 ms"
  IsPending = "Not Pending"
  Memory = "4.4 MB"
  CompareResult = "111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
