title = "Misc"
theme = ["github.com/google/docsy"]
# baseURL = "https://alwaldend.com/misc"
enableRobotsTXT = true

[markup]
goldmark.renderer.unsafe = true

[security.exec]
allow = ['.*']
osEnv = ['.*']

[security.funcs]
getenv = ['.*']
