title = "Misc"
theme = ["github.com/google/docsy"]
# baseURL = "https://alwaldend.com/docs/"

contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
enableMissingTranslationPlaceholders = true
enableRobotsTXT = true
enableGitInfo = true

[params.ui]
sidebar_menu_foldable = true

[markup]
goldmark.renderer.unsafe = true

[security]
enableInlineShortcodes = true

# [security.exec]
# allow = ['.*']
# osEnv = ['.*']
#
# [security.funcs]
# getenv = ['.*']
