title = "Docs"
theme = ["github.com/google/docsy"]
baseURL = "http://127.0.0.1:1313/src"

enableRobotsTXT = true
enableGitInfo = true

[outputs]
section = ["html", "rss", "print"]
home = ["html"]
page = ["html"]

[params]
offlineSearch = true
github_project_repo = "https://github.com/alwaldend/src"
github_repo = "https://github.com/alwaldend/src"

[params.ui]
generated_tags = ["Generated"]
separate_page_tags = ["Bzl-Targets", "Changelog"]
showLightDarkModeMenu = true
sidebar_menu_compact = true
sidebar_menu_foldable = false

[params.drawio]
enable = true

[[params.links.developer]]
name = "Github"
url = "https://github.com/alwaldend/src"
icon = "fa-brands fa-github"
desc = "Github"

[markup.goldmark]
renderer.unsafe = true

[security]
enableInlineShortcodes = true

[[menus.main]]
name = "Docs"
weight = 100
identifier = "docs"
url = "/"

[[menus.main]]
name = "Tags"
identifier = "tags"
weight = 200
url = "/tags/"

# [security.exec]
# allow = ['.*']
# osEnv = ['.*']
#
# [security.funcs]
# getenv = ['.*']

[module.hugoVersion]
extended = true
min = "0.146.0"

[[module.imports]]
path = "github.com/google/docsy"
disable = false

[[module.mounts]]
source = "content"
target = "content"

[[module.mounts]]
source = "content/.github"
target = "content/github"
