title = "Docs"
theme = ["github.com/google/docsy"]
baseURL = "http://127.0.0.1:1313/src"

defaultContentLanguage = "en"
enableMissingTranslationPlaceholders = true
enableRobotsTXT = true
enableGitInfo = true

[outputs]
section = ["html", "rss", "print"]

[params]
offlineSearch = true
github_repo = "https://github.com/alwaldend/src"
github_project_repo = "https://github.com/alwaldend/src"

[params.ui]
sidebar_menu_foldable = true
showLightDarkModeMenu = true

[params.drawio]
enable = true

[[params.links.developer]]
name = "Github"
url = "https://github.com/alwaldend/src"
icon = "fa-brands fa-github"
desc = "Github"

[markup]
goldmark.renderer.unsafe = true

[security]
enableInlineShortcodes = true

[[languages.en.menus.main]]
name = "Docs"
weight = 100
identifier = "docs"
url = "/en/"

[[languages.en.menus.main]]
name = "Tags"
identifier = "tags"
weight = 200
url = "/tags/"

# [security.exec]
# allow = ['.*']
# osEnv = ['.*']
#
# [security.funcs]
# getenv = ['.*']

[module.hugoVersion]
extended = true
min = "0.146.0"

[[module.imports]]
path = "github.com/google/docsy"
disable = false
