---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: harbor
spec:
  interval: 10m0s
  url: https://helm.goharbor.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
spec:
  interval: 15m
  timeout: 5m
  targetNamespace: harbor
  chart:
    spec:
      chart: harbor
      # https://github.com/goharbor/harbor-helm/releases
      version: "1.19.1"
      sourceRef:
        kind: HelmRepository
        name: harbor
      interval: 10m
  releaseName: harbor
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
  upgrade:
    crds: CreateReplace
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
  test:
    enable: true
  driftDetection:
    mode: enabled
  values:
    # https://github.com/goharbor/harbor-helm#configuration
    # https://goharbor.io/docs/2.15.0/install-config/harbor-ha-helm/
    externalURL: https://harbor.alwaldend.com
    persistence:
      persistentVolumeClaim:
        registry:
          storageClass: local-path
        jobservice:
          storageClass: local-path
        database:
          storageClass: local-path
        redis:
          storageClass: local-path
        trivy:
          storageClass: local-path
    caBundleSecretName: alwaldend-ca
