id = 1778585061458
title = 'main::chinese::chinese-grammar-wiki-782551504::B1::Comparing "dui" and "duiyu"'

[notes]
path = 'notes'

[normal]
config_id = 1
extend_new = 0
extend_review = 0
description = ''
markdown_description = false
