load("@com_alwaldend_src_tools_trufflehog//:defs.bzl", "trufflehog_test")
load("@rules_docs//docs:defs.bzl", "docs_filegroup")
load("@rules_shell//shell:sh_test.bzl", "sh_test")

alias(
    name = "trufflehog",
    actual = "@com_alwaldend_src_tools_trufflehog//:trufflehog_binary",
    visibility = ["//:__subpackages__"],
)

trufflehog_test(
    name = "repo_test",
    size = "medium",
    arguments = [
        "git",
        "--fail",
        "--fail-on-scan-errors",
        "--exclude-paths",
        "$(GIT_ROOT)/tools/trufflehog/exclude_paths.txt",
        "file://$(GIT_ROOT)",
    ],
    tags = [
        "local",
        "no-cache",
    ],
    toolchains = ["//tools/git/main/bzl:toolchain_resolved"],
)

docs_filegroup(
    name = "docs",
    srcs = glob(["*.md"]),
    visibility = ["//tools:__pkg__"],
)
