load("@rules_dnscontrol//main/bzl:dnscontrol.bzl", "dnscontrol_site")
load("@rules_docs//docs:defs.bzl", "docs_filegroup")
load("//projects:projects.bzl", "PROJECTS")
load("//projects/al/rules/al:al_binary.bzl", "al_binary_run_map")
load("//projects/al/rules/al:al_config.bzl", "al_config")
load("//tools/vault:defs.bzl", "vault_binary_map")

vault_binary_map(
    name = "vault",
    configs = [":al"],
)

_ZONES = glob(["zones/**/*.zone"])

_INFRA_RECORD_DNSCONFIGS = [
    "//infra/flux:dnsconfig",
    "//infra/forgejo:dnsconfig",
    "//infra/forgejo_runner:dnsconfig",
    "//infra/harbor:dnsconfig",
    "//infra/ingress:dnsconfig",
    "//infra/mikrotik:dnsconfig",
    "//infra/nas:dnsconfig",
    "//infra/pve:dnsconfig",
    "//infra/threexui:dnsconfig",
    "//infra/vault:dnsconfig",
    "//projects/alwaldend.com:dnsconfig",
    "//users/simeonwarren:dnsconfig",
    "//users/simeonwarren/host_bot:dnsconfig",
]

_PROJECT_RECORD_DNSCONFIGS = [
    "//projects/{}:dnsconfig".format(project)
    for project in PROJECTS
    if project != "alwaldend.com" and not project.startswith("rules_")
]

_RECORD_DNSCONFIGS = _INFRA_RECORD_DNSCONFIGS + _PROJECT_RECORD_DNSCONFIGS + [
    "@rules_{}//:dnsconfig".format(project.removeprefix("rules_"))
    for project in PROJECTS
    if project.startswith("rules_")
]

dnscontrol_site(
    name = "requires",
    srcs = _RECORD_DNSCONFIGS,
    config = "dnsconfig.js",
    data = _ZONES,
    visibility = ["//infra:__pkg__"],
)

_BIN = "$(rootpath //tools/dnscontrol)"

al_config(
    name = "al",
    srcs = ["al.lua"],
    visibility = ["//infra/dns:__subpackages__"],
    deps = ["//infra:al"],
)

al_binary_run_map(
    name = "dns",
    args = {
        "": [
            _BIN,
            "--config",
            "$(rootpath dnsconfig.js)",
            "push",
            "-i",
        ],
        "deploy": [
            _BIN,
            "--config",
            "$(rootpath dnsconfig.js)",
            "push",
        ],
        "preview": [
            _BIN,
            "--config",
            "$(rootpath dnsconfig.js)",
            "preview",
        ],
    },
    configs = [":al"],
    data = [
        "creds.json.tpl",
        "dnsconfig.js",
        ":requires_manifest",
        ":requires_manifest_raw",
        "//infra:dnsconfig_nonlanding",
        "//tools/dnscontrol",
        "//tools/vault/injector",
    ] + _ZONES,
    run_args = [
        "--plugin_label",
        "dns",
    ],
)

filegroup(
    name = "project_dnsconfigs",
    srcs = _RECORD_DNSCONFIGS,
    visibility = ["//infra:__pkg__"],
)

docs_filegroup(
    name = "docs",
    srcs = glob(["*.md"]),
    visibility = ["//infra:__pkg__"],
    deps = subpackages(
        include = ["*"],
        allow_empty = True,
    ),
)
