note_id = 1520716969000
guid = "w3jA@O1vgy"
note_type_id = 1496733135171
note_type = "chinese"
tags = ["B1", "Grammatical_Structures", "SentencePatterns"]

[[cards]]
id = 1520716974864
ordinal = 0

[fields]
article-title = "The pattern \"it's not…, it's…\""
english = "You were not helping him by doing this, you're hurting him."
example-sentence = ''
example-type = ''
grammar-construct = 'Subj. + 不是 + [Verb Phrase 1] ， (而)是 + [Verb Phrase 2]'
hanzi = '你这样做不是帮他，是害他。'
notes = ''
pinyin = 'Nǐ zhèyàng zuò bù shì bāng tā, shì hài tā.'
source = 'https://resources.allsetlearning.com/chinese/grammar/ASGT9WYR'
