[[Submissions]]
  Id = 1043209423
  StatusDisplay = "Accepted"
  Lang = "python3"
  QuestionId = 79
  TitleSlug = "word-search"
  Code = "class Solution:\n    def exist(self, board: List[List[str]], word: str) -> bool:\n        row_count, col_count = len(board), len(board[0])\n        word_length = len(word)\n        delta = ((0, 1), (0, -1), (1, 0), (-1, 0))\n\n        if word_length == 1:\n            return any(word in row for row in board)\n\n        def backtrack(row: int, col: int, visited: Set, target: int) -> bool:\n            if (row, col) in visited or not 0 <= row < row_count or not 0 <= col < col_count:\n                return False\n\n            if board[row][col] != word[target]:\n                return False\n            \n            if target == word_length - 1:\n                return True\n\n            visited.add((row, col))\n            if any(backtrack(row + delta_row, col + delta_col, visited, target + 1)\n                   for delta_row, delta_col in delta):\n                return True\n            visited.remove((row, col))\n            return False\n        \n        start_char = word[0]\n\n        return any(backtrack(row, col, set(), 0) \n                   for row in range(row_count) \n                   for col in range(col_count)\n                   if board[row][col] == start_char)"
  Title = "Word Search"
  Url = "/submissions/detail/1043209423/"
  LangName = "Python3"
  Timestamp = 1694106009
  Status = 10
  Runtime = "9144 ms"
  IsPending = "Not Pending"
  Memory = "16.4 MB"
  CompareResult = "11111111111111111111111111111111111111111111111111111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
