[[Submissions]]
  Id = 1000092993
  StatusDisplay = "Accepted"
  Lang = "python3"
  QuestionId = 412
  TitleSlug = "fizz-buzz"
  Code = "class Solution:\n    def fizzBuzz(self, n: int) -> List[str]:\n        result = []\n\n        for i in range(1, n + 1):\n            div_by_3, div_by_5 = i % 3 == 0, i % 5 == 0\n            value = None\n\n            if div_by_3 and div_by_5:\n                value = \"FizzBuzz\"\n            elif div_by_3:\n                value = \"Fizz\"\n            elif div_by_5:\n                value = \"Buzz\"\n            else:\n                value = str(i)\n            \n            result.append(value)\n        \n        return result"
  Title = "Fizz Buzz"
  Url = "/submissions/detail/1000092993/"
  LangName = "Python3"
  Timestamp = 1689935581
  Status = 10
  Runtime = "52 ms"
  IsPending = "Not Pending"
  Memory = "17.4 MB"
  CompareResult = "11111111"
  HasNotes = false
  FlagType = 1
