load("@rules_docs//docs:defs.bzl", "docs_filegroup")

package(default_visibility = ["//:__subpackages__"])

exports_files(["theme.json"])

alias(
    name = "mmdc",
    actual = "//tools/mermaid/cmd/mmdc",
)

docs_filegroup(
    name = "docs",
    srcs = glob(["*.md"]),
    visibility = ["//tools:__pkg__"],
    deps = subpackages(
        include = ["*"],
        allow_empty = True,
    ),
)
