AL_BAZEL_CONTRACTS_LIST = [
    "action_cache.proto",
    # "analysis_v2.proto",
    "bazel_flags.proto",
    # "bazel_output_service.proto",
    # "bazel_output_service_rev2.proto",
    # "build.proto",
    "builtin.proto",
    "cache_salt.proto",
    # "command_line.proto",
    # "command_server.proto",
    "crash_debugging.proto",
    "crosstool_config.proto",
    "deps.proto",
    "desugar_deps.proto",
    "execution_graph.proto",
    "execution_statistics.proto",
    "extra_actions_base.proto",
    # "failure_details.proto",
    "file_invalidation_data.proto",
    # "invocation_policy.proto",
    "java_compilation.proto",
    "memory_pressure.proto",
    "option_filters.proto",
    # "remote_execution_log.proto",
    "remote_scrubbing.proto",
    # "spawn.proto",
    "stardoc_output.proto",
    "strategy_policy.proto",
    "test_status.proto",
    "worker_protocol.proto",
    "xcode_config.proto",
    # "project/buildable_unit.proto",
    "project/enforcement_policy.proto",
    # "project/project.proto",
]
