[[Submissions]]
  Id = 1057826154
  StatusDisplay = "Accepted"
  Lang = "python3"
  QuestionId = 11
  TitleSlug = "container-with-most-water"
  Code = "class Solution:\n    def maxArea(self, height: List[int]) -> int:\n        left = 0\n        right = len(height) - 1\n        maxArea = 0\n\n        while left < right:\n            currentArea = min(height[left], height[right]) * (right - left)\n            if currentArea > maxArea:\n                maxArea = currentArea\n\n            if height[left] < height[right]:\n                left += 1\n            else:\n                right -= 1\n\n        return maxArea"
  Title = "Container With Most Water"
  Url = "/submissions/detail/1057826154/"
  LangName = "Python3"
  Timestamp = 1695551335
  Status = 10
  Runtime = "576 ms"
  IsPending = "Not Pending"
  Memory = "29.3 MB"
  CompareResult = "1111111111111111111111111111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
