load("@bazel_skylib//:bzl_library.bzl", "bzl_library")

bzl_library(
    name = "skill_library",
    srcs = ["skill_library.bzl"],
    visibility = ["//skill:__pkg__"],
)

bzl_library(
    name = "skill_validation",
    srcs = ["skill_validation.bzl"],
    visibility = ["//skill:__pkg__"],
    deps = [":skill_library"],
)
