load("//tools/docs:defs.bzl", "docs_filegroup")
load("//tools/toml/main/bzl:al_toml_data.bzl", "al_toml_data")

docs_filegroup(
    name = "docs",
    srcs = glob(["*.md"]) + [":countries"],
    visibility = ["//data:__pkg__"],
)

al_toml_data(
    name = "countries",
    srcs = ["countries.toml"],
    visibility = ["//:__subpackages__"],
)
