package main

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"unicode/utf8"
)

const (
	commitDisclaimer      = "LLM-disclaimer: This commit was generated by an LLM."
	pullRequestDisclaimer = "LLM-disclaimer: This pull request was generated by an LLM."
	commitMessageLimit    = 60 * 1024
)

type deliveryConfig struct {
	Repository string
	Remote     string
	Base       string
	Forge      string
	ForgeCLI   string
	GitCLI     string
}

type delivery struct {
	repository       *gitRepository
	remote           string
	fetchEndpoint    string
	pushEndpoint     string
	base             string
	remoteRepository remoteRepository
	forge            forge
}

func newDelivery(
	ctx context.Context,
	config deliveryConfig,
	getenv func(string) string,
	runner commandRunner,
) (*delivery, error) {
	remote := strings.TrimSpace(config.Remote)
	if remote == "" {
		remote = "origin"
	}
	if err := validateRemoteName(remote); err != nil {
		return nil, err
	}
	repository, err := openGitRepository(
		ctx,
		config.Repository,
		config.GitCLI,
		getenv,
		runner,
	)
	if err != nil {
		return nil, err
	}
	fetchURL, pushURL, err := repository.remoteURLs(ctx, remote)
	if err != nil {
		return nil, err
	}
	fetchRepository, err := parseRemoteRepository(fetchURL)
	if err != nil {
		return nil, fmt.Errorf("parse fetch remote: %w", err)
	}
	pushRepository, err := parseRemoteRepository(pushURL)
	if err != nil {
		return nil, fmt.Errorf("parse push remote: %w", err)
	}
	if !sameRemoteRepository(fetchRepository, pushRepository) {
		return nil, fmt.Errorf(
			"fetch and push URLs identify different repositories",
		)
	}
	if err := requireCanonicalSSHEndpoint(fetchURL); err != nil {
		return nil, fmt.Errorf("validate captured fetch endpoint: %w", err)
	}
	if err := requireCanonicalSSHEndpoint(pushURL); err != nil {
		return nil, fmt.Errorf("validate captured push endpoint: %w", err)
	}
	forge, err := resolveForge(
		config.Forge,
		config.ForgeCLI,
		fetchRepository,
		runner,
		repository.directory,
	)
	if err != nil {
		return nil, err
	}
	if err := forge.Preflight(ctx, fetchRepository); err != nil {
		return nil, err
	}
	return &delivery{
		repository:       repository,
		remote:           remote,
		fetchEndpoint:    fetchURL,
		pushEndpoint:     pushURL,
		base:             strings.TrimSpace(config.Base),
		remoteRepository: fetchRepository,
		forge:            forge,
	}, nil
}

type inspection struct {
	Repository         string           `json:"repository"`
	Branch             string           `json:"branch"`
	HeadRef            string           `json:"head_ref"`
	LocalHeadOID       string           `json:"local_head_oid"`
	LocalTreeOID       string           `json:"local_tree_oid"`
	Remote             string           `json:"remote"`
	RemoteRepository   remoteRepository `json:"remote_repository"`
	Forge              string           `json:"forge"`
	Base               string           `json:"base"`
	BaseOID            string           `json:"base_oid"`
	RemoteHeadOID      string           `json:"remote_head_oid,omitempty"`
	RemoteHeadDiverged bool             `json:"remote_head_diverged"`
	PullRequest        *pullRequest     `json:"pull_request,omitempty"`
	UniqueCommitCount  int              `json:"unique_commit_count"`
	FeatureCommits     []featureCommit  `json:"feature_commits,omitempty"`
	MergeCommits       []string         `json:"merge_commits,omitempty"`
	BaseIsAncestor     bool             `json:"base_is_ancestor"`
	NeedsRebase        bool             `json:"needs_rebase"`
	Status             repositoryStatus `json:"status"`
	OperationState     []string         `json:"operation_state,omitempty"`
	Refusals           []string         `json:"refusals,omitempty"`
}

func (d *delivery) inspect(
	ctx context.Context,
) (result *inspection, returnErr error) {
	branch, head, err := d.repository.branchHead(ctx)
	if err != nil {
		return nil, err
	}
	tree, err := d.repository.tree(ctx, head)
	if err != nil {
		return nil, err
	}
	report := &inspection{
		Repository:       d.repository.directory,
		Branch:           branch,
		HeadRef:          "refs/heads/" + branch,
		LocalHeadOID:     head,
		LocalTreeOID:     tree,
		Remote:           d.remote,
		RemoteRepository: d.remoteRepository,
		Forge:            d.forge.Name(),
	}
	report.OperationState, err = d.repository.operationState(ctx)
	if err != nil {
		return nil, err
	}
	if len(report.OperationState) != 0 {
		report.Refusals = append(
			report.Refusals,
			"an in-progress Git operation is present: "+
				strings.Join(report.OperationState, ", "),
		)
	}

	allPullRequests, err := d.forge.PullRequests(
		ctx,
		d.remoteRepository,
		branch,
	)
	if err != nil {
		return nil, err
	}
	exact, err := exactPullRequests(
		allPullRequests,
		d.remoteRepository,
		branch,
	)
	if err != nil {
		return nil, err
	}
	selectedPullRequest, pullRequestRefusals := selectOpenPullRequest(exact)
	report.PullRequest = selectedPullRequest
	report.Refusals = append(report.Refusals, pullRequestRefusals...)
	if report.PullRequest != nil {
		report.Base = report.PullRequest.BaseRefName
		if d.base != "" && d.base != report.Base {
			report.Refusals = append(
				report.Refusals,
				fmt.Sprintf(
					"explicit base %q differs from pull request base %q",
					d.base,
					report.Base,
				),
			)
		}
	} else {
		report.Base = d.base
		if report.Base == "" {
			report.Refusals = append(
				report.Refusals,
				"no open pull request exists and no explicit base was supplied",
			)
		}
	}
	if report.Base == "" {
		report.Status, err = d.repository.status(ctx)
		if err != nil {
			return nil, err
		}
		if err := d.repository.requireBranchHead(ctx, branch, head); err != nil {
			return nil, err
		}
		sort.Strings(report.Refusals)
		return report, nil
	}
	if report.Base == branch {
		report.Refusals = append(
			report.Refusals,
			"the feature branch is the pull request base",
		)
	}

	snapshot, err := d.repository.snapshot(
		ctx,
		d.fetchEndpoint,
		report.Base,
		branch,
	)
	if err != nil {
		return nil, err
	}
	defer func() {
		if cleanupErr := snapshot.close(context.Background()); cleanupErr != nil {
			returnErr = errors.Join(
				returnErr,
				fmt.Errorf("clean inspection snapshot: %w", cleanupErr),
			)
		}
	}()
	report.BaseOID = snapshot.BaseOID
	report.RemoteHeadOID = snapshot.RemoteHeadOID
	if report.PullRequest != nil {
		if report.RemoteHeadOID == "" {
			report.Refusals = append(
				report.Refusals,
				"the pull request head ref is absent from the selected remote",
			)
		} else if report.PullRequest.HeadRefOID != report.RemoteHeadOID {
			report.Refusals = append(
				report.Refusals,
				"the pull request head OID differs from the freshly fetched head",
			)
		}
	}
	report.UniqueCommitCount, err = d.repository.commitCount(
		ctx,
		snapshot.BaseOID,
		head,
	)
	if err != nil {
		return nil, err
	}
	report.RemoteHeadDiverged = report.RemoteHeadOID != "" &&
		report.RemoteHeadOID != head && report.RemoteHeadOID != snapshot.BaseOID
	report.MergeCommits, err = d.repository.mergeCommits(
		ctx,
		snapshot.BaseOID,
		head,
	)
	if err != nil {
		return nil, err
	}
	report.FeatureCommits, err = d.repository.featureCommits(
		ctx,
		snapshot.BaseOID,
		head,
	)
	if err != nil {
		return nil, err
	}
	if report.UniqueCommitCount > 1 {
		report.Refusals = append(
			report.Refusals,
			multiCommitRefusal(report.UniqueCommitCount),
		)
	}
	if len(report.MergeCommits) != 0 {
		report.Refusals = append(
			report.Refusals,
			"feature range contains a merge commit",
		)
	}
	report.BaseIsAncestor, err = d.repository.isAncestor(
		ctx,
		snapshot.BaseOID,
		head,
	)
	if err != nil {
		return nil, err
	}
	report.NeedsRebase = !report.BaseIsAncestor
	report.Status, err = d.repository.status(ctx)
	if err != nil {
		return nil, err
	}
	if err := d.repository.requireBranchHead(ctx, branch, head); err != nil {
		return nil, err
	}
	sort.Strings(report.Refusals)
	return report, nil
}

func ensureNoRefusals(report *inspection) error {
	if len(report.Refusals) == 0 {
		return nil
	}
	return fmt.Errorf("delivery refused: %s", strings.Join(report.Refusals, "; "))
}

type prepareOptions struct {
	MessageFile      string
	ReceiptFile      string
	Paths            []string
	UseIndex         bool
	MessageOnly      bool
	RewriteOID       string
	ConsolidateOID   string
	ReplaceRemoteOID string
}

type consolidationEvidence struct {
	ParentOID       string
	AuthorOID       string
	SignatureSource []string
}

type prepareReport struct {
	Inspection *inspection        `json:"inspection"`
	HeadOID    string             `json:"head_oid"`
	TreeOID    string             `json:"tree_oid"`
	Receipt    preparationReceipt `json:"receipt"`
	Projection commitProjection   `json:"pull_request_projection"`
}

func (d *delivery) prepare(
	ctx context.Context,
	options prepareOptions,
) (result *prepareReport, returnErr error) {
	if err := d.requireSameTaskOutputs(
		options.MessageFile,
		options.ReceiptFile,
	); err != nil {
		return nil, err
	}
	receiptTransaction, err := d.beginReceiptTransaction(
		ctx,
		options.ReceiptFile,
		false,
	)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := receiptTransaction.close(); closeErr != nil {
			returnErr = errors.Join(returnErr, closeErr)
		}
	}()
	message, err := d.readMessage(ctx, options.MessageFile)
	if err != nil {
		return nil, err
	}
	message, err = withCommitDisclaimer(message)
	if err != nil {
		return nil, err
	}
	report, err := d.inspect(ctx)
	if err != nil {
		return nil, err
	}
	if options.RewriteOID != "" && options.ConsolidateOID != "" {
		return nil, fmt.Errorf("--rewrite and --consolidate are mutually exclusive")
	}
	if options.MessageOnly && options.ConsolidateOID != "" {
		return nil, fmt.Errorf("--message-only cannot be combined with --consolidate")
	}
	var consolidation *consolidationEvidence
	if options.ConsolidateOID != "" {
		consolidation, err = d.requireConsolidationEvidence(
			ctx,
			report,
			options.ConsolidateOID,
			message,
		)
		if err != nil {
			return nil, err
		}
	}
	if err := ensurePreparationRefusals(report, consolidation != nil); err != nil {
		return nil, err
	}
	if err := requireRemoteReplacementAuthorization(
		report,
		options.ReplaceRemoteOID,
	); err != nil {
		return nil, err
	}
	if err := refuseScratchPaths(report.Status.Staged); err != nil {
		return nil, err
	}

	paths, err := validateTaskPaths(options.Paths)
	if err != nil {
		return nil, err
	}
	if len(paths) != 0 {
		if err := d.repository.requireDefaultIndexFlags(ctx, paths); err != nil {
			return nil, fmt.Errorf("explicit task path index flag gate: %w", err)
		}
	}
	var preparedHead string
	var scope aggregateScope
	var preparationSnapshot *refSnapshot
	defer func() {
		if preparationSnapshot == nil {
			return
		}
		if cleanupErr := preparationSnapshot.close(
			context.Background(),
		); cleanupErr != nil {
			returnErr = errors.Join(
				returnErr,
				fmt.Errorf("clean preparation snapshot: %w", cleanupErr),
			)
		}
	}()
	if options.MessageOnly {
		if len(paths) != 0 || options.UseIndex {
			return nil, fmt.Errorf(
				"--message-only cannot be combined with --path or --use-index",
			)
		}
		if len(report.Status.Staged) != 0 {
			return nil, fmt.Errorf("message-only amend refused with staged changes")
		}
		if err := d.repository.requireIndexTree(
			ctx,
			report.LocalTreeOID,
		); err != nil {
			return nil, fmt.Errorf("message-only index preflight: %w", err)
		}
		preparationSnapshot, err = d.preflightMessageOnly(ctx, report)
		if err != nil {
			return nil, err
		}
		if err := d.requireRewriteEvidence(ctx, report, options.RewriteOID); err != nil {
			return nil, err
		}
		parentOID, err := d.candidateParent(ctx, report, nil)
		if err != nil {
			return nil, err
		}
		scope, err = d.buildAggregateScope(
			ctx,
			parentOID,
			report.LocalTreeOID,
			scopeModeMessageOnly,
			nil,
		)
		if err != nil {
			return nil, err
		}
		if err := d.repository.requireDefaultIndexFlags(
			ctx,
			scope.AuthorizedPaths,
		); err != nil {
			return nil, fmt.Errorf("message-only index flag gate: %w", err)
		}
		preparedHead, err = d.repository.commitChecked(
			ctx,
			message,
			true,
			report.LocalHeadOID,
			report.LocalTreeOID,
			report.Branch,
			scope.AuthorizedPaths,
		)
		if err != nil {
			return nil, err
		}
	} else {
		if (len(paths) == 0) == !options.UseIndex {
			return nil, fmt.Errorf(
				"select exactly one of one-or-more --path flags or --use-index",
			)
		}
		if report.UniqueCommitCount == 1 {
			if err := d.requireRewriteEvidence(
				ctx,
				report,
				options.RewriteOID,
			); err != nil {
				return nil, err
			}
		} else if report.UniqueCommitCount > 1 && consolidation == nil {
			return nil, fmt.Errorf(
				"feature commit count is %d; use --consolidate with the exact inspected head after ownership review",
				report.UniqueCommitCount,
			)
		} else if options.RewriteOID != "" {
			return nil, fmt.Errorf(
				"--rewrite was supplied, but the feature range has no commit",
			)
		}
		var preparedIndexTree string
		if options.UseIndex {
			if err := d.repository.requireDefaultIndexFlags(
				ctx,
				[]string{"."},
			); err != nil {
				return nil, fmt.Errorf("prepared-index flag gate: %w", err)
			}
			preparedIndexTree, err = d.repository.indexTree(ctx)
			if err != nil {
				return nil, err
			}
		}
		if len(paths) != 0 {
			for _, staged := range report.Status.Staged {
				if !isAllowedPath(staged, paths) {
					return nil, fmt.Errorf(
						"already staged path %q is outside the explicit task paths",
						staged,
					)
				}
			}
			if report.NeedsRebase {
				if err := refusePathsOutside(
					report.Status.Unstaged,
					paths,
					"unstaged",
				); err != nil {
					return nil, err
				}
				if err := refusePathsOutside(
					report.Status.Untracked,
					paths,
					"untracked",
				); err != nil {
					return nil, err
				}
			}
			if err := d.repository.addPaths(ctx, paths); err != nil {
				return nil, err
			}
			staged, err := d.repository.status(ctx)
			if err != nil {
				return nil, err
			}
			for _, stagedPath := range staged.Staged {
				if !isAllowedPath(stagedPath, paths) {
					return nil, fmt.Errorf(
						"staged path %q is outside the explicit task paths",
						stagedPath,
					)
				}
			}
		} else if report.NeedsRebase &&
			(len(report.Status.Unstaged) != 0 || len(report.Status.Untracked) != 0) {
			return nil, fmt.Errorf(
				"prepared-index mode cannot preserve unrelated dirty paths across the required rebase",
			)
		}
		hasChanges, err := d.repository.hasStagedChanges(ctx)
		if err != nil {
			return nil, err
		}
		if !hasChanges && consolidation == nil {
			return nil, fmt.Errorf("the prepared index is empty")
		}
		indexTree, err := d.repository.indexTree(ctx)
		if err != nil {
			return nil, err
		}
		preparedStatus, err := d.repository.status(ctx)
		if err != nil {
			return nil, err
		}
		if err := refuseScratchPaths(preparedStatus.Staged); err != nil {
			return nil, err
		}
		if len(paths) != 0 {
			if err := refusePathsOutside(
				preparedStatus.Staged,
				paths,
				"staged",
			); err != nil {
				return nil, err
			}
		} else if indexTree != preparedIndexTree {
			return nil, fmt.Errorf(
				"prepared index changed after inspection; review and retry",
			)
		}
		confirmedIndexTree, err := d.repository.indexTree(ctx)
		if err != nil {
			return nil, err
		}
		if confirmedIndexTree != indexTree {
			return nil, fmt.Errorf("index changed during final scope verification")
		}
		parentOID, err := d.candidateParent(ctx, report, consolidation)
		if err != nil {
			return nil, err
		}
		mode := scopeModePaths
		if options.UseIndex {
			mode = scopeModeUseIndex
		}
		scope, err = d.buildAggregateScope(
			ctx,
			parentOID,
			indexTree,
			mode,
			paths,
		)
		if err != nil {
			return nil, err
		}
		if err := d.repository.requireDefaultIndexFlags(
			ctx,
			scope.AuthorizedPaths,
		); err != nil {
			return nil, fmt.Errorf("final aggregate index flag gate: %w", err)
		}
		if err := d.repository.requireIndexTree(ctx, indexTree); err != nil {
			return nil, fmt.Errorf("final prepared index gate: %w", err)
		}
		preparationSnapshot, err = d.preflightPreparedCommit(
			ctx,
			report,
			parentOID,
		)
		if err != nil {
			return nil, err
		}
		if consolidation == nil {
			preparedHead, err = d.repository.commitChecked(
				ctx,
				message,
				report.UniqueCommitCount == 1,
				report.LocalHeadOID,
				indexTree,
				report.Branch,
				scope.AuthorizedPaths,
			)
		} else {
			preparedHead, err = d.repository.commitConsolidatedChecked(
				ctx,
				message,
				report.LocalHeadOID,
				indexTree,
				report.Branch,
				consolidation.ParentOID,
				consolidation.AuthorOID,
				consolidation.SignatureSource,
				scope.AuthorizedPaths,
			)
		}
		if err != nil {
			return nil, err
		}
	}

	prepared, err := d.finishPreparation(
		ctx,
		report,
		preparedHead,
		scope,
		preparationSnapshot,
		receiptTransaction,
	)
	if err != nil {
		return nil, err
	}
	result = prepared
	if preparationSnapshot != nil {
		if cleanupErr := preparationSnapshot.close(
			context.Background(),
		); cleanupErr != nil {
			preparationSnapshot = nil
			return result, fmt.Errorf(
				"clean preparation snapshot after receipt creation: %w",
				cleanupErr,
			)
		}
		preparationSnapshot = nil
	}
	return result, nil
}

func requireRemoteReplacementAuthorization(
	report *inspection,
	expectedRemoteOID string,
) error {
	if expectedRemoteOID != "" && !isObjectID(expectedRemoteOID) {
		return fmt.Errorf("--replace-remote must be a full Git object ID")
	}
	if report.RemoteHeadDiverged {
		if report.RemoteHeadOID == "" {
			return fmt.Errorf(
				"remote feature divergence was reported without an exact remote OID",
			)
		}
		if expectedRemoteOID == "" {
			return fmt.Errorf(
				"the remote feature ref contains work absent from the exact local candidate; replacement requires --replace-remote=%s after external ownership proof",
				report.RemoteHeadOID,
			)
		}
		if expectedRemoteOID != report.RemoteHeadOID {
			return fmt.Errorf(
				"--replace-remote differs from the freshly fetched remote feature OID",
			)
		}
		return nil
	}
	if expectedRemoteOID == "" {
		return nil
	}
	if report.RemoteHeadOID == "" {
		return fmt.Errorf(
			"--replace-remote cannot authorize replacement of an absent remote feature ref",
		)
	}
	return fmt.Errorf(
		"--replace-remote is unnecessary because the remote feature ref does not diverge from the exact local candidate",
	)
}

func (d *delivery) requireSameTaskOutputs(values ...string) error {
	if len(values) < 2 {
		return fmt.Errorf("at least two task output paths are required")
	}
	want := ""
	for _, value := range values {
		if filepath.IsAbs(value) {
			if filepath.Clean(value) != value {
				return fmt.Errorf(
					"task output path %q must use a canonical lexical form",
					value,
				)
			}
		} else if err := validateTaskOutputPath(
			filepath.ToSlash(value),
		); err != nil {
			return fmt.Errorf("invalid task output path %q: %w", value, err)
		}
		absolute := value
		if !filepath.IsAbs(absolute) {
			absolute = filepath.Join(d.repository.directory, absolute)
		}
		relative, err := filepath.Rel(
			d.repository.directory,
			filepath.Clean(absolute),
		)
		if err != nil {
			return fmt.Errorf("locate task output path: %w", err)
		}
		relative = filepath.ToSlash(relative)
		if err := validateTaskOutputPath(relative); err != nil {
			return fmt.Errorf("invalid task output path %q: %w", value, err)
		}
		task := strings.Split(relative, "/")[1]
		if want == "" {
			want = task
		} else if task != want {
			return fmt.Errorf(
				"task output files must share one out/<task>/ directory",
			)
		}
	}
	return nil
}

func (d *delivery) finishPreparation(
	ctx context.Context,
	previous *inspection,
	preparedHead string,
	scope aggregateScope,
	preparationSnapshot *refSnapshot,
	receiptFileTransaction *receiptTransaction,
) (result *prepareReport, returnErr error) {
	branch, currentHead, err := d.repository.branchHead(ctx)
	if err != nil {
		return nil, err
	}
	if branch != previous.Branch {
		return nil, fmt.Errorf("current branch changed during preparation")
	}
	if currentHead != preparedHead {
		return nil, fmt.Errorf("prepared HEAD changed before finalization")
	}
	snapshot := preparationSnapshot
	if snapshot == nil {
		snapshot, err = d.repository.snapshot(
			ctx,
			d.fetchEndpoint,
			previous.Base,
			branch,
		)
		if err != nil {
			return nil, err
		}
		defer func() {
			if cleanupErr := snapshot.close(
				context.Background(),
			); cleanupErr != nil {
				returnErr = errors.Join(
					returnErr,
					fmt.Errorf("clean finalization snapshot: %w", cleanupErr),
				)
			}
		}()
	}
	if snapshot.RemoteHeadOID != previous.RemoteHeadOID {
		return nil, fmt.Errorf(
			"remote feature ref changed during preparation; local changes were preserved but publication is refused",
		)
	}
	if snapshot.BaseOID != previous.BaseOID {
		descendant, err := d.repository.isAncestor(
			ctx,
			previous.BaseOID,
			snapshot.BaseOID,
		)
		if err != nil {
			return nil, err
		}
		if !descendant {
			return nil, fmt.Errorf(
				"fetched base was rewritten to non-descendant history during preparation",
			)
		}
	}
	baseIsAncestor, err := d.repository.isAncestor(
		ctx,
		snapshot.BaseOID,
		currentHead,
	)
	if err != nil {
		return nil, err
	}
	if !baseIsAncestor {
		status, err := d.repository.status(ctx)
		if err != nil {
			return nil, err
		}
		if !status.clean() {
			return nil, fmt.Errorf(
				"the freshly fetched base requires a rebase, but the worktree is not clean",
			)
		}
		rebasedScope := scope
		rebasedHead, err := d.repository.rebase(
			ctx,
			snapshot.BaseOID,
			branch,
			preparedHead,
			func(
				checkContext context.Context,
				candidateRepository *gitRepository,
				candidateHead string,
			) error {
				var reconcileErr error
				rebasedScope, reconcileErr = reconcileRebasedAggregateScope(
					checkContext,
					candidateRepository,
					snapshot.BaseOID,
					candidateHead,
					preparedHead,
					scope,
				)
				return reconcileErr
			},
		)
		if err != nil {
			return nil, err
		}
		scope = rebasedScope
		currentHead = rebasedHead
		observedBranch, observedHead, err := d.repository.branchHead(ctx)
		if err != nil {
			return nil, err
		}
		if observedBranch != previous.Branch || observedHead != currentHead {
			return nil, fmt.Errorf("current branch or HEAD changed during rebase")
		}
	}
	if err := d.requireSingleCommit(ctx, snapshot.BaseOID, currentHead); err != nil {
		return nil, err
	}
	if err := d.repository.rangeDiffCheck(ctx, snapshot.BaseOID, currentHead); err != nil {
		return nil, err
	}
	if err := d.repository.verifyRequiredSignature(ctx, currentHead); err != nil {
		return nil, err
	}
	tree, err := d.repository.tree(ctx, currentHead)
	if err != nil {
		return nil, err
	}
	projection, err := d.repository.projection(ctx, currentHead)
	if err != nil {
		return nil, err
	}
	if err := d.repository.requireBranchHead(
		ctx,
		branch,
		currentHead,
	); err != nil {
		return nil, err
	}
	if err := d.repository.requireIndexTree(ctx, tree); err != nil {
		return nil, fmt.Errorf("final preparation index gate: %w", err)
	}
	if err := d.repository.requireDefaultIndexFlags(
		ctx,
		scope.AuthorizedPaths,
	); err != nil {
		return nil, fmt.Errorf("final preparation index flag gate: %w", err)
	}
	if err := d.verifyAggregateScope(
		ctx,
		snapshot.BaseOID,
		currentHead,
		scope,
	); err != nil {
		return nil, fmt.Errorf("verify final aggregate scope: %w", err)
	}
	receipt, err := d.newPreparationReceipt(
		ctx,
		previous.Base,
		snapshot.BaseOID,
		branch,
		currentHead,
		tree,
		snapshot.RemoteHeadOID,
		previous.PullRequest,
		scope,
	)
	if err != nil {
		return nil, err
	}
	if err := receiptFileTransaction.write(ctx, receipt); err != nil {
		return nil, err
	}
	return &prepareReport{
		Inspection: previous,
		HeadOID:    currentHead,
		TreeOID:    tree,
		Receipt:    receipt,
		Projection: projection,
	}, nil
}

func (d *delivery) candidateParent(
	ctx context.Context,
	report *inspection,
	consolidation *consolidationEvidence,
) (string, error) {
	if report.UniqueCommitCount == 0 {
		return report.LocalHeadOID, nil
	}
	if consolidation != nil {
		return consolidation.ParentOID, nil
	}
	parents, err := d.repository.commitParents(ctx, report.LocalHeadOID)
	if err != nil {
		return "", err
	}
	if len(parents) != 1 {
		return "", fmt.Errorf(
			"aggregate candidate has %d parents, want exactly one",
			len(parents),
		)
	}
	return parents[0], nil
}

func ensurePreparationRefusals(
	report *inspection,
	consolidating bool,
) error {
	if !consolidating {
		return ensureNoRefusals(report)
	}
	want := multiCommitRefusal(report.UniqueCommitCount)
	remaining := make([]string, 0, len(report.Refusals))
	removed := false
	for _, refusal := range report.Refusals {
		if !removed && refusal == want {
			removed = true
			continue
		}
		remaining = append(remaining, refusal)
	}
	if !removed {
		return fmt.Errorf("delivery refused: the expected multi-commit refusal was absent")
	}
	if len(remaining) != 0 {
		return fmt.Errorf("delivery refused: %s", strings.Join(remaining, "; "))
	}
	return nil
}

func multiCommitRefusal(count int) string {
	return fmt.Sprintf(
		"feature range contains %d commits; explicit --consolidate ownership authorization is required",
		count,
	)
}

func (d *delivery) requireConsolidationEvidence(
	_ context.Context,
	report *inspection,
	expectedHead string,
	message string,
) (*consolidationEvidence, error) {
	if !isObjectID(expectedHead) {
		return nil, fmt.Errorf("--consolidate must be a full Git object ID")
	}
	if expectedHead != report.LocalHeadOID {
		return nil, fmt.Errorf("--consolidate differs from the exact inspected local head")
	}
	if report.UniqueCommitCount < 2 {
		return nil, fmt.Errorf(
			"--consolidate requires at least two feature commits, found %d",
			report.UniqueCommitCount,
		)
	}
	if len(report.MergeCommits) != 0 {
		return nil, fmt.Errorf("--consolidate refuses a feature range containing merges")
	}
	if len(report.FeatureCommits) != report.UniqueCommitCount {
		return nil, fmt.Errorf("feature commit inventory is incomplete")
	}
	first := report.FeatureCommits[0]
	if !first.HasDisclaimer {
		return nil, fmt.Errorf(
			"the oldest feature commit lacks the required ownership marker",
		)
	}
	if len(first.Parents) != 1 || !isObjectID(first.Parents[0]) {
		return nil, fmt.Errorf("the oldest feature commit lacks one exact parent")
	}
	previous := first.Parents[0]
	signatureSources := make([]string, 0, len(report.FeatureCommits))
	for _, commit := range report.FeatureCommits {
		if len(commit.Parents) != 1 || commit.Parents[0] != previous {
			return nil, fmt.Errorf("feature commits are not one linear parent chain")
		}
		if commit.AuthorName != first.AuthorName ||
			commit.AuthorEmail != first.AuthorEmail ||
			commit.CommitterName != first.CommitterName ||
			commit.CommitterEmail != first.CommitterEmail {
			return nil, fmt.Errorf(
				"feature commit %s has a different author or committer identity",
				commit.OID,
			)
		}
		if commit.SignatureStatus == "B" {
			return nil, fmt.Errorf("feature commit %s has a bad signature", commit.OID)
		}
		signatureSources = append(signatureSources, commit.OID)
		previous = commit.OID
	}
	if previous != report.LocalHeadOID {
		return nil, fmt.Errorf("feature commit chain does not end at the inspected head")
	}
	if report.PullRequest != nil {
		projection, err := messageProjection(message)
		if err != nil {
			return nil, err
		}
		if !pullRequestMatchesProjection(
			*report.PullRequest,
			projection,
			report.Base,
			report.Branch,
		) {
			return nil, fmt.Errorf(
				"pull request title or body is not the requested consolidation projection; preserve possible human edits",
			)
		}
	}
	return &consolidationEvidence{
		ParentOID:       first.Parents[0],
		AuthorOID:       first.OID,
		SignatureSource: signatureSources,
	}, nil
}

func messageProjection(message string) (commitProjection, error) {
	normalized := normalizeText(message)
	parts := strings.SplitN(normalized, "\n\n", 2)
	if len(parts) != 2 || strings.Contains(parts[0], "\n") {
		return commitProjection{}, fmt.Errorf(
			"commit message must separate its one-line subject from the body with a blank line",
		)
	}
	body, err := pullRequestBody(parts[1])
	if err != nil {
		return commitProjection{}, err
	}
	return commitProjection{Title: parts[0], Body: body}, nil
}

func (d *delivery) preflightMessageOnly(
	ctx context.Context,
	report *inspection,
) (result *refSnapshot, returnErr error) {
	snapshot, err := d.repository.snapshot(
		ctx,
		d.fetchEndpoint,
		report.Base,
		report.Branch,
	)
	if err != nil {
		return nil, err
	}
	failed := true
	defer func() {
		if failed {
			if cleanupErr := snapshot.close(
				context.Background(),
			); cleanupErr != nil {
				returnErr = errors.Join(
					returnErr,
					fmt.Errorf("clean message-only snapshot: %w", cleanupErr),
				)
			}
		}
	}()
	if snapshot.RemoteHeadOID != report.RemoteHeadOID {
		return nil, fmt.Errorf("remote feature ref changed before message-only amendment")
	}
	if snapshot.BaseOID != report.BaseOID {
		descendant, err := d.repository.isAncestor(
			ctx,
			report.BaseOID,
			snapshot.BaseOID,
		)
		if err != nil {
			return nil, err
		}
		if !descendant {
			return nil, fmt.Errorf(
				"fetched base was rewritten to non-descendant history before message-only amendment",
			)
		}
	}
	baseIsAncestor, err := d.repository.isAncestor(
		ctx,
		snapshot.BaseOID,
		report.LocalHeadOID,
	)
	if err != nil {
		return nil, err
	}
	status, err := d.repository.status(ctx)
	if err != nil {
		return nil, err
	}
	if !baseIsAncestor && !status.clean() {
		return nil, fmt.Errorf(
			"message-only amend refused because the required rebase needs a clean worktree and index",
		)
	}
	if len(status.Staged) != 0 {
		return nil, fmt.Errorf("message-only amend refused with staged changes")
	}
	if err := d.repository.requireIndexTree(ctx, report.LocalTreeOID); err != nil {
		return nil, fmt.Errorf("message-only index changed during preflight: %w", err)
	}
	if err := d.repository.requireBranchHead(
		ctx,
		report.Branch,
		report.LocalHeadOID,
	); err != nil {
		return nil, err
	}
	failed = false
	return snapshot, nil
}

func (d *delivery) preflightPreparedCommit(
	ctx context.Context,
	report *inspection,
	candidateParent string,
) (result *refSnapshot, returnErr error) {
	snapshot, err := d.repository.snapshot(
		ctx,
		d.fetchEndpoint,
		report.Base,
		report.Branch,
	)
	if err != nil {
		return nil, err
	}
	failed := true
	defer func() {
		if failed {
			if cleanupErr := snapshot.close(
				context.Background(),
			); cleanupErr != nil {
				returnErr = errors.Join(
					returnErr,
					fmt.Errorf("clean commit preflight snapshot: %w", cleanupErr),
				)
			}
		}
	}()
	status, err := d.repository.status(ctx)
	if err != nil {
		return nil, err
	}
	if snapshot.RemoteHeadOID != report.RemoteHeadOID {
		return nil, fmt.Errorf("remote feature ref changed before commit creation")
	}
	if snapshot.BaseOID != report.BaseOID {
		descendant, err := d.repository.isAncestor(
			ctx,
			report.BaseOID,
			snapshot.BaseOID,
		)
		if err != nil {
			return nil, err
		}
		if !descendant {
			return nil, fmt.Errorf(
				"fetched base was rewritten to non-descendant history before commit creation",
			)
		}
	}
	baseIsAncestor, err := d.repository.isAncestor(
		ctx,
		snapshot.BaseOID,
		candidateParent,
	)
	if err != nil {
		return nil, err
	}
	if !baseIsAncestor &&
		(len(status.Unstaged) != 0 || len(status.Untracked) != 0) {
		return nil, fmt.Errorf(
			"the freshly fetched base requires a rebase, but unrelated worktree changes cannot be preserved",
		)
	}
	if err := d.repository.requireBranchHead(
		ctx,
		report.Branch,
		report.LocalHeadOID,
	); err != nil {
		return nil, err
	}
	failed = false
	return snapshot, nil
}

func refusePathsOutside(
	paths []string,
	allowed []string,
	kind string,
) error {
	for _, value := range paths {
		if !isAllowedPath(value, allowed) {
			return fmt.Errorf(
				"%s path %q is outside the explicit task paths and cannot be preserved across rebase",
				kind,
				value,
			)
		}
	}
	return nil
}

func refuseScratchPaths(paths []string) error {
	for _, value := range paths {
		clean := filepath.ToSlash(filepath.Clean(value))
		if clean == "out" || strings.HasPrefix(clean, "out/") {
			return fmt.Errorf(
				"delivery scratch path %q must remain ignored and untracked",
				value,
			)
		}
	}
	return nil
}

func requireCleanPreparedScope(
	status repositoryStatus,
	scope aggregateScope,
) error {
	for _, group := range []struct {
		kind  string
		paths []string
	}{
		{kind: "staged", paths: status.Staged},
		{kind: "unstaged", paths: status.Unstaged},
		{kind: "untracked", paths: status.Untracked},
	} {
		for _, value := range group.paths {
			if isAllowedPath(value, scope.AuthorizedPaths) {
				return fmt.Errorf(
					"%s prepared-scope path %q differs from the receipt candidate",
					group.kind,
					value,
				)
			}
		}
	}
	return nil
}

func (d *delivery) requireCandidateBoundary(
	ctx context.Context,
	receipt *preparationReceipt,
	report *inspection,
	phase string,
) (repositoryStatus, error) {
	if receipt != nil {
		if err := d.validateReceiptContext(ctx, *receipt, report); err != nil {
			return repositoryStatus{}, fmt.Errorf("%s receipt context: %w", phase, err)
		}
	}
	status, err := d.repository.status(ctx)
	if err != nil {
		return repositoryStatus{}, err
	}
	if len(status.Staged) != 0 {
		return repositoryStatus{}, fmt.Errorf("%s requires a clean index", phase)
	}
	paths := []string(nil)
	if receipt != nil {
		if err := requireCleanPreparedScope(status, receipt.Scope); err != nil {
			return repositoryStatus{}, err
		}
		paths = receipt.Scope.AuthorizedPaths
	} else {
		paths, err = d.repository.changedPaths(
			ctx,
			report.BaseOID,
			report.LocalHeadOID,
		)
		if err != nil {
			return repositoryStatus{}, err
		}
		for _, group := range [][]string{status.Unstaged, status.Untracked} {
			for _, value := range group {
				if isAllowedPath(value, paths) {
					return repositoryStatus{}, fmt.Errorf(
						"%s aggregate path %q differs from the commit",
						phase,
						value,
					)
				}
			}
		}
	}
	if len(paths) == 0 {
		return repositoryStatus{}, fmt.Errorf("%s aggregate path scope is empty", phase)
	}
	if err := d.repository.requireDefaultIndexFlags(ctx, paths); err != nil {
		return repositoryStatus{}, fmt.Errorf("%s index flag gate: %w", phase, err)
	}
	if err := d.repository.requireIndexTree(ctx, report.LocalTreeOID); err != nil {
		return repositoryStatus{}, fmt.Errorf("%s index tree gate: %w", phase, err)
	}
	if err := d.repository.requireBranchHead(
		ctx,
		report.Branch,
		report.LocalHeadOID,
	); err != nil {
		return repositoryStatus{}, fmt.Errorf("%s branch gate: %w", phase, err)
	}
	return status, nil
}

func (d *delivery) requireRewriteEvidence(
	ctx context.Context,
	report *inspection,
	rewriteOID string,
) error {
	if report.UniqueCommitCount != 1 {
		return fmt.Errorf(
			"rewrite requires exactly one feature commit, found %d",
			report.UniqueCommitCount,
		)
	}
	if rewriteOID == "" || rewriteOID != report.LocalHeadOID {
		return fmt.Errorf(
			"rewriting the sole commit requires --rewrite=%s",
			report.LocalHeadOID,
		)
	}
	body, err := d.repository.commitBody(ctx, report.LocalHeadOID)
	if err != nil {
		return err
	}
	if !hasFinalLine(body, commitDisclaimer) {
		return fmt.Errorf("the existing feature commit lacks the required ownership marker")
	}
	if report.PullRequest != nil {
		sources := []string{report.LocalHeadOID}
		if report.RemoteHeadOID != "" &&
			report.RemoteHeadOID != report.LocalHeadOID {
			sources = append(sources, report.RemoteHeadOID)
		}
		matches := false
		for _, sourceOID := range sources {
			projection, projectionErr := d.repository.projection(ctx, sourceOID)
			if projectionErr == nil && pullRequestMatchesProjection(
				*report.PullRequest,
				projection,
				report.Base,
				report.Branch,
			) {
				matches = true
				break
			}
		}
		if !matches {
			return fmt.Errorf(
				"pull request title or body is not an exact owned local or remote commit projection; preserve possible human edits",
			)
		}
	}
	return nil
}

func (d *delivery) readMessage(
	ctx context.Context,
	messageFile string,
) (string, error) {
	return d.readIgnoredText(ctx, messageFile, "--message-file", "message")
}

func (d *delivery) readReviewBody(
	ctx context.Context,
	bodyFile string,
) (string, error) {
	return d.readIgnoredText(ctx, bodyFile, "--body-file", "review body")
}

func (d *delivery) readIgnoredText(
	ctx context.Context,
	inputPath string,
	flag string,
	description string,
) (string, error) {
	if strings.TrimSpace(inputPath) == "" {
		return "", fmt.Errorf("%s is required", flag)
	}
	if filepath.IsAbs(inputPath) {
		if filepath.Clean(inputPath) != inputPath {
			return "", fmt.Errorf(
				"%s path must use a canonical lexical form",
				description,
			)
		}
	} else if err := validateTaskOutputPath(
		filepath.ToSlash(inputPath),
	); err != nil {
		return "", fmt.Errorf(
			"%s must be under an ignored out/<task>/ directory: %w",
			description,
			err,
		)
	}
	absolute := inputPath
	if !filepath.IsAbs(absolute) {
		absolute = filepath.Join(d.repository.directory, absolute)
	}
	absolute = filepath.Clean(absolute)
	resolved, err := filepath.EvalSymlinks(absolute)
	if err != nil {
		return "", fmt.Errorf("resolve %s symlinks: %w", description, err)
	}
	if filepath.Clean(resolved) != filepath.Clean(absolute) {
		return "", fmt.Errorf("%s path must not contain symlinks", description)
	}
	relative, err := filepath.Rel(d.repository.directory, resolved)
	if err != nil {
		return "", fmt.Errorf("locate %s in repository: %w", description, err)
	}
	relative = filepath.ToSlash(relative)
	if err := validateTaskOutputPath(relative); err != nil {
		return "", fmt.Errorf(
			"%s must be under the repository's ignored out/<task>/ directory: %w",
			description,
			err,
		)
	}
	tracked, err := d.repository.pathTracked(ctx, relative)
	if err != nil {
		return "", err
	}
	if tracked {
		return "", fmt.Errorf("%s must be untracked", description)
	}
	ignored, err := d.repository.pathIgnored(ctx, relative)
	if err != nil {
		return "", err
	}
	if !ignored {
		return "", fmt.Errorf("%s must be ignored by Git", description)
	}
	before, err := os.Lstat(resolved)
	if err != nil {
		return "", fmt.Errorf("inspect %s: %w", description, err)
	}
	if !before.Mode().IsRegular() {
		return "", fmt.Errorf("%s must be a regular non-symlink file", description)
	}
	if before.Size() > commitMessageLimit {
		return "", fmt.Errorf("%s exceeds 60 KiB", description)
	}
	file, err := os.Open(resolved)
	if err != nil {
		return "", fmt.Errorf("open %s: %w", description, err)
	}
	defer file.Close()
	after, err := file.Stat()
	if err != nil {
		return "", fmt.Errorf("inspect opened %s: %w", description, err)
	}
	if !after.Mode().IsRegular() || !os.SameFile(before, after) {
		return "", fmt.Errorf("%s changed while it was being opened", description)
	}
	contents, err := io.ReadAll(io.LimitReader(file, commitMessageLimit+1))
	if err != nil {
		return "", fmt.Errorf("read %s: %w", description, err)
	}
	if len(contents) > commitMessageLimit {
		return "", fmt.Errorf("%s exceeds 60 KiB", description)
	}
	readAfter, err := file.Stat()
	if err != nil {
		return "", fmt.Errorf("inspect read %s: %w", description, err)
	}
	if _, err := file.Seek(0, io.SeekStart); err != nil {
		return "", fmt.Errorf("rewind %s: %w", description, err)
	}
	confirmed, err := io.ReadAll(io.LimitReader(file, commitMessageLimit+1))
	if err != nil {
		return "", fmt.Errorf("reread %s: %w", description, err)
	}
	finalInfo, err := file.Stat()
	if err != nil {
		return "", fmt.Errorf("inspect reread %s: %w", description, err)
	}
	pathAfter, err := os.Lstat(resolved)
	if err != nil {
		return "", fmt.Errorf("reinspect %s path: %w", description, err)
	}
	if !bytes.Equal(contents, confirmed) || !os.SameFile(before, pathAfter) ||
		!os.SameFile(after, readAfter) || !os.SameFile(readAfter, finalInfo) ||
		after.Size() != readAfter.Size() || readAfter.Size() != finalInfo.Size() ||
		!after.ModTime().Equal(readAfter.ModTime()) ||
		!readAfter.ModTime().Equal(finalInfo.ModTime()) {
		return "", fmt.Errorf("%s changed while it was being read", description)
	}
	return string(contents), nil
}

type publishOptions struct {
	ValidatedHead string
	ReceiptFile   string
}

type publishReport struct {
	Status        string              `json:"status"`
	HeadOID       string              `json:"head_oid"`
	TreeOID       string              `json:"tree_oid"`
	RemoteHeadOID string              `json:"remote_head_oid"`
	PullRequest   *pullRequest        `json:"pull_request"`
	Verified      bool                `json:"verified"`
	Receipt       *preparationReceipt `json:"receipt,omitempty"`
}

type revalidationRequiredError struct {
	Report *publishReport
}

func (e *revalidationRequiredError) Error() string {
	return fmt.Sprintf(
		"publish paused before push because HEAD changed; rerun validations and retry with --validated-head=%s",
		e.Report.HeadOID,
	)
}

func (d *delivery) publish(
	ctx context.Context,
	options publishOptions,
) (result *publishReport, returnErr error) {
	if !isObjectID(options.ValidatedHead) {
		return nil, fmt.Errorf("--validated-head must be a full Git object ID")
	}
	receiptTransaction, err := d.beginReceiptTransaction(
		ctx,
		options.ReceiptFile,
		true,
	)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := receiptTransaction.close(); closeErr != nil {
			returnErr = errors.Join(returnErr, closeErr)
		}
	}()
	receipt, err := receiptTransaction.read()
	if err != nil {
		return nil, err
	}
	report, err := d.inspect(ctx)
	if err != nil {
		return nil, err
	}
	if err := d.validateReceiptContext(ctx, receipt, report); err != nil {
		return nil, fmt.Errorf("preparation receipt refused: %w", err)
	}
	if report.BaseOID != receipt.BaseOID {
		descendant, err := d.repository.isAncestor(
			ctx,
			receipt.BaseOID,
			report.BaseOID,
		)
		if err != nil {
			return nil, err
		}
		if !descendant {
			return nil, fmt.Errorf(
				"fetched base is not a descendant of the preparation receipt base",
			)
		}
	}
	if err := ensureNoRefusals(report); err != nil {
		return nil, err
	}
	if options.ValidatedHead != receipt.PreparedHeadOID {
		return nil, fmt.Errorf(
			"validated HEAD differs from the preparation receipt head",
		)
	}
	if len(report.Status.Staged) != 0 {
		return nil, fmt.Errorf("publication requires a clean index")
	}
	if err := requireCleanPreparedScope(report.Status, receipt.Scope); err != nil {
		return nil, err
	}
	if err := d.repository.requireDefaultIndexFlags(
		ctx,
		receipt.Scope.AuthorizedPaths,
	); err != nil {
		return nil, fmt.Errorf("publication index flag gate: %w", err)
	}
	if err := d.repository.requireIndexTree(
		ctx,
		receipt.PreparedTreeOID,
	); err != nil {
		return nil, fmt.Errorf("publication index gate: %w", err)
	}
	if report.NeedsRebase && !report.Status.clean() {
		return nil, fmt.Errorf(
			"publication requires a clean worktree and index before rebase",
		)
	}
	if report.UniqueCommitCount != 1 || len(report.MergeCommits) != 0 {
		return nil, fmt.Errorf("publication requires exactly one non-merge feature commit")
	}
	if report.LocalHeadOID != options.ValidatedHead {
		return nil, fmt.Errorf(
			"validated HEAD %s differs from current HEAD %s",
			options.ValidatedHead,
			report.LocalHeadOID,
		)
	}
	body, err := d.repository.commitBody(ctx, report.LocalHeadOID)
	if err != nil {
		return nil, err
	}
	if !hasFinalLine(body, commitDisclaimer) {
		return nil, fmt.Errorf("feature commit lacks the required commit disclaimer")
	}
	projection, err := d.repository.projection(ctx, report.LocalHeadOID)
	if err != nil {
		return nil, err
	}
	if !receiptAllowsRemoteHead(receipt, report.RemoteHeadOID) {
		return nil, fmt.Errorf(
			"fetched remote head differs from the preparation receipt lease",
		)
	}
	pullRequestState, err := receipt.pullRequestState(
		report.PullRequest,
		report.RemoteHeadOID,
		projection,
	)
	if err != nil {
		return nil, err
	}
	if pullRequestState == receiptPullRequestCreatedDesired {
		receipt, err = receipt.bindCreatedPullRequest(
			report.PullRequest,
			report.RemoteHeadOID,
			projection,
		)
		if err != nil {
			return nil, err
		}
		if err := receiptTransaction.write(ctx, receipt); err != nil {
			return nil, err
		}
	}

	snapshot, err := d.repository.snapshot(
		ctx,
		d.fetchEndpoint,
		report.Base,
		report.Branch,
	)
	if err != nil {
		return nil, err
	}
	snapshotClosed := false
	defer func() {
		if snapshotClosed {
			return
		}
		if cleanupErr := snapshot.close(
			context.Background(),
		); cleanupErr != nil {
			returnErr = errors.Join(
				returnErr,
				fmt.Errorf("clean publication snapshot: %w", cleanupErr),
			)
		}
	}()
	if snapshot.RemoteHeadOID != report.RemoteHeadOID ||
		!receiptAllowsRemoteHead(receipt, snapshot.RemoteHeadOID) {
		return nil, fmt.Errorf("remote feature ref changed after inspection; retry from inspect")
	}
	baseAdvanced := snapshot.BaseOID != receipt.BaseOID
	if baseAdvanced {
		descendant, err := d.repository.isAncestor(
			ctx,
			receipt.BaseOID,
			snapshot.BaseOID,
		)
		if err != nil {
			return nil, err
		}
		if !descendant {
			return nil, fmt.Errorf(
				"fetched base is not a descendant of the preparation receipt base",
			)
		}
	}
	baseIsAncestor, err := d.repository.isAncestor(
		ctx,
		snapshot.BaseOID,
		report.LocalHeadOID,
	)
	if err != nil {
		return nil, err
	}
	candidateHead := report.LocalHeadOID
	rebasedScope := receipt.Scope
	if !baseIsAncestor {
		if !baseAdvanced {
			return nil, fmt.Errorf(
				"prepared head is not based on its exact receipt base",
			)
		}
		status, err := d.repository.status(ctx)
		if err != nil {
			return nil, err
		}
		if !status.clean() {
			return nil, fmt.Errorf(
				"the freshly fetched base requires a rebase, but the worktree is not clean",
			)
		}
		candidateHead, err = d.repository.rebase(
			ctx,
			snapshot.BaseOID,
			report.Branch,
			report.LocalHeadOID,
			func(
				checkContext context.Context,
				candidateRepository *gitRepository,
				candidateHead string,
			) error {
				var reconcileErr error
				rebasedScope, reconcileErr = reconcileRebasedAggregateScope(
					checkContext,
					candidateRepository,
					snapshot.BaseOID,
					candidateHead,
					report.LocalHeadOID,
					receipt.Scope,
				)
				return reconcileErr
			},
		)
		if err != nil {
			return nil, err
		}
		candidateTree, err := d.repository.tree(ctx, candidateHead)
		if err != nil {
			return nil, err
		}
		if err := d.repository.requireIndexTree(ctx, candidateTree); err != nil {
			return nil, fmt.Errorf("rebased publication index gate: %w", err)
		}
		if err := d.verifyAggregateScope(
			ctx,
			snapshot.BaseOID,
			candidateHead,
			rebasedScope,
		); err != nil {
			return nil, fmt.Errorf("verify rebased aggregate scope: %w", err)
		}
		derived, err := d.newPreparationReceiptWithExpectation(
			ctx,
			report.Base,
			snapshot.BaseOID,
			report.Branch,
			candidateHead,
			candidateTree,
			snapshot.RemoteHeadOID,
			receipt.ExpectedPullRequest,
			rebasedScope,
		)
		if err != nil {
			return nil, err
		}
		if err := receiptTransaction.write(ctx, derived); err != nil {
			return nil, err
		}
		revalidationReport := &publishReport{
			Status:        "revalidation_required",
			HeadOID:       candidateHead,
			TreeOID:       candidateTree,
			RemoteHeadOID: snapshot.RemoteHeadOID,
			PullRequest:   report.PullRequest,
			Receipt:       &derived,
		}
		if cleanupErr := snapshot.close(context.Background()); cleanupErr != nil {
			snapshotClosed = true
			return revalidationReport, errors.Join(
				&revalidationRequiredError{Report: revalidationReport},
				fmt.Errorf("clean publication snapshot: %w", cleanupErr),
			)
		}
		snapshotClosed = true
		return revalidationReport, &revalidationRequiredError{
			Report: revalidationReport,
		}
	}
	currentBranch, currentHead, err := d.repository.branchHead(ctx)
	if err != nil {
		return nil, err
	}
	if currentBranch != report.Branch || currentHead != candidateHead {
		return nil, fmt.Errorf("current branch or HEAD changed before publication")
	}
	if err := d.requireSingleCommit(
		ctx,
		snapshot.BaseOID,
		currentHead,
	); err != nil {
		return nil, err
	}
	if err := d.repository.rangeDiffCheck(
		ctx,
		snapshot.BaseOID,
		currentHead,
	); err != nil {
		return nil, err
	}
	if err := d.repository.verifyRequiredSignature(ctx, currentHead); err != nil {
		return nil, err
	}
	if currentHead != options.ValidatedHead {
		return nil, fmt.Errorf("HEAD changed after receipt validation")
	}
	currentStatus, err := d.repository.status(ctx)
	if err != nil {
		return nil, err
	}
	if len(currentStatus.Staged) != 0 {
		return nil, fmt.Errorf("index changed before publication")
	}
	if err := requireCleanPreparedScope(currentStatus, receipt.Scope); err != nil {
		return nil, err
	}
	currentTree, err := d.repository.tree(ctx, currentHead)
	if err != nil {
		return nil, err
	}
	if currentTree != receipt.PreparedTreeOID {
		return nil, fmt.Errorf("prepared tree changed before publication")
	}
	if err := d.repository.requireIndexTree(ctx, currentTree); err != nil {
		return nil, fmt.Errorf("final publication index gate: %w", err)
	}
	currentBody, err := d.repository.commitBody(ctx, currentHead)
	if err != nil {
		return nil, err
	}
	if !hasFinalLine(currentBody, commitDisclaimer) {
		return nil, fmt.Errorf("validated commit lacks the required disclaimer")
	}
	if cleanupErr := snapshot.close(context.Background()); cleanupErr != nil {
		snapshotClosed = true
		return nil, fmt.Errorf("clean publication snapshot: %w", cleanupErr)
	}
	snapshotClosed = true
	currentPullRequest, err := d.currentOpenPullRequest(ctx, report.Branch)
	if err != nil {
		return nil, err
	}
	if _, err := receipt.pullRequestState(
		currentPullRequest,
		snapshot.RemoteHeadOID,
		projection,
	); err != nil {
		return nil, err
	}
	if _, err := d.requireCandidateBoundary(
		ctx,
		&receipt,
		report,
		"final publication",
	); err != nil {
		return nil, err
	}
	if err := receiptTransaction.requireCurrent(ctx); err != nil {
		return nil, fmt.Errorf(
			"pre-push preparation receipt gate: %w",
			err,
		)
	}
	if err := d.repository.push(
		ctx,
		d.pushEndpoint,
		currentHead,
		snapshot.RemoteHeadRef,
		snapshot.RemoteHeadOID,
		snapshot.RemoteBaseRef,
		snapshot.BaseOID,
	); err != nil {
		return nil, err
	}
	if err := d.repository.requireBranchHead(
		ctx,
		currentBranch,
		currentHead,
	); err != nil {
		return nil, err
	}
	input := pullRequestInput{
		BaseRefName:     report.Base,
		HeadRefName:     report.Branch,
		ExpectedHeadOID: currentHead,
		Title:           projection.Title,
		Body:            projection.Body,
	}
	pullRequest := currentPullRequest
	if pullRequest != nil {
		expected := *pullRequest
		expected.State = "OPEN"
		expected.HeadRefOID = currentHead
		pullRequest = &expected
	}
	if pullRequest == nil {
		if err := receiptTransaction.requireCurrent(ctx); err != nil {
			return nil, fmt.Errorf(
				"pre-create preparation receipt gate: %w",
				err,
			)
		}
		pullRequest, err = d.forge.CreatePullRequest(
			ctx,
			d.remoteRepository,
			input,
		)
	} else if !pullRequestMatchesInput(*pullRequest, input) {
		if err := receiptTransaction.requireCurrent(ctx); err != nil {
			return nil, fmt.Errorf(
				"pre-update preparation receipt gate: %w",
				err,
			)
		}
		pullRequest, err = d.forge.UpdatePullRequest(
			ctx,
			d.remoteRepository,
			*pullRequest,
			input,
		)
	}
	if err != nil {
		return nil, err
	}
	if pullRequest != nil && !receipt.ExpectedPullRequest.Present {
		receipt, err = receipt.bindCreatedPullRequest(
			pullRequest,
			currentHead,
			projection,
		)
		if err != nil {
			return nil, err
		}
		if err := receiptTransaction.write(ctx, receipt); err != nil {
			return nil, err
		}
	}
	if err := receiptTransaction.requireCurrent(ctx); err != nil {
		return nil, fmt.Errorf(
			"final preparation receipt gate: %w",
			err,
		)
	}
	verified, err := d.verify(ctx, &receipt)
	if err != nil {
		return nil, err
	}
	if verified.Inspection.LocalHeadOID != currentHead ||
		verified.Inspection.LocalTreeOID != currentTree ||
		verified.Inspection.RemoteHeadOID != currentHead {
		return nil, fmt.Errorf(
			"final verification did not describe the exact validated candidate",
		)
	}
	if pullRequest == nil || verified.Inspection.PullRequest == nil ||
		verified.Inspection.PullRequest.ID != pullRequest.ID {
		return nil, fmt.Errorf(
			"final verification selected a different pull request",
		)
	}
	if err := receiptTransaction.requireCurrent(ctx); err != nil {
		return nil, fmt.Errorf(
			"post-verification preparation receipt gate: %w",
			err,
		)
	}
	return &publishReport{
		Status:        "published",
		HeadOID:       verified.Inspection.LocalHeadOID,
		TreeOID:       verified.Inspection.LocalTreeOID,
		RemoteHeadOID: verified.Inspection.RemoteHeadOID,
		PullRequest:   verified.Inspection.PullRequest,
		Verified:      true,
	}, nil
}

func (d *delivery) currentPullRequestMatchingInspection(
	ctx context.Context,
	report *inspection,
) (*pullRequest, error) {
	current, err := d.currentOpenPullRequest(ctx, report.Branch)
	if err != nil {
		return nil, err
	}
	if current == nil {
		return nil, fmt.Errorf("pull request changed after inspection: it is absent")
	}
	if report.PullRequest == nil {
		return nil, fmt.Errorf("pull request appeared after inspection")
	}
	if !samePullRequestMetadata(*current, *report.PullRequest) {
		return nil, fmt.Errorf(
			"pull request metadata changed after inspection; preserve possible human edits",
		)
	}
	return current, nil
}

func (d *delivery) refreshPullRequestSafety(
	ctx context.Context,
	report *inspection,
) error {
	_, err := d.currentPullRequestMatchingInspection(ctx, report)
	return err
}

func (d *delivery) currentOpenPullRequest(
	ctx context.Context,
	branch string,
) (*pullRequest, error) {
	all, err := d.forge.PullRequests(ctx, d.remoteRepository, branch)
	if err != nil {
		return nil, err
	}
	exact, err := exactPullRequests(all, d.remoteRepository, branch)
	if err != nil {
		return nil, err
	}
	current, refusals := selectOpenPullRequest(exact)
	if len(refusals) != 0 {
		return nil, fmt.Errorf(
			"cannot select exact open pull request: %s",
			strings.Join(refusals, "; "),
		)
	}
	return current, nil
}

func samePullRequestMetadata(left, right pullRequest) bool {
	return samePullRequestIdentity(left, right) &&
		left.AuthorLogin == right.AuthorLogin &&
		left.IsDraft == right.IsDraft &&
		normalizeText(left.Title) == normalizeText(right.Title) &&
		normalizeText(left.Body) == normalizeText(right.Body)
}

func samePullRequestIdentity(left, right pullRequest) bool {
	return left.ID == right.ID &&
		left.Number == right.Number &&
		left.URL == right.URL &&
		strings.EqualFold(left.State, "OPEN") &&
		strings.EqualFold(right.State, "OPEN") &&
		left.BaseRefName == right.BaseRefName &&
		left.HeadRefName == right.HeadRefName &&
		left.HeadRefOID == right.HeadRefOID &&
		strings.EqualFold(
			left.HeadRepositoryOwner,
			right.HeadRepositoryOwner,
		) &&
		strings.EqualFold(
			left.HeadRepositoryName,
			right.HeadRepositoryName,
		) &&
		left.IsCrossRepository == right.IsCrossRepository
}

func (d *delivery) requirePullRequestProjection(
	ctx context.Context,
	report *inspection,
) error {
	if report.PullRequest == nil {
		return nil
	}
	if report.RemoteHeadOID == "" {
		return fmt.Errorf("pull request exists without a fetched remote head")
	}
	projection, err := d.repository.projection(ctx, report.RemoteHeadOID)
	if err != nil {
		return err
	}
	if !pullRequestMatchesProjection(
		*report.PullRequest,
		projection,
		report.Base,
		report.Branch,
	) {
		return fmt.Errorf(
			"pull request is not the fetched remote commit projection; preserve possible human edits",
		)
	}
	return nil
}

func pullRequestMatchesProjection(
	pullRequest pullRequest,
	projection commitProjection,
	base string,
	head string,
) bool {
	return pullRequest.BaseRefName == base &&
		pullRequest.HeadRefName == head &&
		normalizeText(pullRequest.Title) == normalizeText(projection.Title) &&
		normalizeText(pullRequest.Body) == normalizeText(projection.Body)
}

func (d *delivery) requireSingleCommit(
	ctx context.Context,
	baseOID string,
	headOID string,
) error {
	count, err := d.repository.commitCount(ctx, baseOID, headOID)
	if err != nil {
		return err
	}
	merges, err := d.repository.mergeCommits(ctx, baseOID, headOID)
	if err != nil {
		return err
	}
	if count != 1 || len(merges) != 0 {
		return fmt.Errorf(
			"prepared feature range has %d commits and %d merges; want one commit and no merges",
			count,
			len(merges),
		)
	}
	hasChanges, err := d.repository.hasRangeChanges(ctx, baseOID, headOID)
	if err != nil {
		return err
	}
	if !hasChanges {
		return fmt.Errorf("prepared feature commit has an empty aggregate diff")
	}
	return nil
}

type verifyReport struct {
	Inspection *inspection `json:"inspection"`
	Verified   bool        `json:"verified"`
}

func (d *delivery) verify(
	ctx context.Context,
	receipt *preparationReceipt,
) (*verifyReport, error) {
	report, err := d.inspect(ctx)
	if err != nil {
		return nil, err
	}
	if receipt != nil {
		if err := d.validateReceiptContext(ctx, *receipt, report); err != nil {
			return nil, fmt.Errorf("preparation receipt refused: %w", err)
		}
		if err := requireCleanPreparedScope(report.Status, receipt.Scope); err != nil {
			return nil, err
		}
		if err := d.repository.requireDefaultIndexFlags(
			ctx,
			receipt.Scope.AuthorizedPaths,
		); err != nil {
			return nil, fmt.Errorf("verification index flag gate: %w", err)
		}
	}
	if err := ensureNoRefusals(report); err != nil {
		return nil, err
	}
	if len(report.Status.Staged) != 0 {
		return nil, fmt.Errorf("final index is not clean")
	}
	if err := d.repository.requireIndexTree(
		ctx,
		report.LocalTreeOID,
	); err != nil {
		return nil, fmt.Errorf("final verification index gate: %w", err)
	}
	if !report.BaseIsAncestor {
		return nil, fmt.Errorf("final feature range is not one rebased non-merge commit")
	}
	if err := d.requireSingleCommit(
		ctx,
		report.BaseOID,
		report.LocalHeadOID,
	); err != nil {
		return nil, err
	}
	if err := d.repository.rangeDiffCheck(
		ctx,
		report.BaseOID,
		report.LocalHeadOID,
	); err != nil {
		return nil, err
	}
	if err := d.repository.verifyRequiredSignature(
		ctx,
		report.LocalHeadOID,
	); err != nil {
		return nil, err
	}
	if report.RemoteHeadOID == "" ||
		report.RemoteHeadOID != report.LocalHeadOID {
		return nil, fmt.Errorf("local HEAD does not equal the fetched remote feature ref")
	}
	if report.PullRequest == nil {
		return nil, fmt.Errorf("no exact open pull request exists")
	}
	if report.PullRequest.HeadRefOID != report.LocalHeadOID {
		return nil, fmt.Errorf("pull request head does not equal local HEAD")
	}
	projection, err := d.repository.projection(ctx, report.LocalHeadOID)
	if err != nil {
		return nil, err
	}
	if receipt != nil {
		state, err := receipt.pullRequestState(
			report.PullRequest,
			report.RemoteHeadOID,
			projection,
		)
		if err != nil {
			return nil, err
		}
		if state != receiptPullRequestDesired {
			return nil, fmt.Errorf(
				"pull request has not reached the receipt's exact desired state",
			)
		}
	}
	if !pullRequestMatchesProjection(
		*report.PullRequest,
		projection,
		report.Base,
		report.Branch,
	) {
		return nil, fmt.Errorf("pull request does not equal the commit projection")
	}
	commitBody, err := d.repository.commitBody(ctx, report.LocalHeadOID)
	if err != nil {
		return nil, err
	}
	if !hasFinalLine(commitBody, commitDisclaimer) ||
		!hasFinalLine(report.PullRequest.Body, pullRequestDisclaimer) {
		return nil, fmt.Errorf("commit or pull request has the wrong final disclaimer")
	}
	if err := d.repository.requireBranchHead(
		ctx,
		report.Branch,
		report.LocalHeadOID,
	); err != nil {
		return nil, err
	}
	currentPullRequest, err := d.currentPullRequestMatchingInspection(
		ctx,
		report,
	)
	if err != nil {
		return nil, err
	}
	report.PullRequest = currentPullRequest
	finalStatus, err := d.requireCandidateBoundary(
		ctx,
		receipt,
		report,
		"final verification",
	)
	if err != nil {
		return nil, err
	}
	report.Status = finalStatus
	return &verifyReport{Inspection: report, Verified: true}, nil
}

func normalizeText(value string) string {
	value = strings.ReplaceAll(value, "\r\n", "\n")
	value = strings.ReplaceAll(value, "\r", "\n")
	return strings.TrimRight(value, "\n")
}

func hasFinalLine(value string, line string) bool {
	normalized := normalizeText(value)
	parts := strings.Split(normalized, "\n")
	return len(parts) != 0 && parts[len(parts)-1] == line
}

func withCommitDisclaimer(message string) (string, error) {
	if !utf8.ValidString(message) {
		return "", fmt.Errorf("commit message is not valid UTF-8")
	}
	normalized := normalizeText(message)
	if normalized == "" {
		return "", fmt.Errorf("commit message is empty")
	}
	lines := strings.Split(normalized, "\n")
	if strings.TrimSpace(lines[0]) == "" {
		return "", fmt.Errorf("commit subject is empty")
	}
	last := lines[len(lines)-1]
	if strings.HasPrefix(last, "LLM-disclaimer:") && last != commitDisclaimer {
		return "", fmt.Errorf("commit message ends with the wrong disclaimer")
	}
	if last != commitDisclaimer {
		normalized += "\n\n" + commitDisclaimer
	}
	return normalized + "\n", nil
}

func pullRequestBody(commitBody string) (string, error) {
	if !utf8.ValidString(commitBody) {
		return "", fmt.Errorf("commit body is not valid UTF-8")
	}
	normalized := normalizeText(commitBody)
	if !hasFinalLine(normalized, commitDisclaimer) {
		return "", fmt.Errorf("commit body does not end with the commit disclaimer")
	}
	lines := strings.Split(normalized, "\n")
	lines[len(lines)-1] = pullRequestDisclaimer
	return strings.Join(lines, "\n") + "\n", nil
}
