note_id = 1520716970333
guid = "P=:a&$7ZLE"
note_type_id = 1496733135171
note_type = "chinese"
tags = ["B2", "Grammatical_Structures", "NoMatterStatements"]

[[cards]]
id = 1520716976197
ordinal = 0

[fields]
article-title = 'Expressing "no matter" with "buguan"'
english = 'You need to pay the taxes wherever you work.'
example-sentence = ''
example-type = ''
grammar-construct = '不管 + Question Word ，(Subj. +) 都 ⋯⋯'
hanzi = '不管你在哪儿工作，都要交税。'
notes = ''
pinyin = ''
source = 'https://resources.allsetlearning.com/chinese/grammar/ASG0NDS6'
