note_id = 1520716967801
guid = "BwX5uUAFDN"
note_type_id = 1496733135171
note_type = "chinese"
tags = ["B1", "Parts_of_Speech", "Prepositions"]

[[cards]]
id = 1520716973665
ordinal = 0

[fields]
article-title = 'Expressing "for" with "wei"'
english = 'You guys can come to cheer us up.'
example-sentence = ''
example-type = ''
grammar-construct = '为 + Party + Verb / Adj.'
hanzi = '你们可以来为我们加油。'
notes = ''
pinyin = 'Nǐmen kěyǐ lái wèi wǒmen jiāyóu.'
source = 'https://resources.allsetlearning.com/chinese/grammar/ASG68RBX'
