ansible_user: ansible
ssh_vault_role: src_infra_dc1_vault_ssh
vault_dir: "/opt/vault"
vault_tls_issue_path: pki/ica_servers/issue/src_infra_dc1_vault_pki_server
vault_tls_alt_names: vault.dc1.alwaldend.com
sysctl_overwrite:
  # Switch does not support ipv6
  net.ipv6.conf.all.disable_ipv6: 1
firewall_allow_port_from:
  - src: "any"
    port: 8200
    comment: Vault traffic
  - src: "any"
    port: 8201
    comment: Cluster traffic
  - src: "any"
    port: 22
    comment: ssh
