load("@rules_docs//docs:defs.bzl", "docs_filegroup")
load("@rules_pkg//pkg:mappings.bzl", "pkg_filegroup")
load("//tools/ansible/main/bzl:al_ansible_role.bzl", "al_ansible_role")

docs_filegroup(
    name = "docs",
    srcs = glob(["*.md"]),
    visibility = ["//projects/ansible_collection/roles:__pkg__"],
    deps = subpackages(
        include = ["*"],
        allow_empty = True,
    ) + [":role.docs"],
)

al_ansible_role(
    name = "role",
    srcs = glob(["**"]) + ["//third_party/com_nousresearch_hermes_agent"],
    renames = {
        "//third_party/com_nousresearch_hermes_agent": "files/install.sh",
    },
    visibility = ["//:__subpackages__"],
)
