[[Submissions]]
  Id = 1049394708
  StatusDisplay = "Accepted"
  Lang = "python3"
  QuestionId = 2352
  TitleSlug = "design-an-atm-machine"
  Code = "class ATM:\n\n    def __init__(self):\n        self._banknotes = (0, ) * 5\n        self._values = (20, 50, 100, 200, 500)\n\n    def deposit(self, banknotesCount: List[int]) -> None:\n        self._banknotes = tuple(banknotesCount[i] + self._banknotes[i] for i in range(5))\n\n    def withdraw(self, amount: int) -> List[int]:\n        withdrawn = [0] * 5\n        for i in reversed(range(5)):\n            value, notes_left = self._values[i], self._banknotes[i]\n            notes_need = min(notes_left, amount // value)\n            \n            if notes_need == 0:\n                continue\n            \n            amount -= value * notes_need\n            withdrawn[i] = notes_need\n\n            if amount == 0:\n                self._banknotes = tuple(self._banknotes[i] - withdrawn[i] \n                                        for i in range(5))\n                return withdrawn\n\n        return (-1, )\n\n\n# Your ATM object will be instantiated and called as such:\n# obj = ATM()\n# obj.deposit(banknotesCount)\n# param_2 = obj.withdraw(amount)"
  Title = "Design an ATM Machine"
  Url = "/submissions/detail/1049394708/"
  LangName = "Python3"
  Timestamp = 1694706302
  Status = 10
  Runtime = "592 ms"
  IsPending = "Not Pending"
  Memory = "20.1 MB"
  CompareResult = "11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
