note_id = 1634364224829
guid = "v_{Akdk.av"
note_type_id = 1630447360002
note_type = "python-basic"
tags = []

[[cards]]
id = 1634370830777
ordinal = 0

[fields]
'Additional Info' = ''
'Back - Basic' = ''
'Back - Code' = 'def new_func(x=3) -&gt; int:<br>&nbsp; &nbsp; pass'
Example = ''
Front = 'Create a function named new_func with a argument x. x should have a default value of 3, and the function should specify a return value of int. the function body should be empty.'
Version = ''
