note_id = 1635647779232
guid = "BL|j{M~vni"
note_type_id = 1630447360002
note_type = "python-basic"
tags = []

[[cards]]
id = 1635647779232
ordinal = 0

[fields]
'Additional Info' = ''
'Back - Basic' = ''
'Back - Code' = '[2, 3, 5, 4, 3, 1]&nbsp;'
Example = ''
Front = 'What would the result of this code be?&nbsp;<br><br><div><div>x = [2, 3, 5]</div><div>y = [4, 3, 1]</div><div>print(x + y)</div></div>'
Version = ''
