note_id = 1520716967743
guid = "fbO=Q<~eM7"
note_type_id = 1496733135171
note_type = "chinese"
tags = ["B1", "Particles", "Parts_of_Speech"]

[[cards]]
id = 1520716973607
ordinal = 0

[fields]
article-title = 'Expressing the self-evident with "ma"'
english = 'The Chinese population is huge.'
example-sentence = ''
example-type = ''
grammar-construct = 'Statement + 嘛'
hanzi = '中国人口很多嘛。'
notes = ''
pinyin = 'Zhōngguó rénkǒu hěn duō ma.'
source = 'https://resources.allsetlearning.com/chinese/grammar/ASGVMC4B'
