[[Submissions]]
  Id = 1717471008
  StatusDisplay = "Accepted"
  Lang = "python3"
  QuestionId = 628
  TitleSlug = "maximum-product-of-three-numbers"
  Code = "class Solution:\n    def maximumProduct(self, nums: List[int]) -> int:\n        nums.sort()\n        pos_res = nums[-1] * nums[-2] * nums[-3]\n        if nums[0] >= 0:\n            return pos_res\n        neg_res = nums[0] * nums[1] * nums[-1]\n        return max(pos_res, neg_res)\n"
  Title = "Maximum Product of Three Numbers"
  Url = "/submissions/detail/1717471008/"
  LangName = "Python3"
  Timestamp = 1753898389
  Status = 10
  Runtime = "5 ms"
  IsPending = "Not Pending"
  Memory = "18.5 MB"
  CompareResult = "111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
