[[Submissions]]
  Id = 1165812156
  StatusDisplay = "Accepted"
  Lang = "python3"
  QuestionId = 76
  TitleSlug = "minimum-window-substring"
  Code = "class Solution:\n    def minWindow(self, s: str, t: str) -> str:\n        if not s or not t:\n            return \"\"\n\n        dictT = defaultdict(int)\n        for c in t:\n            dictT[c] += 1\n\n        required = len(dictT)\n        l, r = 0, 0\n        formed = 0\n\n        windowCounts = defaultdict(int)\n        ans = [-1, 0, 0]\n\n        while r < len(s):\n            c = s[r]\n            windowCounts[c] += 1\n\n            if c in dictT and windowCounts[c] == dictT[c]:\n                formed += 1\n\n            while l <= r and formed == required:\n                c = s[l]\n\n                if ans[0] == -1 or r - l + 1 < ans[0]:\n                    ans[0] = r - l + 1\n                    ans[1] = l\n                    ans[2] = r\n\n                windowCounts[c] -= 1\n                if c in dictT and windowCounts[c] < dictT[c]:\n                    formed -= 1\n\n                l += 1\n\n            r += 1\n\n        return \"\" if ans[0] == -1 else s[ans[1]:ans[2] + 1]\n\n"
  Title = "Minimum Window Substring"
  Url = "/submissions/detail/1165812156/"
  LangName = "Python3"
  Timestamp = 1707049028
  Status = 10
  Runtime = "91 ms"
  IsPending = "Not Pending"
  Memory = "17.4 MB"
  CompareResult = "111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
