load("@rules_hugo//main/bzl:al_hugo_run_binary.bzl", "al_hugo_run_binary")
load("@rules_hugo//main/bzl:al_hugo_site.bzl", "al_hugo_site")
load("@rules_shell//shell:sh_binary.bzl", "sh_binary")
load(":analysis_test.bzl", "hugo_site_action_test")

genrule(
    name = "site_archive",
    testonly = True,
    outs = ["site_archive.tar"],
    cmd = ": >$@",
    tags = ["manual"],
)

sh_binary(
    name = "mock_postcss",
    srcs = ["mock_postcss.sh"],
)

al_hugo_site(
    name = "site_definition",
    testonly = True,
    postcss = ":mock_postcss",
    site = ":site_archive",
    tags = ["manual"],
)

al_hugo_run_binary(
    name = "site",
    testonly = True,
    out_dir = "destination",
    site = ":site_definition",
    tags = ["manual"],
)

hugo_site_action_test(
    name = "hugo_site_action_test",
    target_under_test = ":site",
    visibility = ["//visibility:public"],
)
