- name: Setup host
  tags:
    - host
  block:
    - name: Setup facts
      ansible.builtin.import_role:
        name: alwaldend.main.facts
    - name: Setup firewall
      ansible.builtin.import_role:
        name: alwaldend.main.firewall
    - name: Setup users
      ansible.builtin.import_role:
        name: alwaldend.main.users
    - name: Setup LVM volumes
      ansible.builtin.import_role:
        name: alwaldend.main.lvol
    - name: Setup ssh
      ansible.builtin.import_role:
        name: alwaldend.main.ssh
    - name: Setup os
      ansible.builtin.import_role:
        name: alwaldend.main.os
    - name: Update all packages
      ansible.builtin.import_role:
        name: alwaldend.main.update_all_packages
