note_id = 1520716967656
guid = "RdivHQ-rb$"
note_type_id = 1496733135171
note_type = "chinese"
tags = ["B1", "Nouns", "Parts_of_Speech"]

[[cards]]
id = 1520716973520
ordinal = 0

[fields]
article-title = 'Saying "ever since" with "yilai"'
english = 'Ever since five years ago, prices have been going up.'
example-sentence = ''
example-type = ''
grammar-construct = 'Time Interval + 来'
hanzi = '五年来，物价一直上涨。'
notes = ''
pinyin = 'Wǔ nián lái, wùjià yīzhí shàngzhǎng.'
source = 'https://resources.allsetlearning.com/chinese/grammar/ASGNEMXP'
