[[Submissions]]
  Id = 1043821324
  StatusDisplay = "Accepted"
  Lang = "python3"
  QuestionId = 118
  TitleSlug = "pascals-triangle"
  Code = "class Solution:\n    def generate(self, numRows: int) -> List[List[int]]:\n        answer = [[1]]\n        numRows -= 1\n\n        while numRows > 0:\n            cur, prev = [1], answer[-1]\n            for i in range(len(prev) - 1):\n                cur.append(prev[i] + prev[i+1])\n            cur.append(1)\n            answer.append(cur)\n            numRows -= 1\n        \n        return answer"
  Title = "Pascal's Triangle"
  Url = "/submissions/detail/1043821324/"
  LangName = "Python3"
  Timestamp = 1694169670
  Status = 10
  Runtime = "41 ms"
  IsPending = "Not Pending"
  Memory = "16.2 MB"
  CompareResult = "111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
