[[Submissions]]
  Id = 1087461734
  StatusDisplay = "Accepted"
  Lang = "golang"
  QuestionId = 199
  TitleSlug = "binary-tree-right-side-view"
  Code = "/**\n * Definition for a binary tree node.\n * type TreeNode struct {\n *     Val int\n *     Left *TreeNode\n *     Right *TreeNode\n * }\n */\nfunc rightSideView(root *TreeNode) []int {\n    if root == nil {\n        return []int{}\n    }\n\n    q_cur, q_next, answer := []*TreeNode{root}, []*TreeNode{}, []int{}\n\n    for length := len(q_cur); length > 0; length = len(q_cur) {\n        for _, node := range q_cur {\n            if left := node.Left; left != nil {\n                q_next = append(q_next, left)\n            }\n            if right := node.Right; right != nil {\n                q_next = append(q_next, right)\n            }\n        }\n\n        answer = append(answer, q_cur[length - 1].Val)\n        q_cur = q_cur[:0]\n        q_cur, q_next = q_next, q_cur\n    }\n\n    return answer\n} "
  Title = "Binary Tree Right Side View"
  Url = "/submissions/detail/1087461734/"
  LangName = "Go"
  Timestamp = 1698660780
  Status = 10
  Runtime = "0 ms"
  IsPending = "Not Pending"
  Memory = "2.3 MB"
  CompareResult = "111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
