[[Submissions]]
  Id = 1116406430
  StatusDisplay = "Accepted"
  Lang = "cpp"
  QuestionId = 898
  TitleSlug = "transpose-matrix"
  Code = "class Solution {\npublic:\n    vector<vector<int>> transpose(vector<vector<int>>& matrix) {\n        int row = matrix.size();\n        int col = matrix[0].size();\n        vector<vector<int>> result(col, vector<int>(row, 0));\n        \n        for (int i = 0; i < col; ++i) {\n            for (int j = 0; j < row; ++j) {\n                result[i][j] = matrix[j][i];\n            }\n        }\n        \n        return result;\n    }\n};"
  Title = "Transpose Matrix"
  Url = "/submissions/detail/1116406430/"
  LangName = "C++"
  Timestamp = 1702205146
  Status = 10
  Runtime = "7 ms"
  IsPending = "Not Pending"
  Memory = "10.9 MB"
  CompareResult = "111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
