[[Submissions]]
  Id = 1091199226
  StatusDisplay = "Accepted"
  Lang = "golang"
  QuestionId = 30
  TitleSlug = "substring-with-concatenation-of-all-words"
  Code = "func findSubstring(s string, words []string) []int {\n    \n    wordLen := len(words[0])\n    totalWords := len(words)\n    mem := make(map[string]int, totalWords)\n    \n    \n    for _, str := range words {\n        mem[str] += 1\n    }\n    \n    temp := make(map[string]int, totalWords)\n    var found bool\n    result := make([]int, 0)\n    \n    for i:=0; i + wordLen*totalWords <= len(s);  {\n            \n        found = true\n        temp = make(map[string]int, totalWords)\n\n        for j := i; j < i + wordLen*totalWords; j += wordLen {\n            if _, ok := mem[ s[j:j+wordLen] ]; ok {\n                temp[ s[j:j+wordLen] ] += 1\n            } else {\n                found = false\n                break\n            }\n        }\n\n        if found {\n            for key, _ := range mem {\n                if val, ok := temp[key]; !ok || val != mem[key]{\n                    i++\n                    found = false\n                    break\n                }\n            }\n\n            if found {\n                result = append(result, i)\n                i += 1    \n            }\n\n        } else {\n            i++\n        }\n    }\n    \n    return result\n    \n}"
  Title = "Substring with Concatenation of All Words"
  Url = "/submissions/detail/1091199226/"
  LangName = "Go"
  Timestamp = 1699093498
  Status = 10
  Runtime = "846 ms"
  IsPending = "Not Pending"
  Memory = "13.6 MB"
  CompareResult = "11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
