apiVersion: v1
kind: Secret
metadata:
    name: flux-sops-secret
    namespace: flux-system
stringData:
    sops.vault-token: ENC[AES256_GCM,data:/miPGXJiPOFab4Yn0YWsALpH9mY8g5N6eavOoQ7JiRbKg1hU2zFJm8aCe+bbaM9JmYnbFmKmV3a1J5G6obEAeYMNeXYr89RKI1eLiS/jgFYYFC2HZsr/fqUBE/S/85k=,iv:Zv7Y7S8PM+jU7zGIXSLX6W8GSN8F3cg69KfCBjjcoAY=,tag:BWdlnrbpu6Kefge3o0gCEQ==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    hc_vault:
        - created_at: "2026-07-09T18:00:02Z"
          enc: vault:v1:80vXiDz/QZfnVv33XDSlvlGSE/CzuyAHuKPohxhKLYCnhQRX4jpaPlJpVLmTWBfA6IK48b4xQ4VYxA0C
          engine_path: transit/default
          key_name: src_infra_flux_cluster_sops
          vault_address: https://vault.alwaldend.com:8200
    lastmodified: "2026-07-09T18:00:02Z"
    mac: ENC[AES256_GCM,data:Xio8BIRpTZYnTUdz/HTAzWGvT4OVYcewlc/478BoC0EHBjEP74zxXphuHbHj+8OTpHMJs7xIdg5WtV5IkCos5EojVjogBfP/JOWscIdO2y0M7pN4juUmVp61AXKtkAX93v/hHYyI+xWdsY3bJUhsTiZm6UpwwQ8c0FUJP5beywk=,iv:YDwVVIyuYoCp01tovGr+1Q18M735M8WJWmzP2dkk7ro=,tag:mT03gBBoWk5v4waWhKksgg==,type:str]
    version: 3.13.2
