---
apiVersion: v1
kind: ConfigMap
metadata:
  name: src-infra-harbor-cl-kubeconfig
  namespace: flux-system
  labels:
    reconcile.fluxcd.io/watch: Enabled
data:
  provider: generic
  address: https://harbor.alwaldend.com:6443
  ca.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkakNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzT0RNM01EWXhNVGt3SGhjTk1qWXdOekV3TVRZMU5URTVXaGNOTXpZd056QTNNVFkxTlRFNQpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzT0RNM01EWXhNVGt3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFSQnlDb2VTM2diS3NiVTIxR2tFOWxta0RMcDlUWm1wYVR0Y1JidlhrRXMKNFBzVU5wTFZjS0RKWWwzOXp2U3NsSWNKM3JqQUUvdmRhZUdOc09EeXNja01vMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVWVWaTd1MVhPZE1TV0FsNHRsdTQzCmtsaklIcVF3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnYzB3RWhtVmRVeVU1MUlhTjRUNElNTENsbDJnbVF4eW0KaU0xSU5KcEVkUklDSUFJbi9xZzdoNW4zTUFLR3NGRm1tSXJ3UnVkWVkrTmRLd2VGS1hudXk3aDQKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: src-infra-harbor-cl
  namespace: flux-system
spec:
  path: ./infra/harbor/cl
  sourceRef:
    kind: GitRepository
    name: src
  kubeConfig:
    configMapRef:
      name: src-infra-harbor-cl-kubeconfig
  decryption:
    provider: sops
    secretRef:
      name: flux-sops-secret
  interval: 60m0s
  wait: true
  timeout: 3m0s
  retryInterval: 2m0s
  prune: true
  force: false
---
