[[Submissions]]
  Id = 1010336801
  StatusDisplay = "Accepted"
  Lang = "python3"
  QuestionId = 2134
  TitleSlug = "maximize-the-confusion-of-an-exam"
  Code = "class Solution:\n    def maxConsecutiveAnswers(self, answerKey: str, k: int) -> int:\n        length = len(answerKey)\n        char_t, char_f = \"T\", \"F\"\n        max_size = k\n        count = defaultdict(int)\n        \n        for char in answerKey[:k]:\n            count[char] += 1\n\n        left = 0\n        for right in range(k, length):\n            count[answerKey[right]] += 1\n            \n            while min(count[char_t], count[char_f]) > k: \n                count[answerKey[left]] -= 1\n                left += 1\n            \n            size = right - left + 1\n            if size > max_size:\n                max_size = size\n                    \n        return max_size\n\n\n\n        \n"
  Title = "Maximize the Confusion of an Exam"
  Url = "/submissions/detail/1010336801/"
  LangName = "Python3"
  Timestamp = 1690986804
  Status = 10
  Runtime = "239 ms"
  IsPending = "Not Pending"
  Memory = "16.8 MB"
  CompareResult = "111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
