note_id = 1520716970938
guid = "Co&%;p`i_t"
note_type_id = 1496733135171
note_type = "chinese"
tags = ["C1", "SentencePatterns"]

[[cards]]
id = 1520716976802
ordinal = 0

[fields]
article-title = 'Expressing "Prefer...rather than" with "yuqi...buru"'
english = "I'd rather to work for myself than work for other people."
example-sentence = ''
example-type = ''
grammar-construct = '与其 ⋯⋯ ，不如 ⋯⋯'
hanzi = '与其帮别人打工，还不如自己当老板。'
notes = ''
pinyin = ''
source = 'https://resources.allsetlearning.com/chinese/grammar/ASGWI5CV'
