load("@rules_docs//docs:defs.bzl", "docs_filegroup")
load("@rules_terraform//terraform:defs.bzl", "terraform_binary_map", "terraform_test_map")
load("//projects/al/rules/al:al_binary.bzl", "al_binary_run", "al_binary_run_test")

docs_filegroup(
    name = "docs",
    srcs = glob(["*.md"]),
    visibility = ["//infra/yandex_cloud/org1:__pkg__"],
    deps = subpackages(
        include = ["*"],
        allow_empty = True,
    ),
)

_PROVIDERS = [
    "@terraform_provider_hashicorp_vault//:provider",
    "@terraform_provider_yandex_cloud_yandex//:provider",
]

_CONFIGS = ["//infra/yandex_cloud/org1:al"]

_DATA = glob(["*.tf"]) + [
    "//projects/tf_modules/yc_folder",
    "//projects/tf_modules/tf_backend",
    "//tools/vault/tf_backend",
    "//tools/vault/injector",
]

terraform_binary_map(
    name = "tf",
    data = _DATA,
    providers = _PROVIDERS,
    wrapper = al_binary_run,
    wrapper_kwargs = {
        "configs": _CONFIGS,
        "run_args": [
            "--plugin_label",
            "tf",
            "--plugin_label",
            "vault_env=default_default",
        ],
    },
)

terraform_test_map(
    name = "tf_test",
    data = _DATA,
    providers = _PROVIDERS,
    wrapper = al_binary_run_test,
    wrapper_kwargs = {
        "configs": _CONFIGS,
    },
)
