load("@bazel_skylib//rules:common_settings.bzl", "bool_flag")
load("//tools/docs:defs.bzl", "docs_filegroup")

docs_filegroup(
    name = "docs",
    srcs = glob(["*.md"]),
    visibility = ["//tools:__pkg__"],
)

config_setting(
    name = "use_local_repos",
    flag_values = {
        ":use_local_repos_flag": "true",
    },
)

bool_flag(
    name = "use_local_repos_flag",
    build_setting_default = False,
)

config_setting(
    name = "ci",
    flag_values = {
        ":ci_flag": "true",
    },
    visibility = ["//:__subpackages__"],
)

bool_flag(
    name = "ci_flag",
    build_setting_default = False,
)

config_setting(
    name = "release",
    flag_values = {
        ":release_flag": "true",
    },
    visibility = ["//:__subpackages__"],
)

bool_flag(
    name = "release_flag",
    build_setting_default = False,
)

config_setting(
    name = "harbor",
    flag_values = {
        ":harbor_flag": "true",
    },
    visibility = ["//:__subpackages__"],
)

bool_flag(
    name = "harbor_flag",
    build_setting_default = False,
    visibility = ["//:__subpackages__"],
)
