[[Submissions]]
  Id = 1129545299
  StatusDisplay = "Accepted"
  Lang = "python3"
  QuestionId = 1700
  TitleSlug = "minimum-time-to-make-rope-colorful"
  Code = "class Solution:\n    def minCost(self, colors: str, neededTime: List[int]) -> int:\n        totalTime = 0\n        i = 0\n        j = 0\n\n        while i < len(neededTime) and j < len(neededTime):\n            currTotal = 0\n            currMax = 0\n\n            while j < len(neededTime) and colors[i] == colors[j]:\n                currTotal += neededTime[j]\n                currMax = max(currMax, neededTime[j])\n                j += 1\n\n            totalTime += currTotal - currMax\n            i = j\n\n        return totalTime\n\n\n"
  Title = "Minimum Time to Make Rope Colorful"
  Url = "/submissions/detail/1129545299/"
  LangName = "Python3"
  Timestamp = 1703667077
  Status = 10
  Runtime = "869 ms"
  IsPending = "Not Pending"
  Memory = "28.1 MB"
  CompareResult = "11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
