load("//tools/docs:defs.bzl", "docs_filegroup")

docs_filegroup(
    name = "docs",
    srcs = glob(["*.md"]) + [
        "diagram.svg",
        "//projects/nexus_security_plugin/main/java:model/README.md",
    ],
    renames = {
        "README.md": "_index.md",
        "//projects/nexus_security_plugin/main/java:model/README.md": "model/_index.md",
    },
    visibility = ["//projects:__pkg__"],
    deps = [
        "//projects/nexus_security_plugin/releases:docs",
    ],
)
