load("@rules_docs//docs:defs.bzl", "docs_filegroup")
load("@rules_pkg//pkg:mappings.bzl", "pkg_files")
load("//projects/al/rules/al:al_config.bzl", "al_config")
load("//tools/vault:defs.bzl", "vault_binary_map")

docs_filegroup(
    name = "docs",
    srcs = ["diagram.svg"],
    visibility = [
        "//projects:__pkg__",
        "//projects/nexus_security_plugin/landing:__pkg__",
    ],
    deps = [
        ":docs_pages",
        "//projects/nexus_security_plugin/releases:docs",
        "//projects/nexus_security_plugin/tf:docs",
    ],
)

pkg_files(
    name = "docs_pages",
    srcs = [
        "README.md",
        "//projects/nexus_security_plugin/main/java:model/README.md",
    ],
    prefix = "content/docs/projects/nexus_security_plugin",
    renames = {
        "README.md": "_index.md",
        "//projects/nexus_security_plugin/main/java:model/README.md": "model/_index.md",
    },
)

filegroup(
    name = "dnsconfig",
    srcs = ["dnsconfig.json"],
    visibility = [
        "//infra:__pkg__",
        "//infra/dns:__pkg__",
        "//projects/alwaldend.com:__subpackages__",
        "//projects/nexus_security_plugin/tf:__pkg__",
    ],
)

al_config(
    name = "al",
    srcs = ["al.lua"],
    visibility = ["//projects/nexus_security_plugin/tf:__pkg__"],
    deps = ["//infra:al"],
)

vault_binary_map(
    name = "vault",
    configs = [":al"],
)
