load("@rules_docs//docs:defs.bzl", "docs_filegroup")
load("@rules_terraform//terraform:defs.bzl", "terraform_binary_map")
load("//projects/al/rules/al:al_binary.bzl", "al_binary_run")

docs_filegroup(
    name = "docs",
    srcs = glob(["*.md"]),
    visibility = ["//users/simeonwarren:__pkg__"],
    deps = subpackages(
        include = ["*"],
        allow_empty = True,
    ),
)

_PROVIDERS = [
    "@terraform_provider_hashicorp_vault//:provider",
    "@terraform_provider_telmate_proxmox//:provider",
    "@terraform_provider_yandex_cloud_yandex//:provider",
]

_CONFIGS = ["//users/simeonwarren:al"]

_DATA = glob(["*.tf"]) + [
    "//projects/tf_modules/pve_vm_qemu",
    "//users/simeonwarren:dnsconfig",
    "//tools/vault/tf_backend",
    "//tools/vault/pve_login",
    "//tools/vault/injector",
    "//infra/cloud_init:cloud_init",
]

terraform_binary_map(
    name = "tf",
    data = _DATA,
    providers = _PROVIDERS,
    wrapper = al_binary_run,
    wrapper_kwargs = {
        "configs": _CONFIGS,
        "run_args": [
            "--plugin_label",
            "tf",
            "--plugin_label",
            "vault_env=default_default",
        ],
    },
)
