[[Submissions]]
  Id = 1096032485
  StatusDisplay = "Accepted"
  Lang = "cpp"
  QuestionId = 1894
  TitleSlug = "merge-strings-alternately"
  Code = "class Solution {\npublic:\n    string mergeAlternately(string word1, string word2) {\n        int m = word1.size();\n        int n = word2.size();\n        string result = \"\";\n\n        for (int i = 0; i < max(m, n); i++) {\n            if (i < m) {\n                result.push_back(word1[i]);\n            }\n            if (i < n) {\n                result.push_back(word2[i]);\n            }\n        }\n\n        return result;\n    }\n};"
  Title = "Merge Strings Alternately"
  Url = "/submissions/detail/1096032485/"
  LangName = "C++"
  Timestamp = 1699635003
  Status = 10
  Runtime = "3 ms"
  IsPending = "Not Pending"
  Memory = "6.5 MB"
  CompareResult = "111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
