note_id = 1520716968947
guid = "QSLHn!M`bb"
note_type_id = 1496733135171
note_type = "chinese"
tags = ["B1", "Grammatical_Structures", "SentencePatterns"]

[[cards]]
id = 1520716974811
ordinal = 0

[fields]
article-title = 'Expressing "some" with question words'
english = "Let's pay him a visit sometime."
example-sentence = ''
example-type = ''
grammar-construct = ''
hanzi = '我们什么时候去看看他吧。'
notes = ''
pinyin = 'Wǒmen shénme shíhou qù kànkan tā ba.'
source = 'https://resources.allsetlearning.com/chinese/grammar/ASG7ED89'
