[[Submissions]]
  Id = 1075767391
  StatusDisplay = "Accepted"
  Lang = "python3"
  QuestionId = 1398
  TitleSlug = "number-of-ways-to-stay-in-the-same-place-after-some-steps"
  Code = "class Solution:\n    def numWays(self, steps: int, arrLen: int) -> int:\n        @cache\n        def dp(curr, remain):\n            if remain == 0:\n                if curr == 0:\n                    return 1\n                \n                return 0\n            \n            ans = dp(curr, remain - 1)\n            if curr > 0:\n                ans = (ans + dp(curr - 1, remain - 1)) % MOD\n            \n            if curr < arrLen - 1:\n                ans = (ans + dp(curr + 1, remain - 1)) % MOD\n                \n            return ans\n        \n        MOD = 10 ** 9 + 7\n        return dp(0, steps)"
  Title = "Number of Ways to Stay in the Same Place After Some Steps"
  Url = "/submissions/detail/1075767391/"
  LangName = "Python3"
  Timestamp = 1697364328
  Status = 10
  Runtime = "396 ms"
  IsPending = "Not Pending"
  Memory = "108.6 MB"
  CompareResult = "111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
