load("@bazel_skylib//rules:build_test.bzl", "build_test")
load("@rules_docs//docs:defs.bzl", "docs_filegroup")

docs_filegroup(
    name = "docs",
    srcs = glob(["*.md"]),
    prefix = "content/docs/projects/rules_docs_gazelle",
    visibility = ["//visibility:public"],
)

build_test(
    name = "build_test",
    targets = [
        ":docs",
        "//gazelle",
        "//gazelle:gazelle_docs",
    ],
)
