load("@rules_pkg//pkg:mappings.bzl", "pkg_filegroup")
load("//tools/docs:defs.bzl", "docs_filegroup")

_ROLES = subpackages(
    include = ["*"],
)

docs_filegroup(
    name = "docs",
    srcs = glob(["*.md"]),
    visibility = ["//projects/ansible_collection:__pkg__"],
    deps = ["//{}/{}:docs".format(
        package_name(),
        role,
    ) for role in _ROLES],
)

pkg_filegroup(
    name = "roles",
    srcs = ["//{}/{}:role".format(
        package_name(),
        role,
    ) for role in _ROLES],
    prefix = "roles",
    visibility = ["//:__subpackages__"],
)
