load("@rules_docs//docs:defs.bzl", "docs_filegroup")
load("@rules_shell//shell:sh_binary.bzl", "sh_binary")

sh_binary(
    name = "install",
    srcs = ["install.sh"],
    args = ["$(rootpath //tools/android_cmdtools:sdkmanager)"],
    data = ["//tools/android_cmdtools:sdkmanager"],
)

docs_filegroup(
    name = "docs",
    srcs = glob(["*.md"]),
    visibility = ["//tools:__pkg__"],
)
