[[Submissions]]
  Id = 690941182
  StatusDisplay = "Accepted"
  Lang = "golang"
  QuestionId = 1031
  TitleSlug = "add-to-array-form-of-integer"
  Code = "func addToArrayForm(number1 []int, add int) []int {\n\tif add == 0 {\n\t\treturn number1\n\t}\n\tif len(number1) == 0 {\n\t\treturn convert(add)\n\t}\n\tnumber2 := convert(add)\n\tlength1, length2, carry := len(number1), len(number2), 0\n\thightest := length1\n\tif length2 > length1 {\n\t\thightest = length2\n\t}\n\tresult := make([]int, hightest)\n\tindex1, index2, indexResult := length1-1, 0, hightest-1\n\tfor {\n\t\tindex1Valid, index2Valid := index1 >= 0, index2 < length2\n\t\tif !index1Valid && !index2Valid && carry==0 {\n\t\t\tbreak\n\t\t}\n\t\tdigit1, digit2 := 0, 0\n\t\tif index1Valid {\n\t\t\tdigit1 = number1[index1]\n\t\t\tindex1--\n\t\t}\n\t\tif index2Valid {\n\t\t\tdigit2 = number2[index2]\n\t\t\tindex2++\n\t\t}\n\t\tdigitResult := digit1 + digit2 + carry\n\t\tif digitResult > 9 {\n\t\t\tcarry = 1\n\t\t\tdigitResult -= 10\n\t\t} else {\n\t\t\tcarry = 0\n\t\t}\n\t\tif indexResult == -1 {\n\t\t\tresult = append(result, 0)\n\t\t\tcopy(result[1:], result[0:hightest])\n            indexResult=0\n\t\t}\n\t\tresult[indexResult] = digitResult\n\t\tindexResult--\n\t}\n\treturn result\n}\n\nfunc convert(number int) (result []int) {\n\tfor {\n\t\tif number == 0 {\n\t\t\treturn\n\t\t}\n\t\tresult = append(result, number%10)\n\t\tnumber /= 10\n\t}\n}\n"
  Title = "Add to Array-Form of Integer"
  Url = "/submissions/detail/690941182/"
  LangName = "Go"
  Timestamp = 1651411438
  Status = 10
  Runtime = "64 ms"
  IsPending = "Not Pending"
  Memory = "7 MB"
  CompareResult = "11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
