load("//tools/bzl/main/bzl:al_bzl_library_map.bzl", "al_bzl_library_map")
load("//tools/docs:defs.bzl", "docs_filegroup")

al_bzl_library_map(
    name = "libs",
    libs = {
        "al_gzip_extension": [
            ":al_gzip_repo",
        ],
        "al_gzip_repo": [],
    },
    visibility = ["//:__subpackages__"],
)

docs_filegroup(
    name = "docs",
    srcs = glob(["*.md"]),
    visibility = ["//tools/gzip:__pkg__"],
    deps = [
        ":libs.stardoc",
    ],
)
