load("@rules_pkg//pkg:mappings.bzl", "pkg_filegroup")
load("//tools/docs:defs.bzl", "docs_filegroup")

docs_filegroup(
    name = "docs",
    srcs = glob(["*.md"]),
    prefix = "content/docs/misc/leetcode_submissions",
    visibility = ["//projects/alwaldend.com/content/docs/misc:__pkg__"],
    deps = [
        ":submissions",
    ],
)

pkg_filegroup(
    name = "submissions",
    srcs = [
        "//data/leetcode_submissions",
    ],
    prefix = "content/docs/misc/leetcode_submissions",
)
