note_id = 1520716967061
guid = "g>pVnev*}g"
note_type_id = 1496733135171
note_type = "chinese"
tags = ["Adverbs", "B1", "Parts_of_Speech"]

[[cards]]
id = 1520716972925
ordinal = 0

[fields]
article-title = 'Expressing "all along" with "yuanlai"'
english = 'So it was you all along!'
example-sentence = ''
example-type = ''
grammar-construct = '原来 + [New Information]'
hanzi = '原来是你！'
notes = ''
pinyin = 'Yuánlái shì nǐ!'
source = 'https://resources.allsetlearning.com/chinese/grammar/ASGTKXFR'
