[[Submissions]]
  Id = 1100028827
  StatusDisplay = "Accepted"
  Lang = "cpp"
  QuestionId = 1833
  TitleSlug = "find-the-highest-altitude"
  Code = "class Solution {\npublic:\n    int largestAltitude(vector<int>& gain) {\n        int att {0}, maxAtt {0};\n        for (int num : gain) {\n            att += num;\n            maxAtt = max(maxAtt, att);\n        }\n        return maxAtt;\n    }\n};"
  Title = "Find the Highest Altitude"
  Url = "/submissions/detail/1100028827/"
  LangName = "C++"
  Timestamp = 1700132790
  Status = 10
  Runtime = "0 ms"
  IsPending = "Not Pending"
  Memory = "8.4 MB"
  CompareResult = "11111111111111111111111111111111111111111111111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
