[[Submissions]]
  Id = 1015933091
  StatusDisplay = "Accepted"
  Lang = "python3"
  QuestionId = 97
  TitleSlug = "interleaving-string"
  Code = "class Solution:\n    def isInterleave(self, s1: str, s2: str, s3: str) -> bool:\n        length_1, length_2, length_3 = len(s1), len(s2), len(s3)\n        if length_1 + length_2 != length_3:\n            return False\n        \n        @cache\n        def dp(i_1: int, i_2: int, i_3: int) -> bool:\n            if i_3 == length_3:\n                return True\n\n            target = s3[i_3]\n            return (\n                i_1 != length_1 and s1[i_1] == target and dp(i_1 + 1, i_2, i_3 + 1)\n            ) or (\n                i_2 != length_2 and s2[i_2] == target and dp(i_1, i_2 + 1, i_3 + 1)\n            )\n\n        return dp(0, 0, 0)\n"
  Title = "Interleaving String"
  Url = "/submissions/detail/1015933091/"
  LangName = "Python3"
  Timestamp = 1691519262
  Status = 10
  Runtime = "44 ms"
  IsPending = "Not Pending"
  Memory = "17.4 MB"
  CompareResult = "1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
