[[Submissions]]
  Id = 1015823030
  StatusDisplay = "Accepted"
  Lang = "python3"
  QuestionId = 120
  TitleSlug = "triangle"
  Code = "class Solution:\n    def minimumTotal(self, triangle: List[List[int]]) -> int:\n        row_count = len(triangle)\n\n\n        @cache\n        def dp(row: int, column: int) -> int:\n            if row == row_count or column == row + 1:\n                return 0\n        \n            return triangle[row][column] + min(dp(row + 1, column), dp(row + 1, column + 1))\n\n        return dp(0, 0)"
  Title = "Triangle"
  Url = "/submissions/detail/1015823030/"
  LangName = "Python3"
  Timestamp = 1691512488
  Status = 10
  Runtime = "73 ms"
  IsPending = "Not Pending"
  Memory = "20.2 MB"
  CompareResult = "11111111111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
