note_id = 1520716969636
guid = "vVlA$p=#rH"
note_type_id = 1496733135171
note_type = "chinese"
tags = ["Adverbs", "B2", "Parts_of_Speech"]

[[cards]]
id = 1520716975500
ordinal = 0

[fields]
article-title = 'An additional step with "jin yi bu"'
english = 'Study your first foreign language well first, then you can take the next step and start a second foreign language.'
example-sentence = ''
example-type = ''
grammar-construct = 'Subj. + 进一步 + Verb'
hanzi = '先学好第一外语，再进一步学好第二外语。'
notes = ''
pinyin = ''
source = 'https://resources.allsetlearning.com/chinese/grammar/ASGET76G'
