load("@rules_docs//docs:defs.bzl", "docs_filegroup")
load("@rules_pkg//pkg:mappings.bzl", "pkg_filegroup", "pkg_files")

pkg_filegroup(
    name = "data",
    srcs = [
        ":git_info",
    ],
    prefix = "data",
    visibility = ["//projects/alwaldend.com:__pkg__"],
)

pkg_files(
    name = "git_info",
    srcs = ["//tools/git:git_info"],
    renames = {"//tools/git:git_info": "git_info.json"},
)

docs_filegroup(
    name = "docs",
    srcs = glob(["*.md"]),
    visibility = ["//projects/alwaldend.com:__pkg__"],
)
