load("@rules_docs//docs:defs.bzl", "docs_filegroup")
load("@rules_terraform//terraform:defs.bzl", "terraform_binary_map", "terraform_test_map")
load("//projects/al/rules/al:al_binary.bzl", "al_binary_run", "al_binary_run_test")

docs_filegroup(
    name = "docs",
    srcs = glob(["*.md"]),
    visibility = ["//infra/vault:__pkg__"],
    deps = subpackages(
        include = ["*"],
        allow_empty = True,
    ),
)

_PROVIDERS = [
    "@terraform_provider_hashicorp_local//:provider",
    "@terraform_provider_hashicorp_vault//:provider",
    "@terraform_provider_yandex_cloud_yandex//:provider",
]

_CONFIGS = ["//infra/vault:al"]

_RUN_ARGS = [
    "--plugin_label",
    "tf=main",
    "--plugin_label",
    "vault_env=default_default",
]

_DATA = glob([
    "*.tf",
    "approle_src_infra_openhands/*.tf",
    "approles/*/*.tf",
    "dns_access/*.tf",
]) + [
    "//data/ssl/alwaldend.com:ica1",
    "//data/ssl/alwaldend.com:simeonwarren",
    "//projects/tf_modules/backup_bucket",
    "//projects/tf_modules/tf_backend",
    "//projects/tf_modules/vault_approle",
    "//projects/tf_modules/vault_pki_ica",
    "//projects/tf_modules/vault_pki_server",
    "//projects/tf_modules/vault_oidc_provider",
    "//projects/tf_modules/vault_ssh_server_role",
    "//projects/tf_modules/vault_transit_key",
    "//infra/vault/tf/output",
    "//tools/vault/tf_backend",
    "//tools/vault/injector",
]

terraform_binary_map(
    name = "tf",
    data = _DATA,
    providers = _PROVIDERS,
    wrapper = al_binary_run,
    wrapper_kwargs = {
        "configs": _CONFIGS,
        "run_args": _RUN_ARGS,
    },
)

terraform_test_map(
    name = "tf_tests",
    data = _DATA,
    providers = _PROVIDERS,
    wrapper = al_binary_run_test,
    wrapper_kwargs = {
        "configs": _CONFIGS,
    },
)
