[[Submissions]]
  Id = 1232828272
  StatusDisplay = "Accepted"
  Lang = "golang"
  QuestionId = 129
  TitleSlug = "sum-root-to-leaf-numbers"
  Code = "/**\n * Definition for a binary tree node.\n * type TreeNode struct {\n *     Val int\n *     Left *TreeNode\n *     Right *TreeNode\n * }\n */\nfunc sumNumbers(root *TreeNode) int {\n    return dfs(root, 0)\n}\n\nfunc dfs(node *TreeNode, num int) int {\n    if node == nil {\n        return 0\n    }\n    if node.Left == nil && node.Right == nil {\n        return num * 10 + node.Val\n    }\n    return dfs(node.Left, num * 10 + node.Val) + dfs(node.Right, num * 10 + node.Val)\n}"
  Title = "Sum Root to Leaf Numbers"
  Url = "/submissions/detail/1232828272/"
  LangName = "Go"
  Timestamp = 1713163862
  Status = 10
  Runtime = "0 ms"
  IsPending = "Not Pending"
  Memory = "2.3 MB"
  CompareResult = "111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
