[project]
name = "com_alwaldend_src_py_tools"
version = "0.0.0"
requires-python = ">=3.10, <4"
dependencies = [
    "black",
    "mypy",
    "isort",
    "pre-commit",
    "flake8",
    "flake8-pyproject",
    "git-filter-repo",
    "pynput",
    "pyside6",
    "twine",
]
