[[Submissions]]
  Id = 1117200785
  StatusDisplay = "Accepted"
  Lang = "python3"
  QuestionId = 500
  TitleSlug = "keyboard-row"
  Code = "class Solution:\n    def findWords(self, words: List[str]) -> List[str]:\n        ans = []\n        rows = [\n            set(\"qwertyuiop\"),\n            set(\"asdfghjkl\"), \n            set(\"zxcvbnm\")\n        ]\n        for word in words:\n            for row in rows:\n                if len(row.union(word.lower())) == len(row):\n                    ans.append(word)\n                    break\n        return ans\n"
  Title = "Keyboard Row"
  Url = "/submissions/detail/1117200785/"
  LangName = "Python3"
  Timestamp = 1702297835
  Status = 10
  Runtime = "39 ms"
  IsPending = "Not Pending"
  Memory = "16.3 MB"
  CompareResult = "11111111111111111111111"
  HasNotes = false
  FlagType = 1
