[[Submissions]]
  Id = 1719185284
  StatusDisplay = "Accepted"
  Lang = "python3"
  QuestionId = 866
  TitleSlug = "rectangle-overlap"
  Code = "class Solution:\n    def isRectangleOverlap(self, rec1: List[int], rec2: List[int]) -> bool:\n        def intersect(p_left: int, p_right: int, q_left: int, q_right: int) -> bool:\n            return min(p_right, q_right) > max(p_left, q_left)\n        return (\n            intersect(rec1[0], rec1[2], rec2[0], rec2[2]) # width > 0 \n            and intersect(rec1[1], rec1[3], rec2[1], rec2[3]) # height > 0\n        )"
  Title = "Rectangle Overlap"
  Url = "/submissions/detail/1719185284/"
  LangName = "Python3"
  Timestamp = 1754030456
  Status = 10
  Runtime = "0 ms"
  IsPending = "Not Pending"
  Memory = "17.7 MB"
  CompareResult = "11111111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
