http_archive = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "dns_test_cloudflare",
    build_file_content = "exports_files([\"terraform-provider-cloudflare_v5.22.0\"], visibility = [\"//visibility:public\"])\nfilegroup(name = \"provider\", srcs = [\"terraform-provider-cloudflare_v5.22.0\"], visibility = [\"//visibility:public\"])",
    integrity = "sha256-zXZwFupzguOE5WD23bMCY37LG1Ps4VyTJgMgEO/+bDM=",
    urls = ["https://github.com/cloudflare/terraform-provider-cloudflare/releases/download/v5.22.0/terraform-provider-cloudflare_5.22.0_linux_amd64.zip"],
)

http_archive(
    name = "dns_test_proxmox",
    build_file_content = "exports_files([\"terraform-provider-proxmox_v3.0.2-rc07\"], visibility = [\"//visibility:public\"])\nfilegroup(name = \"provider\", srcs = [\"terraform-provider-proxmox_v3.0.2-rc07\"], visibility = [\"//visibility:public\"])",
    integrity = "sha256-9BXMb3NaOXH6rmrCQDSv257oM3PvjeGaljHBh9Wtx9s=",
    urls = ["https://github.com/Telmate/terraform-provider-proxmox/releases/download/v3.0.2-rc07/terraform-provider-proxmox_3.0.2-rc07_linux_amd64.zip"],
)

http_archive(
    name = "dns_test_routeros",
    build_file_content = "exports_files([\"terraform-provider-routeros_v1.99.1\"], visibility = [\"//visibility:public\"])\nfilegroup(name = \"provider\", srcs = [\"terraform-provider-routeros_v1.99.1\"], visibility = [\"//visibility:public\"])",
    integrity = "sha256-reKesm06b2/1BzApCG7nijs1M6/AQU8S3zdGcRNY5Rs=",
    urls = ["https://github.com/terraform-routeros/terraform-provider-routeros/releases/download/v1.99.1/terraform-provider-routeros_1.99.1_linux_amd64.zip"],
)
