note_id = 1520716969961
guid = "H%Ek@|@Y-v"
note_type_id = 1496733135171
note_type = "chinese"
tags = ["B2", "Parts_of_Speech", "Prepositions"]

[[cards]]
id = 1520716975825
ordinal = 0

[fields]
article-title = 'Expressing "along with…" with "suizhe"'
english = 'Children started dancing with the music.'
example-sentence = ''
example-type = ''
grammar-construct = 'Subj. + 随着 + Noun + Verb Phrase'
hanzi = '孩子们随着音乐跳起了舞。'
notes = ''
pinyin = ''
source = 'https://resources.allsetlearning.com/chinese/grammar/ASGHVFRA'
