load("@rules_pkg//pkg:mappings.bzl", "pkg_files")
load("//tools/docs:defs.bzl", "docs_filegroup")

docs_filegroup(
    name = "docs",
    srcs = glob(["*.md"]),
    visibility = ["//data:__pkg__"],
    deps = [":docs_keys"] + subpackages(
        include = ["*"],
        allow_empty = True,
    ),
)

pkg_files(
    name = "docs_keys",
    srcs = [":ssh"],
    prefix = "content/docs/{}".format(package_name()),
)

filegroup(
    name = "ssh",
    srcs = [
        ":ca_clients",
        ":ca_servers",
        ":simeonwarren",
    ],
)

alias(
    name = "ca_clients",
    actual = "//infra/vault/tf/output:ssh_ca_clients",
    visibility = ["//:__subpackages__"],
)

alias(
    name = "ca_servers",
    actual = "//infra/vault/tf/output:ssh_ca_servers",
    visibility = ["//:__subpackages__"],
)

filegroup(
    name = "simeonwarren",
    srcs = ["simeonwarren@alwaldend.com-2026-03-22-openpgp.pub"],
    visibility = ["//:__subpackages__"],
)
