note_id = 1520716968770
guid = "OknqAkdzw%"
note_type_id = 1496733135171
note_type = "chinese"
tags = ["B1", "Grammatical_Structures", "SentencePatterns"]

[[cards]]
id = 1520716974634
ordinal = 0

[fields]
article-title = 'Expressing "every" with question words'
english = 'Is it OK if I do however I want?'
example-sentence = ''
example-type = ''
grammar-construct = '怎么 + Verb + 都 + Predicate'
hanzi = '怎么做都可以吗？'
notes = ''
pinyin = 'Zěnme zuò dōu kěyǐ ma?'
source = 'https://resources.allsetlearning.com/chinese/grammar/ASG13ALM'
