note_id = 1634436716371
guid = "Aej_m<5vY^"
note_type_id = 1630447360003
note_type = "python-basic-and-reversed"
tags = []

[[cards]]
id = 1634436716372
ordinal = 0

[fields]
additional-info = '<strong>Note:</strong>&nbsp;All string methods returns new values. They do not change the original string.'
answer = '<i>string</i>.isdecimal()'
example = ''
question = '<b>String method</b>&nbsp;that returns True if the string can be converted to a decimal number, else False.'
version = ''
with-options = ''
