note_id = 1654615139998
guid = "C.f;+UpGI("
note_type_id = 1630447360003
note_type = "python-basic-and-reversed"
tags = []

[[cards]]
id = 1654615139999
ordinal = 0

[fields]
additional-info = """


<strong>Note:</strong>&nbsp;All string methods returns new values. They do not change the original string.\
"""
answer = '<b>String</b> <b>method</b>&nbsp;that&nbsp;decodes the string using the codec registered for the&nbsp;<i>encoding </i>argument.'
example = ''
question = '<i>string</i>.decode()'
version = ''
with-options = '<i>string</i>.decode(<span style="color: var(--field-fg); background: var(--field-bg);"><i>encoding</i>=“UTF-8”,&nbsp;<i>errors</i>=“strict”)&nbsp;</span><br>'
