[[Submissions]]
  Id = 1030523976
  StatusDisplay = "Accepted"
  Lang = "python3"
  QuestionId = 373
  TitleSlug = "find-k-pairs-with-smallest-sums"
  Code = "class Solution:\n    def kSmallestPairs(self, nums1: List[int], nums2: List[int], k: int) -> List[List[int]]:\n        nums1_count, nums2_count = len(nums1), len(nums2)\n        result = []\n        visited = set(((0, 0)))\n        min_heap = [(nums1[0] + nums2[0], (0, 0))]\n        count = 0\n\n        while k > 0 and min_heap:\n            _, (i, j) = heappop(min_heap)\n            new_i, new_j = i + 1, j + 1\n            new_pair1, new_pair2 = (new_i, j), (i, new_j)\n            num1, num2 = nums1[i], nums2[j]\n            result.append((num1, num2))\n\n            if new_i < nums1_count and new_pair1 not in visited:\n                heappush(min_heap, (nums1[new_i] + num2, new_pair1))\n                visited.add(new_pair1)\n\n            if new_j < nums2_count and new_pair2 not in visited:\n                heappush(min_heap, (num1 + nums2[new_j], new_pair2))\n                visited.add(new_pair2)\n\n            k -= 1\n        \n        return result"
  Title = "Find K Pairs with Smallest Sums"
  Url = "/submissions/detail/1030523976/"
  LangName = "Python3"
  Timestamp = 1692884527
  Status = 10
  Runtime = "930 ms"
  IsPending = "Not Pending"
  Memory = "36.5 MB"
  CompareResult = "111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
