title = "Alwaldend"
theme = ["github.com/google/docsy"]
baseURL = "http://127.0.0.1:1313"
# refLinksErrorLevel = "WARNING"

enableRobotsTXT = true

[outputs]
section = ["html", "rss", "print"]
home = ["html"]
page = ["html", "rss"]

[frontmatter]
lastmod = [":fileModTime"]

[sitemap]
changefreq = "daily"
priority = 0.5

[params]
offlineSearch = true
github_repo = "https://github.com/alwaldend/src"
github_branch = "master"
version_menu = "Versions"
version_menu_pagelinks = true

[[params.alwaldend.links]]
name = "Docs"
url = "https://alwaldend.com/docs/"

[[params.alwaldend.links]]
name = "Github"
url = "https://github.com/alwaldend/src/"

# [params.copyright]
# authors = ""

[params.ui]
navbar_logo = false
generated_tags = ["Generated"]
separate_page_tags = ["Bzl-Targets", "Changelog"]
showLightDarkModeMenu = true
sidebar_menu_compact = true
sidebar_menu_foldable = true

[params.drawio]
enable = true

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.renderHooks.link]
useEmbedded = "always"

[markup.goldmark.parser.attribute]
block = true
title = true

[taxonomies]
category = "categories"
language = "languages"
status = "statuses"
tag = "tags"
site = "websites"

[[menus.main]]
name = "Docs"
weight = 100
url = "/docs/"

[[menus.main]]
name = "Projects"
weight = 200
url = "/projects/"

[security.exec]
# allow = [".*"]
# osEnv = [".*"]
# osEnv = [
#     # '(?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM|GO\w+|(XDG_CONFIG_)?HOME|USERPROFILE|SSH_AUTH_SOCK|DISPLAY|LANG|SYSTEMDRIVE|PROGRAMDATA)$',
#     '(?i)^(BAZEL_.+)$',
# ] # extra env for postcss

[security.funcs]
# getenv = [".*"]

[module.hugoVersion]
extended = true
min = "0.160.1"

[module]
[[module.mounts]]
source = "themes/github.com/twbs/bootstrap/scss"
target = "assets/vendor/bootstrap/scss"
[[module.mounts]]
source = "themes/github.com/twbs/bootstrap/js"
target = "assets/vendor/bootstrap/js"
[[module.mounts]]
source = "themes/github.com/twbs/bootstrap/dist"
target = "assets/vendor/bootstrap/dist"
[[module.mounts]]
source = "themes/github.com/FortAwesome/Font-Awesome/scss"
target = "assets/vendor/Font-Awesome/scss"
[[module.mounts]]
source = "themes/github.com/FortAwesome/Font-Awesome/webfonts"
target = "static/webfonts"
