[[Submissions]]
  Id = 689722001
  StatusDisplay = "Accepted"
  Lang = "golang"
  QuestionId = 14
  TitleSlug = "longest-common-prefix"
  Code = "\nimport \"fmt\"\n\n\nfunc substrings(input string) map[string]bool {\n\tresults := make(map[string]bool)\n\tfor index := range input {\n\t\tresults[string(input[0:index+1])] = true\n\t}\n\treturn results\n}\n\nfunc string_in_maps(\n\tsource map[string]bool,\n\ttarget map[string]bool,\n\tresults map[string]bool) {\n\tfor string := range source {\n\t\tif result, exists_in_results := results[string]; exists_in_results && !result {\n\t\t\tcontinue\n\t\t}\n\t\t_, exists_in_target := target[string]\n\t\tresults[string] = exists_in_target\n\t}\n}\n\nfunc longestCommonPrefix(strings []string) (result string) {\n\tresults := make(map[string]bool)\n\tprevious := make(map[string]bool)\n\tfor index, string := range strings {\n\t\tcurrent := substrings(string)\n\t\tif index == 0 {\n\t\t\tprevious = current\n\t\t}\n\t\tstring_in_maps(current, previous, results)\n\t\tstring_in_maps(previous, current, results)\n\t\tfmt.Println(\"current string\", string, current, \"results\", results)\n\t\tprevious = current\n\t}\n\tfor string, valid := range results {\n\t\tif !valid || len(string) < len(result) {\n\t\t\tcontinue\n\t\t}\n\t\tif len(string) == len(result) && string < result {\n\t\t\tresult = string\n\t\t\tcontinue\n\t\t}\n\t\tresult = string\n\t}\n\tfmt.Println(\"result\", result)\n\treturn\n}\n\n"
  Title = "Longest Common Prefix"
  Url = "/submissions/detail/689722001/"
  LangName = "Go"
  Timestamp = 1651244942
  Status = 10
  Runtime = "86 ms"
  IsPending = "Not Pending"
  Memory = "6.9 MB"
  CompareResult = "111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
