[[Submissions]]
  Id = 689740949
  StatusDisplay = "Accepted"
  Lang = "golang"
  QuestionId = 14
  TitleSlug = "longest-common-prefix"
  Code = "\nfunc substrings(input string) map[string]bool {\n\tresults := make(map[string]bool)\n\tfor index := range input {\n\t\tresults[input[0:index+1]] = true\n\t}\n\treturn results\n}\n\nfunc string_in_maps(\n\tsource map[string]bool,\n\ttarget map[string]bool,\n\tresults map[string]bool) {\n\tfor string := range source {\n\t\tis_valid, exists_in_results := results[string]\n\t\t_, exists_in_target := target[string]\n\t\tswitch {\n\t\tcase !exists_in_target:\n\t\t\tfallthrough\n\t\tcase exists_in_target && (is_valid || !exists_in_results):\n\t\t\tresults[string] = exists_in_target\n\t\t}\n\t}\n}\n\nfunc longestCommonPrefix(strings []string) (result string) {\n\tresults := make(map[string]bool)\n\tvar previous map[string]bool\n\tfor index, string := range strings {\n\t\tcurrent := substrings(string)\n\t\tif index == 0 {\n\t\t\tprevious = current\n\t\t}\n\t\tstring_in_maps(previous, current, results)\n\t\tstring_in_maps(current, previous, results)\n\t\tprevious = current\n\t}\n\tfor string, valid := range results {\n\t\tif valid && len(string) > len(result) {\n\t\t\tresult = string\n\t\t}\n\t}\n\treturn\n}\n\n"
  Title = "Longest Common Prefix"
  Url = "/submissions/detail/689740949/"
  LangName = "Go"
  Timestamp = 1651247464
  Status = 10
  Runtime = "33 ms"
  IsPending = "Not Pending"
  Memory = "6.5 MB"
  CompareResult = "111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
