load("@com_alwaldend_src_npm//tools:prettier/package_json.bzl", prettier = "bin")
load("//tools/docs:defs.bzl", "docs_filegroup")

prettier.prettier_binary(
    name = "prettier",
    visibility = ["//:__subpackages__"],
)

docs_filegroup(
    name = "docs",
    srcs = glob(["*.md"]),
    visibility = ["//tools:__pkg__"],
)
