[[Submissions]]
  Id = 1240750456
  StatusDisplay = "Accepted"
  Lang = "golang"
  QuestionId = 1236
  TitleSlug = "n-th-tribonacci-number"
  Code = "func tribonacci(n int) int {\n\tif n < 2 {\n\t\treturn n\n\t}\n\n\tdp := []int{0, 1, 1}\n\n\tfor i := 3; i <= n; i++ {\n\t\tnext := dp[0] + dp[1] + dp[2]\n\t\tdp[0], dp[1], dp[2] = dp[1], dp[2], next\n\t}\n\n\treturn dp[2]\n}"
  Title = "N-th Tribonacci Number"
  Url = "/submissions/detail/1240750456/"
  LangName = "Go"
  Timestamp = 1713960372
  Status = 10
  Runtime = "1 ms"
  IsPending = "Not Pending"
  Memory = "2.1 MB"
  CompareResult = "111111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
