[[Submissions]]
  Id = 1018260045
  StatusDisplay = "Accepted"
  Lang = "python3"
  QuestionId = 518
  TitleSlug = "coin-change-ii"
  Code = "class Solution:\n    def change(self, amount: int, coins: List[int]) -> int:\n        n = len(coins)\n        dp = [[0] * (amount + 1) for _ in range(n + 1)]\n        for i in range(n):\n            dp[i][0] = 1\n\n        for i in range(n - 1, -1, -1):\n            for j in range(1, amount + 1):\n                if coins[i] > j:\n                    dp[i][j] = dp[i + 1][j]\n                else:\n                    dp[i][j] = dp[i + 1][j] + dp[i][j - coins[i]]\n\n        return dp[0][amount]"
  Title = "Coin Change II"
  Url = "/submissions/detail/1018260045/"
  LangName = "Python3"
  Timestamp = 1691741855
  Status = 10
  Runtime = "270 ms"
  IsPending = "Not Pending"
  Memory = "25.9 MB"
  CompareResult = "1111111111111111111111111111"
  HasNotes = false
  FlagType = 1
