[[Submissions]]
  Id = 1052579467
  StatusDisplay = "Accepted"
  Lang = "python3"
  QuestionId = 2413
  TitleSlug = "smallest-number-in-infinite-set"
  Code = "class SmallestInfiniteSet:\n\n    def __init__(self):\n        self.heap, self.next_num, self.nums = [], 1, set() \n\n\n    def popSmallest(self) -> int:\n        if not self.heap:\n            self.next_num += 1\n            return self.next_num - 1\n            \n        val = heappop(self.heap)\n        if val < self.next_num:\n            self.nums.remove(val)\n            return val\n        heappush(self.heap, val)\n        self.next_num += 1\n        return self.next_num - 1\n        \n\n    def addBack(self, num: int) -> None:\n        if num in self.nums or num >= self.next_num:\n            return\n        self.nums.add(num)\n        heappush(self.heap, num)\n\n\n# Your SmallestInfiniteSet object will be instantiated and called as such:\n# obj = SmallestInfiniteSet()\n# param_1 = obj.popSmallest()\n# obj.addBack(num)"
  Title = "Smallest Number in Infinite Set"
  Url = "/submissions/detail/1052579467/"
  LangName = "Python3"
  Timestamp = 1695038356
  Status = 10
  Runtime = "109 ms"
  IsPending = "Not Pending"
  Memory = "16.9 MB"
  CompareResult = "111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
