note_id = 1520716967204
guid = "L9bxWX4!$>"
note_type_id = 1496733135171
note_type = "chinese"
tags = ["Adverbs", "B1", "Parts_of_Speech"]

[[cards]]
id = 1520716973068
ordinal = 0

[fields]
article-title = 'Expressing "in this way" with "zheyang"'
english = 'You should let him do it by himself. Only in this way can he learn.'
example-sentence = ''
example-type = ''
grammar-construct = 'Condition, 这样 + Result / Purpose'
hanzi = '你要让他自己做，只有这样他才能学会。'
notes = ''
pinyin = 'Nǐ yào ràng tā zìjǐ zuò, zhǐyǒu zhèyàng tā cái néng xuéhuì.'
source = 'https://resources.allsetlearning.com/chinese/grammar/ASG1F4D1'
