[[Submissions]]
  Id = 1053766402
  StatusDisplay = "Accepted"
  Lang = "python3"
  QuestionId = 287
  TitleSlug = "find-the-duplicate-number"
  Code = "class Solution:\n    def findDuplicate(self, nums: List[int]) -> int:\n        freqs = [0] * (10**5 + 1)\n        for num in nums:\n            freqs[num] += 1\n            if freqs[num] > 1:\n                return num\n\n        raise Exception()"
  Title = "Find the Duplicate Number"
  Url = "/submissions/detail/1053766402/"
  LangName = "Python3"
  Timestamp = 1695142717
  Status = 10
  Runtime = "486 ms"
  IsPending = "Not Pending"
  Memory = "30.8 MB"
  CompareResult = "1111111111111111111111111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
