note_id = 1520716970077
guid = "EaeY9X*#wr"
note_type_id = 1496733135171
note_type = "chinese"
tags = ["B2", "Parts_of_Speech", "Verbs"]

[[cards]]
id = 1520716975941
ordinal = 0

[fields]
article-title = 'Making "-ize" and "-ify" verbs with "hua"'
english = 'You should allow the butter to soften, then eat it with bread.'
example-sentence = ''
example-type = ''
grammar-construct = 'Noun / Adj. + 化'
hanzi = '你应该让黄油软化，然后跟面包一起吃。'
notes = ''
pinyin = ''
source = 'https://resources.allsetlearning.com/chinese/grammar/ASGS6UKN'
