note_id = 1520716970071
guid = "zIl?x-Lph;"
note_type_id = 1496733135171
note_type = "chinese"
tags = ["B2", "Parts_of_Speech", "Verbs"]

[[cards]]
id = 1520716975935
ordinal = 0

[fields]
article-title = 'Making "-ize" and "-ify" verbs with "hua"'
english = "KFC's Chinese localization has been implemented very successfully."
example-sentence = ''
example-type = ''
grammar-construct = 'Noun / Adj. + 化'
hanzi = 'KFC的中国本土化经营做得非常成功。'
notes = ''
pinyin = ''
source = 'https://resources.allsetlearning.com/chinese/grammar/ASGS6UKN'
