note_id = 1520716969074
guid = "OJVlimgH~2"
note_type_id = 1496733135171
note_type = "chinese"
tags = ["B1", "Grammatical_Structures", "SentencePatterns"]

[[cards]]
id = 1520716974938
ordinal = 0

[fields]
article-title = 'Using the "shi... de" construction'
english = "This phone call isn't to him."
example-sentence = ''
example-type = ''
grammar-construct = 'Subj. + 是 + [Information to be Emphasized] + Verb + 的'
hanzi = '这个电话不是打给他的。'
notes = ''
pinyin = 'Zhège diànhuà bù shì dǎ gěi tā de.'
source = 'https://resources.allsetlearning.com/chinese/grammar/ASG8YTSF'
