[[Submissions]]
  Id = 1036785038
  StatusDisplay = "Accepted"
  Lang = "python3"
  QuestionId = 1451
  TitleSlug = "minimum-number-of-taps-to-open-to-water-a-garden"
  Code = "class Solution:\n    def minTaps(self, n: int, ranges: List[int]) -> int:\n        inf = float(\"inf\")\n        dp = [inf] * (n + 1)\n        dp[0] = 0\n        \n        for i in range(n + 1):\n            cur_range = ranges[i]\n            tap_start, tap_end = max(0, i - cur_range), min(n, i + cur_range)\n            \n            for j in range(tap_start, tap_end + 1):\n                dp[tap_end] = min(dp[tap_end], dp[j] + 1)\n        \n        min_taps = dp[n]\n        return -1 if min_taps == inf else min_taps "
  Title = "Minimum Number of Taps to Open to Water a Garden"
  Url = "/submissions/detail/1036785038/"
  LangName = "Python3"
  Timestamp = 1693484983
  Status = 10
  Runtime = "458 ms"
  IsPending = "Not Pending"
  Memory = "16.5 MB"
  CompareResult = "11111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
