load("@rules_docs//docs:defs.bzl", "docs_filegroup")
load("@rules_terraform//terraform:defs.bzl", "terraform_binary_map", "terraform_target_binary_map", "terraform_test_map")
load("//projects/al/rules/al:al_binary.bzl", "al_binary_run", "al_binary_run_test")

docs_filegroup(
    name = "docs",
    srcs = glob(["*.md"]),
    visibility = ["//projects/alwaldend.com:__pkg__"],
    deps = subpackages(
        include = ["*"],
        allow_empty = True,
    ),
)

genrule(
    name = "update_pve_disk",
    srcs = ["//projects/alwaldend.com/cmd/server:ops"],
    outs = ["update_pve_disk.sh"],
    cmd = """
target=/var/lib/vz/template/iso/alwaldend.com-server.iso
src=$(execpath //projects/alwaldend.com/cmd/server:ops)
pve=host1.pve1.dc1.alwaldend.com
cat - >$(@) <<EOF
#!/usr/bin/env sh
set -eu
scp "$${src}" "$${pve}:$${target}"
ssh "$${pve}" chmod 600 "$${target}"
for vmid in 900; do
    ssh "$${pve}" -- "
        sudo qm stop '\\$${vmid}'
        sudo qm set '\\$${vmid}' --scsi0 'local-lvm:0,import-from=$${target}'
        sudo qm start '\\$${vmid}'
    "
done
EOF
chmod u+x $(@)
""",
    executable = True,
)

_PROVIDERS = [
    "@terraform_provider_cloudflare_cloudflare//:provider",
    "@terraform_provider_telmate_proxmox//:provider",
]

_CONFIGS = ["//projects/alwaldend.com:al"]

_RUN_ARGS = [
    "--plugin_label",
    "tf=main",
]

_DATA = glob(["*.tf"]) + [
    "//projects/alwaldend.com:dnsconfig",
    "//projects/tf_modules/dns_records/global:global",
    "//tools/vault/pve_login",
    "//tools/vault/tf_backend",
    "//tools/vault/injector",
]

terraform_binary_map(
    name = "tf",
    data = _DATA,
    providers = _PROVIDERS,
    wrapper = al_binary_run,
    wrapper_kwargs = {
        "configs": _CONFIGS,
        "run_args": _RUN_ARGS,
    },
)

terraform_target_binary_map(
    name = "dns",
    data = _DATA,
    providers = _PROVIDERS,
    target = "module.dns",
    wrapper = al_binary_run,
    wrapper_kwargs = {
        "configs": _CONFIGS,
        "run_args": [
            "--plugin_label",
            "dns=1",
        ],
    },
)

terraform_test_map(
    name = "tf_tests",
    data = _DATA,
    providers = _PROVIDERS,
    wrapper = al_binary_run_test,
    wrapper_kwargs = {
        "configs": _CONFIGS,
    },
)
