load("@rules_docs//docs:defs.bzl", "docs_filegroup")
load("//projects/al/rules/al:al_config.bzl", "al_config")
load("//tools/vault:defs.bzl", "vault_binary_map")

docs_filegroup(
    name = "docs",
    srcs = glob(["*.md"]) + ["arch.drawio.svg"],
    visibility = [
        "//projects:__pkg__",
        "//projects/ci_platform/landing:__pkg__",
    ],
    deps = [
        "//projects/ci_platform/releases:docs",
        "//projects/ci_platform/tf:docs",
    ],
)

filegroup(
    name = "dnsconfig",
    srcs = ["dnsconfig.json"],
    visibility = [
        "//infra:__pkg__",
        "//infra/dns:__pkg__",
        "//projects/alwaldend.com:__subpackages__",
        "//projects/ci_platform/tf:__pkg__",
    ],
)

al_config(
    name = "al",
    srcs = ["al.lua"],
    visibility = ["//projects/ci_platform/tf:__pkg__"],
    deps = ["//infra:al"],
)

vault_binary_map(
    name = "vault",
    configs = [":al"],
)
