- name: Phone setup
  hosts: laptop1
  become: true
  tags:
    - phone
  tasks:
    - name: Generate wireguard config for the phone
      vars:
        wg_interface: phone1 
        wg_peers: "{{ hostvars.phone1.wg_peers }}"
        wg_interface_config: "{{ hostvars.phone1.wg_interface_config }}"
      ansible.builtin.template:
        dest: "{{ hostvars.phone1.wg_dir }}/{{ hostvars.phone1.wg_interface }}.conf"
        src: "roles/wireguard/templates/wireguard.conf.j2"
        owner: "root"
        group: "root"
        mode: "600" 
