note_id = 1520716970003
guid = "J^)oSzN4hY"
note_type_id = 1496733135171
note_type = "chinese"
tags = ["B2", "Parts_of_Speech", "Prepositions"]

[[cards]]
id = 1520716975867
ordinal = 0

[fields]
article-title = 'Expressing passive voice with "gei"'
english = 'The water here is all polluted.'
example-sentence = ''
example-type = ''
grammar-construct = 'Receiver + 给 + The Doer + Verb Phrase'
hanzi = '这里的水都给污染了。'
notes = ''
pinyin = ''
source = 'https://resources.allsetlearning.com/chinese/grammar/ASGEZ2HN'
