load("@rules_docs//docs:defs.bzl", "docs_filegroup")
load("@rules_pkg//pkg:mappings.bzl", "pkg_files")
load("//tools/vial/main/bzl:al_vial_configs.bzl", "al_vial_configs")

pkg_files(
    name = "vial",
    srcs = glob(["*.json"]),
    visibility = ["//projects/dotfiles/releases:__pkg__"],
)

al_vial_configs(
    name = "generated_docs",
    srcs = glob(["*.json"]),
)

docs_filegroup(
    name = "docs",
    srcs = glob(["*.md"]),
    visibility = ["//projects/dotfiles:__pkg__"],
    deps = [":generated_docs"],
)
