note_id = 1520716968966
guid = "DJS<e<!@51"
note_type_id = 1496733135171
note_type = "chinese"
tags = ["B1", "Grammatical_Structures", "SentencePatterns"]

[[cards]]
id = 1520716974830
ordinal = 0

[fields]
article-title = 'Expressing comparable degree with "you"'
english = 'Are you as busy as the boss?'
example-sentence = ''
example-type = ''
grammar-construct = 'A + 有 + B + Adj. + 吗 ？'
hanzi = '你有老板忙吗？'
notes = ''
pinyin = 'Nǐ yǒu lǎobǎn máng ma?'
source = 'https://resources.allsetlearning.com/chinese/grammar/ASG5DG95'
