load("@rules_docs//docs:defs.bzl", "docs_filegroup")
load("@rules_terraform//terraform:defs.bzl", "terraform_binary_map", "terraform_test_map")
load("//projects/al/rules/al:al_binary.bzl", "al_binary_run", "al_binary_run_test")

docs_filegroup(
    name = "docs",
    srcs = ["README.md"],
    visibility = ["//projects/infinitime:__pkg__"],
)

_PROVIDERS = [
    "@terraform_provider_cloudflare_cloudflare//:provider",
]

_CONFIGS = ["//projects/infinitime:al"]

_RUN_ARGS = [
    "--plugin_label",
    "tf=main",
]

_DATA = glob(["*.tf"]) + [
    "//projects/infinitime:dnsconfig",
    "//projects/tf_modules/dns_records/global:global",
    "//tools/vault/injector",
    "//tools/vault/tf_backend",
]

terraform_binary_map(
    name = "tf",
    data = _DATA,
    providers = _PROVIDERS,
    wrapper = al_binary_run,
    wrapper_kwargs = {
        "configs": _CONFIGS,
        "run_args": _RUN_ARGS,
    },
)

terraform_test_map(
    name = "tf_tests",
    data = _DATA,
    providers = _PROVIDERS,
    wrapper = al_binary_run_test,
    wrapper_kwargs = {
        "configs": _CONFIGS,
    },
)
