note_id = 1520716968191
guid = "Ic,d*;Hd9y"
note_type_id = 1496733135171
note_type = "chinese"
tags = ["B1", "Parts_of_Speech", "Verbs"]

[[cards]]
id = 1520716974055
ordinal = 0

[fields]
article-title = 'Making judgments with "suan"'
english = "He's only 1.75 meter. He can't be considered to be very tall."
example-sentence = ''
example-type = ''
grammar-construct = 'Subj. + 不 + 算 (+ Adv.) + Adj.'
hanzi = '他才一米七五，不算很高。'
notes = ''
pinyin = 'Tā cái yī mǐ qīwǔ, bù suàn hěn gāo.'
source = 'https://resources.allsetlearning.com/chinese/grammar/ASGWDWFN'
