[[Submissions]]
  Id = 1089803621
  StatusDisplay = "Accepted"
  Lang = "golang"
  QuestionId = 2347
  TitleSlug = "count-nodes-equal-to-average-of-subtree"
  Code = "/**\n * Definition for a binary tree node.\n * type TreeNode struct {\n *     Val int\n *     Left *TreeNode\n *     Right *TreeNode\n * }\n */\nfunc averageOfSubtree(root *TreeNode) int {\n    _, _, answer := getAverage(root)\n    return answer\n}\n\nfunc getAverage(root *TreeNode) (int, int, int) {\n    if root == nil {\n        return 0, 0, 0\n    }\n    sum, count, validNodes := root.Val, 1, 0\n    leftSum, leftCount, leftValidNodes := getAverage(root.Left)\n    rightSum, rightCount, rightValidNodes := getAverage(root.Right)\n    validNodes += leftValidNodes + rightValidNodes\n    sum += leftSum + rightSum\n    count += leftCount + rightCount\n    if sum / count == root.Val {\n        validNodes += 1\n    }\n    return sum, count, validNodes\n}"
  Title = "Count Nodes Equal to Average of Subtree"
  Url = "/submissions/detail/1089803621/"
  LangName = "Go"
  Timestamp = 1698921166
  Status = 10
  Runtime = "5 ms"
  IsPending = "Not Pending"
  Memory = "4.3 MB"
  CompareResult = "111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
