load("@rules_docs//docs:defs.bzl", "docs_filegroup")
load("@rules_terraform//terraform:defs.bzl", "terraform_binary_map")
load("//projects/al/rules/al:al_binary.bzl", "al_binary_run")
load("//projects/al/rules/al:al_config.bzl", "al_config")

al_config(
    name = "config",
    srcs = ["//:al.lua"],
    data = [
        "//:al_lib.lua",
        "//data/ssl/alwaldend.com:ica_servers",
    ],
    visibility = ["//:__subpackages__"],
)

terraform_binary_map(
    name = "tf",
    chdir = ".",
    visibility = ["//:__pkg__"],
    wrapper = al_binary_run,
    wrapper_kwargs = {"configs": [":config"]},
)

docs_filegroup(
    name = "docs",
    srcs = ["README.md"],
    visibility = ["//tools:__pkg__"],
)
