[[Submissions]]
  Id = 1123253523
  StatusDisplay = "Accepted"
  Lang = "python3"
  QuestionId = 661
  TitleSlug = "image-smoother"
  Code = "class Solution:\n    def imageSmoother(self, img: List[List[int]]) -> List[List[int]]:\n        # Save the dimensions of the image.\n        m = len(img)\n        n = len(img[0])\n\n        # Create a new image of the same dimension as the input image.\n        smooth_img = [[0] * n for _ in range(m)]\n\n        # Iterate over the cells of the image.\n        for i in range(m):\n            for j in range(n):\n                # Initialize the sum and count \n                sum = 0\n                count = 0\n\n                # Iterate over all plausible nine indices.\n                for x in (i - 1, i, i + 1):\n                    for y in (j - 1, j, j + 1):\n                        # If the indices form valid neighbor\n                        if 0 <= x < m and 0 <= y < n:\n                            sum += img[x][y]\n                            count += 1\n\n                # Store the rounded down value in smooth_img[i][j].\n                smooth_img[i][j] = sum // count\n        \n        # Return the smooth image.\n        return smooth_img"
  Title = "Image Smoother"
  Url = "/submissions/detail/1123253523/"
  LangName = "Python3"
  Timestamp = 1702974287
  Status = 10
  Runtime = "463 ms"
  IsPending = "Not Pending"
  Memory = "17.1 MB"
  CompareResult = "11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
