load("@rules_docs//docs:defs.bzl", "docs_filegroup")
load("@rules_go//go:def.bzl", "go_binary", "go_library")

docs_filegroup(
    name = "docs",
    srcs = [],
    visibility = ["//tools/ansible:__pkg__"],
    deps = subpackages(
        include = ["*"],
        allow_empty = True,
    ),
)

go_library(
    name = "lint_lib",
    srcs = ["main.go"],
    importpath = "git.alwaldend.com/alwaldend/src/tools/ansible/lint",
    deps = ["@rules_go//go/tools/bazel"],
)

alias(
    name = "ansible_lint_runner",
    actual = ":ansible_lint_test",
    visibility = ["//:__subpackages__"],
)

go_binary(
    name = "ansible_lint_test",
    embed = [":lint_lib"],
    visibility = ["//:__subpackages__"],
)
