[[Submissions]]
  Id = 692355461
  StatusDisplay = "Accepted"
  Lang = "golang"
  QuestionId = 35
  TitleSlug = "search-insert-position"
  Code = "func searchInsert(numbers []int, target int) int {\n\t// checking edge cases\n\tlength := len(numbers)\n\tif numbers[0] == target {\n\t\treturn 0\n\t} else if numbers[length-1] == target {\n\t\treturn length - 1\n\t}\n\tleft, right, index, was_bigger := 0, length-1, 0, false\n\tfor right >= left {\n\t\t// overflow protection\n\t\tindex = left + (right-left)/2\n\t\tnumber := numbers[index]\n\t\t//fmt.Println(\"index\", index, \"left\", left, \"right\", right)\n\t\tswitch {\n\t\tcase number == target:\n\t\t\t// found the target\n\t\t\treturn index\n\t\tcase number > target:\n\t\t\t// the number is bigger -> the target is to the left -> discard right\n\t\t\tright = index - 1\n\t\t\twas_bigger = true\n\t\tcase number < target:\n\t\t\t// the number is smaller -> the target is to the right -> discard left\n\t\t\tleft = index + 1\n\t\t\twas_bigger = false\n\t\t}\n\t}\n\t// the target is not in the array\n\n\t// the last number was bigger -> target should be to the left\n\tif was_bigger {\n\t\treturn index\n\t}\n\t// the last number was smaller -> target should be to the right\n\treturn index + 1\n}\n"
  Title = "Search Insert Position"
  Url = "/submissions/detail/692355461/"
  LangName = "Go"
  Timestamp = 1651589069
  Status = 10
  Runtime = "3 ms"
  IsPending = "Not Pending"
  Memory = "3 MB"
  CompareResult = "1111111111111111111111111111111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
