load("@com_alwaldend_src_tools_terraform//:defs.bzl", "terraform_binary")
load("@rules_docs//docs:defs.bzl", "docs_filegroup")
load("@rules_shell//shell:sh_test.bzl", "sh_test")
load(":defs.bzl", "terraform_test_map")
load(":defs_test.bzl", "terraform_test_map_test")

exports_files(["agent_operations.json"])

sh_test(
    name = "explicit_operations_test",
    srcs = ["explicit_operations_test.sh"],
    args = ["$(location defs.bzl)"],
    data = ["defs.bzl"],
)

terraform_binary(
    name = "fixture_terraform",
    testonly = True,
    tags = ["manual"],
)

terraform_test_map(
    name = "fixture",
    testonly = True,
    tags = ["manual"],
)

terraform_test_map_test(
    name = "terraform_test_map_analysis_test",
    target_under_test = ":fixture.fmt_test",
)

docs_filegroup(
    name = "docs",
    srcs = glob(["*.md"]),
    visibility = ["//tools:__pkg__"],
    deps = subpackages(
        include = ["*"],
        allow_empty = True,
    ),
)

terraform_binary(
    name = "terraform",
    visibility = ["//:__subpackages__"],
)
