note_id = 1520716965234
guid = "J|nx)>o.-L"
note_type_id = 1496733135171
note_type = "chinese"
tags = ["A1", "Numbers", "Parts_of_Speech"]

[[cards]]
id = 1520716971098
ordinal = 0

[fields]
article-title = 'Structure of days of the week'
english = 'Is today Monday?'
example-sentence = ''
example-type = ''
grammar-construct = ''
hanzi = '今天是星期一吗？'
notes = '是 is optional'
pinyin = 'Jīntiān shì Xīngqīyī ma?'
source = 'https://resources.allsetlearning.com/chinese/grammar/ASGVH4Q5'
