[[Submissions]]
  Id = 1209931328
  StatusDisplay = "Accepted"
  Lang = "golang"
  QuestionId = 1765
  TitleSlug = "merge-in-between-linked-lists"
  Code = "/**\n * Definition for singly-linked list.\n * type ListNode struct {\n *     Val int\n *     Next *ListNode\n * }\n */\nfunc mergeInBetween(list1 *ListNode, a int, b int, list2 *ListNode) *ListNode {\n    if list1 == nil {\n        return list2 \n    }\n    list2Head, list2Tail := list2, list2\n    for list2 != nil {\n        list2Tail = list2\n        list2 = list2.Next\n    }\n    count := 0\n    list1Head := list1\n    for list1 != nil {\n        next := list1.Next\n        if count == a - 1 {\n            list1.Next = list2Head\n        } else if count == b {\n            list2Tail.Next = list1.Next\n        }\n        list1 = next\n        count++\n    }\n    return list1Head\n}"
  Title = "Merge In Between Linked Lists"
  Url = "/submissions/detail/1209931328/"
  LangName = "Go"
  Timestamp = 1711018408
  Status = 10
  Runtime = "83 ms"
  IsPending = "Not Pending"
  Memory = "7.2 MB"
  CompareResult = "1111111111111111111111111111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
