load("//tools/docs:defs.bzl", "docs_filegroup")

docs_filegroup(
    name = "docs",
    srcs = glob(["*.md"]),
    visibility = ["//projects:__pkg__"],
    deps = [
        "//projects/al/releases:docs",
        "//projects/al/rules:docs",
    ],
)

alias(
    name = "al",
    actual = "//projects/al/cmd/al",
    visibility = ["//:__subpackages__"],
)
