[[Submissions]]
  Id = 1080534787
  StatusDisplay = "Accepted"
  Lang = "python3"
  QuestionId = 1286
  TitleSlug = "constrained-subsequence-sum"
  Code = "import heapq\n\nclass Solution:\n    def constrainedSubsetSum(self, nums: List[int], k: int) -> int:\n        heap = [(-nums[0], 0)]\n        ans = nums[0]\n        \n        for i in range(1, len(nums)):\n            while i - heap[0][1] > k:\n                heapq.heappop(heap)\n\n            curr = max(0, -heap[0][0]) + nums[i]\n            ans = max(ans, curr)\n            heapq.heappush(heap, (-curr, i))\n\n        return ans"
  Title = "Constrained Subsequence Sum"
  Url = "/submissions/detail/1080534787/"
  LangName = "Python3"
  Timestamp = 1697887253
  Status = 10
  Runtime = "1729 ms"
  IsPending = "Not Pending"
  Memory = "36.4 MB"
  CompareResult = "111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
