load("@rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

go_library(
    name = "go_lib",
    srcs = ["main.go"],
    importpath = "git.alwaldend.com/alwaldend/src/projects/bazel_agent/cmd/bazel_agent",
    visibility = ["//visibility:private"],
)

go_binary(
    name = "bazel_agent",
    embed = [":go_lib"],
    visibility = ["//projects/bazel_agent:__pkg__"],
)

go_test(
    name = "bazel_agent_test",
    srcs = ["main_test.go"],
    # keep
    embed = [":go_lib"],
)
