[[Submissions]]
  Id = 1014633319
  StatusDisplay = "Accepted"
  Lang = "python3"
  QuestionId = 322
  TitleSlug = "coin-change"
  Code = "class Solution:\n    def coinChange(self, coins: List[int], amount: int) -> int:\n        dp = [amount + 1] * (amount + 1)\n        dp[0] = 0\n\n        for current_amount in range(1, amount + 1):\n            for coin in coins:\n                diff = current_amount - coin\n                if diff < 0:\n                    continue\n                \n                dp[current_amount] = min(dp[current_amount], dp[diff] + 1)\n\n        return dp[-1] if dp[-1] != amount + 1 else -1\n"
  Title = "Coin Change"
  Url = "/submissions/detail/1014633319/"
  LangName = "Python3"
  Timestamp = 1691408345
  Status = 10
  Runtime = "918 ms"
  IsPending = "Not Pending"
  Memory = "16.6 MB"
  CompareResult = "111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
