load("@rules_docs//docs:defs.bzl", "docs_filegroup")

exports_files(
    [
        "repo.yml",
        "selene.toml",
    ],
    visibility = ["//:__subpackages__"],
)

alias(
    name = "selene",
    actual = "//third_party/com_github_kampfkarren_selene:selene",
    visibility = ["//:__subpackages__"],
)

docs_filegroup(
    name = "docs",
    srcs = glob(["*.md"]),
    visibility = ["//tools:__pkg__"],
)
