load("//tools/docs:defs.bzl", "docs_filegroup")

alias(
    name = "shell_worker",
    actual = "//tools/shell_worker/main/go",
    visibility = ["//:__subpackages__"],
)

docs_filegroup(
    name = "docs",
    srcs = glob(["*.md"]),
    visibility = ["//tools:__pkg__"],
    deps = [
        "//tools/shell_worker/main/bzl:docs",
    ],
)
