[[Submissions]]
  Id = 1002023003
  StatusDisplay = "Accepted"
  Lang = "python3"
  QuestionId = 448
  TitleSlug = "find-all-numbers-disappeared-in-an-array"
  Code = "class Solution:\n    # [1,1,3,4], [1,2,3,4] -> [2]\n    def findDisappearedNumbers(self, nums: List[int]) -> List[int]:\n        for number in nums:\n            index = abs(number) - 1\n            nums[index] = -1 * abs(nums[index])\n        \n        return [number\n                for number in range(1, len(nums) + 1) \n                if nums[number-1] > 0]\n        \n"
  Title = "Find All Numbers Disappeared in an Array"
  Url = "/submissions/detail/1002023003/"
  LangName = "Python3"
  Timestamp = 1690135971
  Status = 10
  Runtime = "372 ms"
  IsPending = "Not Pending"
  Memory = "25.2 MB"
  CompareResult = "1111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
