[[Submissions]]
  Id = 1002014133
  StatusDisplay = "Accepted"
  Lang = "python3"
  QuestionId = 448
  TitleSlug = "find-all-numbers-disappeared-in-an-array"
  Code = "class Solution:\n    # [1,1,3,4], [1,2,3,4] -> [2]\n    def findDisappearedNumbers(self, nums: List[int]) -> List[int]:\n        result = {number: True for number in range(1, len(nums) + 1)}\n\n        for number in nums:\n            result[number] = False\n        \n        return [number for number, valid in result.items() if valid]\n"
  Title = "Find All Numbers Disappeared in an Array"
  Url = "/submissions/detail/1002014133/"
  LangName = "Python3"
  Timestamp = 1690135266
  Status = 10
  Runtime = "345 ms"
  IsPending = "Not Pending"
  Memory = "29.5 MB"
  CompareResult = "1111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
