note_id = 1520716966850
guid = "MQ:I^`G4V("
note_type_id = 1496733135171
note_type = "chinese"
tags = ["Adjectives", "B1", "Parts_of_Speech"]

[[cards]]
id = 1520716972714
ordinal = 0

[fields]
article-title = 'Expressing "not very" with "bu zenme"'
english = "He's been in America for more than one year, but he's not very homesick."
example-sentence = ''
example-type = ''
grammar-construct = 'Subj. + 不怎么 + Adj. / [Psychological Verb]'
hanzi = '他去美国一年多了，不过不怎么想家。'
notes = ''
pinyin = 'Tā qù Měiguó yī nián duō le, bùguò bù zěnme xiǎngjiā.'
source = 'https://resources.allsetlearning.com/chinese/grammar/ASGVYIZT'
