[[Submissions]]
  Id = 1046627083
  StatusDisplay = "Accepted"
  Lang = "python3"
  QuestionId = 94
  TitleSlug = "binary-tree-inorder-traversal"
  Code = "# Definition for a binary tree node.\n# class TreeNode:\n#     def __init__(self, val=0, left=None, right=None):\n#         self.val = val\n#         self.left = left\n#         self.right = right\nclass Solution:\n    def inorderTraversal(self, root: Optional[TreeNode]) -> List[int]:\n        def get_nodes(root: TreeNode) -> Generator[None, None, TreeNode]:\n            if not root:\n                return\n\n            yield from get_nodes(root.left)\n            yield root.val\n            yield from get_nodes(root.right)\n        \n        return tuple(get_nodes(root))"
  Title = "Binary Tree Inorder Traversal"
  Url = "/submissions/detail/1046627083/"
  LangName = "Python3"
  Timestamp = 1694446276
  Status = 10
  Runtime = "43 ms"
  IsPending = "Not Pending"
  Memory = "16.2 MB"
  CompareResult = "1111111111111111111111111111111111111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
