[[Submissions]]
  Id = 1717270173
  StatusDisplay = "Accepted"
  Lang = "postgresql"
  QuestionId = 586
  TitleSlug = "customer-placing-the-largest-number-of-orders"
  Code = "SELECT \n    Orders.customer_number\nFROM \n    Orders\nGROUP BY \n    Orders.customer_number\nORDER BY \n    COUNT(*) DESC\nLIMIT \n    1;"
  Title = "Customer Placing the Largest Number of Orders"
  Url = "/submissions/detail/1717270173/"
  LangName = "PostgreSQL"
  Timestamp = 1753889488
  Status = 10
  Runtime = "262 ms"
  IsPending = "Not Pending"
  Memory = "0.0B"
  CompareResult = "11111111111111111111"
  HasNotes = false
  FlagType = 1
