[[Submissions]]
  Id = 989415156
  StatusDisplay = "Accepted"
  Lang = "python3"
  QuestionId = 58
  TitleSlug = "length-of-last-word"
  Code = "class Solution:\n    # we need to iterate over the string searching for words\n    # possible combinations:\n    # 1. a whitespace after a symbol: end of the word\n    # 2. a whitespace after a whitespace: ignore\n    # 3. a symbol after a symbol, but it's the last symbol: end of the last word\n    # 4. a symbol after a symbol: ignore\n    def lengthOfLastWord(self, s: str) -> int:\n        length = len(s)\n        if length == 1:\n            return 1\n\n        word_start, word_end, in_word = 0, 0, False\n\n        for i, symbol in enumerate(s):\n            is_whitespace = symbol == \" \"\n            is_last = i == length - 1\n            \n            if is_whitespace and in_word:\n                in_word = False\n                word_end = i - 1\n                continue\n            \n            if is_whitespace and not in_word:\n                continue\n\n            if not is_whitespace and in_word and is_last:\n                word_end = i\n                continue\n\n            if not is_whitespace and not in_word and is_last:\n                word_end = i\n                word_start = i\n                continue\n\n            if not is_whitespace and in_word:\n                continue\n\n            if not is_whitespace and not in_word:\n                word_start = i\n                in_word = True\n                continue\n            \n        return word_end - word_start + 1"
  Title = "Length of Last Word"
  Url = "/submissions/detail/989415156/"
  LangName = "Python3"
  Timestamp = 1688831281
  Status = 10
  Runtime = "56 ms"
  IsPending = "Not Pending"
  Memory = "16.4 MB"
  CompareResult = "1111111111111111111111111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
