[[Submissions]]
  Id = 1007875491
  StatusDisplay = "Accepted"
  Lang = "python3"
  QuestionId = 664
  TitleSlug = "strange-printer"
  Code = "class Solution:\n    def strangePrinter(self, s: str) -> int:\n        n = len(s)\n        dp = [[n] * n for _ in range(n)]\n        for length in range(1, n + 1):\n            for left in range(n - length + 1):\n                right = left + length - 1\n                j = -1\n                for i in range(left, right):\n                    if s[i] != s[right] and j == -1:\n                        j = i\n                    if j != -1:\n                        dp[left][right] = min(dp[left][right], 1 + dp[j][i] + dp[i + 1][right])\n        \n                if j == -1:\n                    dp[left][right] = 0\n\n        return dp[0][n - 1] + 1"
  Title = "Strange Printer"
  Url = "/submissions/detail/1007875491/"
  LangName = "Python3"
  Timestamp = 1690737075
  Status = 10
  Runtime = "1399 ms"
  IsPending = "Not Pending"
  Memory = "16.3 MB"
  CompareResult = "11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
