[[Submissions]]
  Id = 1100704063
  StatusDisplay = "Accepted"
  Lang = "cpp"
  QuestionId = 1988
  TitleSlug = "minimize-maximum-pair-sum-in-array"
  Code = "class Solution {\npublic:\n    int minPairSum(vector<int>& nums) {\n        std::sort(nums.begin(), nums.end());\n        unsigned long length {nums.size()};\n        int maxSum {0};\n        for (int i = 0; i < length / 2; ++i) {\n            maxSum = max(maxSum, nums[i] + nums[length - i - 1]);\n        }\n        return maxSum;\n    }\n};"
  Title = "Minimize Maximum Pair Sum in Array"
  Url = "/submissions/detail/1100704063/"
  LangName = "C++"
  Timestamp = 1700215346
  Status = 10
  Runtime = "190 ms"
  IsPending = "Not Pending"
  Memory = "96.9 MB"
  CompareResult = "1111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
