"""Generate Gradle build inputs from a rules_jvm_external lock file."""

load("@aspect_bazel_lib//lib:run_binary.bzl", "run_binary")
load("@aspect_bazel_lib//lib:write_source_files.bzl", "write_source_file")

def al_gradle_lock(name, lock_file, tool):
    """Generate a Gradle version catalog from a rules_jvm_external lock file.

    Creates:
      <name>_toml_run:    run_binary producing libs.versions.generated.toml
      <name>_toml_write:  write_source_file diffing it against the source tree

    Run `bazel run :<name>_toml_write` to update the checked-in file.
    The generated `*_toml_write_test` target fails when the file is stale.

    The dependency verification file (verification-metadata.xml) must be
    generated by Gradle itself (`--write-verification-metadata sha256`)
    because it must include entries for the plugin classpath, which the
    Bazel lock file does not cover.

    Args:
        name: target name prefix
        lock_file: label of the maven_install.json lock file
        tool: label of the gradle_lock_gen Go binary
    """
    run_binary(
        name = "{}_toml_run".format(name),
        tool = tool,
        srcs = [lock_file],
        args = [
            "--format=toml",
            "--out=$(location libs.versions.generated.toml)",
            "$(location {})".format(lock_file),
        ],
        outs = ["libs.versions.generated.toml"],
    )
    write_source_file(
        name = "{}_toml_write".format(name),
        in_file = ":{}_toml_run".format(name),
        out_file = "libs.versions.toml",
    )
