note_id = 1520716969843
guid = "lOp2z,gI:-"
note_type_id = 1496733135171
note_type = "chinese"
tags = ["Adverbs", "B2", "Parts_of_Speech"]

[[cards]]
id = 1520716975707
ordinal = 0

[fields]
article-title = 'Rhetorical questions with "nandao"'
english = 'How many more kids do they want to have?'
example-sentence = ''
example-type = 'invalid'
grammar-construct = '难道 + [Rhetorical Question]'
hanzi = '难道他们还要再生几个孩子？'
notes = 'Not a 吗 question'
pinyin = ''
source = 'https://resources.allsetlearning.com/chinese/grammar/ASGMCP9V'
