[[Submissions]]
  Id = 1274487910
  StatusDisplay = "Accepted"
  Lang = "python3"
  QuestionId = 260
  TitleSlug = "single-number-iii"
  Code = "class Solution:\n    def singleNumber(self, nums: list[int]) -> list[int]:\n        n: int = len(nums)\n        result: list[int] = [0, 0]\n        index = 0\n\n        for i in range(n):\n            found = False\n            for j in range(n):\n                if i != j and nums[i] == nums[j]:\n                    found = True\n                    break\n            if not found:\n                result[index] = nums[i]\n                index += 1\n                if index == 2:\n                    break\n\n        return result"
  Title = "Single Number III"
  Url = "/submissions/detail/1274487910/"
  LangName = "Python3"
  Timestamp = 1717268659
  Status = 10
  Runtime = "2759 ms"
  IsPending = "Not Pending"
  Memory = "18.5 MB"
  CompareResult = "111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
