load("@com_alwaldend_src_npm//:postcss-cli/package_json.bzl", postcss = "bin")
load("//tools/docs:defs.bzl", "docs_filegroup")

postcss.postcss_binary(
    name = "postcss",
    data = [
        "//:node_modules/autoprefixer",
    ],
    visibility = ["//:__subpackages__"],
)

docs_filegroup(
    name = "docs",
    srcs = glob(["*.md"]),
    visibility = ["//tools:__pkg__"],
)
