note_id = 1520716965765
guid = "Pj{h+:7Cly"
note_type_id = 1496733135171
note_type = "chinese"
tags = ["A2", "Adverbs", "Parts_of_Speech"]

[[cards]]
id = 1520716971629
ordinal = 0

[fields]
article-title = 'Expressing "just" with "gang"'
english = 'He just got to China two months ago.'
example-sentence = ''
example-type = ''
grammar-construct = 'Subj. + 刚 + Verb (+ Obj.)  + Duration'
hanzi = '他刚来中国两个月。'
notes = ''
pinyin = 'Tā gāng lái Zhōngguó liǎng gè yuè.'
source = 'https://resources.allsetlearning.com/chinese/grammar/ASGQJJYO'
