note_id = 1520716969725
guid = "pfjfg4g3m."
note_type_id = 1496733135171
note_type = "chinese"
tags = ["Adverbs", "B2", "Parts_of_Speech"]

[[cards]]
id = 1520716975589
ordinal = 0

[fields]
article-title = 'Expressing "in the end" with "jiujing"'
english = 'Family are family after all. You may not like them, but you will still love them.'
example-sentence = ''
example-type = ''
grammar-construct = 'A＋究竟 + 是＋ A，……'
hanzi = '家人究竟是家人，也许你不喜欢他们，但你还是会爱他们。'
notes = ''
pinyin = ''
source = 'https://resources.allsetlearning.com/chinese/grammar/ASGDK0BR'
