load("@rules_docs//docs:defs.bzl", "docs_filegroup")
load("//tools/bzl/main/bzl:al_bzl_library_map.bzl", "al_bzl_library_map")

al_bzl_library_map(
    name = "libs",
    libs = {
        "al_resolved_toolchain": [],
    },
    visibility = ["//:__subpackages__"],
)

docs_filegroup(
    name = "docs",
    srcs = glob(["*.md"]),
    visibility = ["//tools/resolved_toolchain:__pkg__"],
    deps = [
        ":libs.stardoc",
    ],
)
