[[Submissions]]
  Id = 1278221123
  StatusDisplay = "Accepted"
  Lang = "python3"
  QuestionId = 1044
  TitleSlug = "find-common-characters"
  Code = "class Solution:\n    def commonChars(self, words: List[str]) -> List[str]:\n        result = []\n        \n        # Check each character from 'a' to 'z'\n        for char in range(ord('a'), ord('z') + 1):\n            char = chr(char)\n            min_count = float('inf')  # Start with a very high number\n            \n            # Find the minimum count of the character in all words\n            for word in words:\n                count = word.count(char)  # Count the current character in the current word\n                min_count = min(min_count, count)  # Keep track of the smallest count\n                if min_count == 0:\n                    break  # If the character is not in one of the words, we can skip further checking\n            \n            # Add the character to the result list the required number of times\n            result.extend([char] * min_count)\n        \n        return result"
  Title = "Find Common Characters"
  Url = "/submissions/detail/1278221123/"
  LangName = "Python3"
  Timestamp = 1717572756
  Status = 10
  Runtime = "41 ms"
  IsPending = "Not Pending"
  Memory = "16.8 MB"
  CompareResult = "11111111111111111111111111111111111111111111111111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
