load("@rules_docs//docs:defs.bzl", "docs_filegroup")
load("//projects/hugo_landing/pkg/bzl:al_hugo_landing.bzl", "al_hugo_landing_site")

al_hugo_landing_site(
    name = "site",
    docs = "//projects/android_launcher:docs",
    docs_url = "https://alwaldend.com/docs/projects/android_launcher/",
    project = "android_launcher",
    repository_url = "https://github.com/alwaldend/src",
    title = "Android Launcher",
    visibility = ["//projects:__pkg__"],
)

docs_filegroup(
    name = "docs",
    srcs = glob(
        ["*.md"],
        allow_empty = True,
    ),
    visibility = ["//projects/android_launcher:__pkg__"],
)
