[[Submissions]]
  Id = 1032260045
  StatusDisplay = "Accepted"
  Lang = "python3"
  QuestionId = 112
  TitleSlug = "path-sum"
  Code = "# Definition for a binary tree node.\n# class TreeNode:\n#     def __init__(self, val=0, left=None, right=None):\n#         self.val = val\n#         self.left = left\n#         self.right = right\nclass Solution:\n    def hasPathSum(self, root: Optional[TreeNode], targetSum: int) -> bool:\n        node_stack = [(root, 0)]\n        while node_stack:\n            node, curr_sum = node_stack.pop()\n            if not node:\n                continue\n            \n            new_sum = curr_sum + node.val\n            if new_sum == targetSum and not node.left and not node.right:\n                return True\n            \n            node_stack.extend(((node.left, new_sum), (node.right, new_sum)))\n                \n        return False"
  Title = "Path Sum"
  Url = "/submissions/detail/1032260045/"
  LangName = "Python3"
  Timestamp = 1693055164
  Status = 10
  Runtime = "36 ms"
  IsPending = "Not Pending"
  Memory = "17.6 MB"
  CompareResult = "111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
