package main

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
	"unicode"
	"unicode/utf8"

	"github.com/spf13/cobra"
)

const (
	commentDisclaimer         = "LLM-disclaimer: This comment was generated by an LLM."
	noTopLevelCommentSentinel = "NONE"
	reviewReplyReceiptSchema  = "repo_delivery/review_reply/v4"
	reviewReplyAuthorityLimit = 5 * time.Minute
)

type reviewTargetOptions struct {
	PullRequestID             string
	ExpectedHeadOID           string
	ExpectedPullRequestDigest string
}

type reviewReplyOptions struct {
	reviewTargetOptions
	ThreadID              string
	ExpectedLastCommentID string
	ExpectedThreadDigest  string
	BodyFile              string
	ReplyReceiptFile      string
}

type reviewCommentOptions struct {
	reviewTargetOptions
	ExpectedLastCommentID string
	ExpectedDigest        string
	BodyFile              string
}

type reviewResolveOptions struct {
	reviewTargetOptions
	ThreadID              string
	ExpectedLastCommentID string
	ExpectedThreadDigest  string
	ReplyReceiptFile      string
}

type reviewRequestOptions struct {
	reviewTargetOptions
	Reviewers []string
}

// reviewReplyReceipt is a local consistency record proving that this tool
// observed its own reply before a later resolution. It deliberately contains
// no comment body or remote URL and is not an unforgeable authorization token.
type reviewReplyReceipt struct {
	Schema                string           `json:"schema"`
	IssuedAt              string           `json:"issued_at"`
	ExpiresAt             string           `json:"expires_at"`
	RepositoryFingerprint string           `json:"repository_fingerprint"`
	RemoteRepository      remoteRepository `json:"remote_repository"`
	Forge                 string           `json:"forge"`
	PullRequestID         string           `json:"pull_request_id"`
	PullRequestNumber     int              `json:"pull_request_number"`
	PullRequestDigest     string           `json:"pull_request_digest"`
	PullRequestUpdatedAt  string           `json:"pull_request_updated_at"`
	ReviewInventoryDigest string           `json:"review_inventory_digest"`
	HeadOID               string           `json:"head_oid"`
	ThreadID              string           `json:"thread_id"`
	PriorThreadDigest     string           `json:"prior_thread_digest"`
	ReplyCommentID        string           `json:"reply_comment_id"`
	ReplyBodyDigest       string           `json:"reply_body_digest"`
	ResultThreadDigest    string           `json:"result_thread_digest"`
}

type reviewReplyReceiptClockKey struct{}

func withReviewReplyReceiptClock(
	ctx context.Context,
	clock func() time.Time,
) context.Context {
	return context.WithValue(ctx, reviewReplyReceiptClockKey{}, clock)
}

func reviewReplyReceiptNow(ctx context.Context) time.Time {
	if clock, ok := ctx.Value(reviewReplyReceiptClockKey{}).(func() time.Time); ok &&
		clock != nil {
		return clock()
	}
	return time.Now()
}

func newReviewCommand(
	ctx context.Context,
	config *deliveryConfig,
	getenv func(string) string,
	stdout io.Writer,
	runner commandRunner,
) *cobra.Command {
	command := &cobra.Command{
		Use:   "review",
		Short: "Inspect and update pull-request review state",
		Args:  cobra.NoArgs,
	}
	command.AddCommand(
		newReviewInspectCommand(ctx, config, getenv, stdout, runner),
		newReviewCommentCommand(ctx, config, getenv, stdout, runner),
		newReviewReplyCommand(ctx, config, getenv, stdout, runner),
		newReviewResolveCommand(ctx, config, getenv, stdout, runner),
		newReviewRequestCommand(ctx, config, getenv, stdout, runner),
	)
	return command
}

func newReviewCommentCommand(
	ctx context.Context,
	config *deliveryConfig,
	getenv func(string) string,
	stdout io.Writer,
	runner commandRunner,
) *cobra.Command {
	options := &reviewCommentOptions{}
	command := &cobra.Command{
		Use:   "comment",
		Short: "Add a top-level comment to an unchanged pull request",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			delivery, err := deliveryFromConfig(ctx, config, getenv, runner)
			if err != nil {
				return err
			}
			body, err := delivery.readReviewBody(ctx, options.BodyFile)
			if err != nil {
				return fmt.Errorf("read review comment body: %w", err)
			}
			body, err = withCommentDisclaimer(body)
			if err != nil {
				return err
			}
			inspection, err := delivery.commentOnPullRequest(
				ctx,
				options.reviewTargetOptions,
				topLevelCommentExpectation{
					ExpectedLastCommentID: options.ExpectedLastCommentID,
					ExpectedDigest:        options.ExpectedDigest,
				},
				body,
			)
			if err != nil {
				return err
			}
			return writeJSON(stdout, inspection)
		},
	}
	addReviewTargetFlags(command, &options.reviewTargetOptions)
	flags := command.Flags()
	flags.StringVar(
		&options.ExpectedLastCommentID,
		"expected-last-top-level-comment",
		"",
		"exact token observed in review inspect (NONE means no comments)",
	)
	flags.StringVar(
		&options.BodyFile,
		"body-file",
		"",
		"ignored top-level comment body under out/<task>/",
	)
	flags.StringVar(
		&options.ExpectedDigest,
		"expected-top-level-comments-digest",
		"",
		"exact top-level comment inventory digest observed by review inspect",
	)
	_ = command.MarkFlagRequired("expected-last-top-level-comment")
	_ = command.MarkFlagRequired("expected-top-level-comments-digest")
	_ = command.MarkFlagRequired("body-file")
	return command
}

func newReviewInspectCommand(
	ctx context.Context,
	config *deliveryConfig,
	getenv func(string) string,
	stdout io.Writer,
	runner commandRunner,
) *cobra.Command {
	return &cobra.Command{
		Use:   "inspect",
		Short: "Read all comments, reviews, and review threads",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			delivery, err := deliveryFromConfig(ctx, config, getenv, runner)
			if err != nil {
				return err
			}
			inspection, err := delivery.inspectReviews(ctx)
			if err != nil {
				return err
			}
			return writeJSON(stdout, inspection)
		},
	}
}

func newReviewReplyCommand(
	ctx context.Context,
	config *deliveryConfig,
	getenv func(string) string,
	stdout io.Writer,
	runner commandRunner,
) *cobra.Command {
	options := &reviewReplyOptions{}
	command := &cobra.Command{
		Use:   "reply",
		Short: "Reply to an unchanged unresolved review thread",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			delivery, err := deliveryFromConfig(ctx, config, getenv, runner)
			if err != nil {
				return err
			}
			// Validate the destination before causing an external mutation. The
			// atomic installation is repeated afterward in case local state races.
			receiptPath, err := delivery.receiptPath(
				ctx,
				options.ReplyReceiptFile,
				false,
			)
			if err != nil {
				return fmt.Errorf("validate review reply receipt path: %w", err)
			}
			if err := delivery.requireSameReviewTaskDirectory(
				options.BodyFile,
				receiptPath,
			); err != nil {
				return err
			}
			body, err := delivery.readReviewBody(ctx, options.BodyFile)
			if err != nil {
				return fmt.Errorf("read review body: %w", err)
			}
			body, err = withCommentDisclaimer(body)
			if err != nil {
				return err
			}
			inspection, err := delivery.replyToReviewThread(
				ctx,
				options.reviewTargetOptions,
				reviewThreadExpectation{
					ThreadID:              options.ThreadID,
					ExpectedLastCommentID: options.ExpectedLastCommentID,
					ExpectedDigest:        options.ExpectedThreadDigest,
				},
				body,
			)
			if err != nil {
				return err
			}
			receipt, err := delivery.newReviewReplyReceipt(
				ctx,
				options.reviewTargetOptions,
				options.ThreadID,
				options.ExpectedThreadDigest,
				body,
				inspection,
			)
			if err != nil {
				return fmt.Errorf(
					"reply succeeded but its receipt could not be constructed; do not resolve the thread: %w",
					err,
				)
			}
			if err := delivery.writeReviewReplyReceipt(
				ctx,
				options.ReplyReceiptFile,
				receipt,
			); err != nil {
				return fmt.Errorf(
					"reply succeeded but its receipt could not be installed; do not retry the reply or resolve the thread: %w",
					err,
				)
			}
			return writeJSON(stdout, inspection)
		},
	}
	addReviewTargetFlags(command, &options.reviewTargetOptions)
	flags := command.Flags()
	flags.StringVar(&options.ThreadID, "thread-id", "", "exact review thread node ID")
	flags.StringVar(
		&options.ExpectedLastCommentID,
		"expected-last-comment-id",
		"",
		"exact last comment node ID observed by review inspect",
	)
	flags.StringVar(
		&options.ExpectedThreadDigest,
		"expected-thread-digest",
		"",
		"exact thread digest observed by review inspect",
	)
	flags.StringVar(
		&options.BodyFile,
		"body-file",
		"",
		"ignored review reply body under out/<task>/",
	)
	flags.StringVar(
		&options.ReplyReceiptFile,
		"reply-receipt-file",
		"",
		"ignored output receipt under out/<task>/ required for resolution",
	)
	_ = command.MarkFlagRequired("thread-id")
	_ = command.MarkFlagRequired("expected-last-comment-id")
	_ = command.MarkFlagRequired("expected-thread-digest")
	_ = command.MarkFlagRequired("body-file")
	_ = command.MarkFlagRequired("reply-receipt-file")
	return command
}

func (d *delivery) requireSameReviewTaskDirectory(
	bodyFile string,
	receiptPath string,
) error {
	taskForPath := func(value string) (string, error) {
		absolute := value
		if !filepath.IsAbs(absolute) {
			absolute = filepath.Join(d.repository.directory, absolute)
		}
		absolute = filepath.Clean(absolute)
		relative, err := filepath.Rel(d.repository.directory, absolute)
		if err != nil {
			return "", err
		}
		parts := strings.Split(filepath.ToSlash(relative), "/")
		if len(parts) < 3 || parts[0] != "out" || parts[1] == "" ||
			parts[1] == "." || parts[1] == ".." {
			return "", fmt.Errorf("path is not under out/<task>/")
		}
		return parts[1], nil
	}
	bodyTask, err := taskForPath(bodyFile)
	if err != nil {
		return fmt.Errorf("locate review body task directory: %w", err)
	}
	receiptTask, err := taskForPath(receiptPath)
	if err != nil {
		return fmt.Errorf("locate review reply receipt task directory: %w", err)
	}
	if bodyTask != receiptTask {
		return fmt.Errorf(
			"--body-file and --reply-receipt-file must share the same out/<task>/ directory",
		)
	}
	return nil
}

func newReviewResolveCommand(
	ctx context.Context,
	config *deliveryConfig,
	getenv func(string) string,
	stdout io.Writer,
	runner commandRunner,
) *cobra.Command {
	options := &reviewResolveOptions{}
	command := &cobra.Command{
		Use:   "resolve",
		Short: "Resolve an unchanged review thread",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			delivery, err := deliveryFromConfig(ctx, config, getenv, runner)
			if err != nil {
				return err
			}
			inspection, err := delivery.resolveReviewThread(
				ctx,
				options.reviewTargetOptions,
				reviewThreadExpectation{
					ThreadID:              options.ThreadID,
					ExpectedLastCommentID: options.ExpectedLastCommentID,
					ExpectedDigest:        options.ExpectedThreadDigest,
				},
				options.ReplyReceiptFile,
			)
			if err != nil {
				return err
			}
			return writeJSON(stdout, inspection)
		},
	}
	addReviewTargetFlags(command, &options.reviewTargetOptions)
	flags := command.Flags()
	flags.StringVar(&options.ThreadID, "thread-id", "", "exact review thread node ID")
	flags.StringVar(
		&options.ExpectedLastCommentID,
		"expected-last-comment-id",
		"",
		"exact last comment node ID observed by review inspect",
	)
	flags.StringVar(
		&options.ExpectedThreadDigest,
		"expected-thread-digest",
		"",
		"exact thread digest observed by review inspect",
	)
	flags.StringVar(
		&options.ReplyReceiptFile,
		"reply-receipt-file",
		"",
		"exact ignored reply receipt written by review reply",
	)
	_ = command.MarkFlagRequired("thread-id")
	_ = command.MarkFlagRequired("expected-last-comment-id")
	_ = command.MarkFlagRequired("expected-thread-digest")
	_ = command.MarkFlagRequired("reply-receipt-file")
	return command
}

func newReviewRequestCommand(
	ctx context.Context,
	config *deliveryConfig,
	getenv func(string) string,
	stdout io.Writer,
	runner commandRunner,
) *cobra.Command {
	options := &reviewRequestOptions{}
	command := &cobra.Command{
		Use:   "request",
		Short: "Request review from explicit user accounts",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			delivery, err := deliveryFromConfig(ctx, config, getenv, runner)
			if err != nil {
				return err
			}
			inspection, err := delivery.requestReview(ctx, *options)
			if err != nil {
				return err
			}
			return writeJSON(stdout, inspection)
		},
	}
	addReviewTargetFlags(command, &options.reviewTargetOptions)
	command.Flags().StringArrayVar(
		&options.Reviewers,
		"reviewer",
		nil,
		"explicit reviewer account (repeatable)",
	)
	_ = command.MarkFlagRequired("reviewer")
	return command
}

func addReviewTargetFlags(
	command *cobra.Command,
	options *reviewTargetOptions,
) {
	flags := command.Flags()
	flags.StringVar(
		&options.PullRequestID,
		"pull-request-id",
		"",
		"exact pull-request node ID observed by review inspect",
	)
	flags.StringVar(
		&options.ExpectedHeadOID,
		"expected-head",
		"",
		"exact pull-request head OID observed by review inspect",
	)
	flags.StringVar(
		&options.ExpectedPullRequestDigest,
		"expected-pull-request-digest",
		"",
		"exact pull-request context digest observed by review inspect",
	)
	_ = command.MarkFlagRequired("pull-request-id")
	_ = command.MarkFlagRequired("expected-head")
	_ = command.MarkFlagRequired("expected-pull-request-digest")
}

func (d *delivery) inspectReviews(
	ctx context.Context,
) (*reviewInspection, error) {
	pullRequest, capability, err := d.reviewTarget(ctx)
	if err != nil {
		return nil, err
	}
	return capability.InspectReviews(ctx, d.remoteRepository, *pullRequest)
}

func (d *delivery) replyToReviewThread(
	ctx context.Context,
	options reviewTargetOptions,
	expectation reviewThreadExpectation,
	body string,
) (*reviewInspection, error) {
	pullRequest, capability, err := d.expectedReviewTarget(ctx, options)
	if err != nil {
		return nil, err
	}
	if err := validateThreadExpectation(expectation); err != nil {
		return nil, err
	}
	return capability.ReplyToReviewThread(
		ctx,
		d.remoteRepository,
		*pullRequest,
		expectation,
		body,
	)
}

func (d *delivery) commentOnPullRequest(
	ctx context.Context,
	options reviewTargetOptions,
	expectation topLevelCommentExpectation,
	body string,
) (*reviewInspection, error) {
	pullRequest, capability, err := d.expectedReviewTarget(ctx, options)
	if err != nil {
		return nil, err
	}
	if err := validateTopLevelCommentExpectation(expectation); err != nil {
		return nil, err
	}
	return capability.CommentOnPullRequest(
		ctx,
		d.remoteRepository,
		*pullRequest,
		expectation,
		body,
	)
}

func (d *delivery) resolveReviewThread(
	ctx context.Context,
	options reviewTargetOptions,
	expectation reviewThreadExpectation,
	replyReceiptFile string,
) (*reviewInspection, error) {
	pullRequest, capability, err := d.expectedReviewTarget(ctx, options)
	if err != nil {
		return nil, err
	}
	if err := validateThreadExpectation(expectation); err != nil {
		return nil, err
	}
	receipt, err := d.readReviewReplyReceipt(ctx, replyReceiptFile)
	if err != nil {
		return nil, fmt.Errorf("read review reply receipt: %w", err)
	}
	if err := d.validateReviewReplyReceiptContext(
		ctx,
		receipt,
		options,
		*pullRequest,
		expectation,
	); err != nil {
		return nil, err
	}
	expectation.RequiredReplyBodyDigest = receipt.ReplyBodyDigest
	expectation.RequiredInventoryDigest = receipt.ReviewInventoryDigest
	expectation.AuthorityExpiresAt = receipt.ExpiresAt
	consumed, err := d.consumeReviewReplyReceipt(
		ctx,
		replyReceiptFile,
		receipt,
	)
	if err != nil {
		return nil, fmt.Errorf("consume review reply receipt: %w", err)
	}
	if err := receipt.validateAuthorityAt(reviewReplyReceiptNow(ctx)); err != nil {
		cleanupErr := consumed.cleanup()
		return nil, errors.Join(err, cleanupErr)
	}
	inspection, resolveErr := capability.ResolveReviewThread(
		ctx,
		d.remoteRepository,
		*pullRequest,
		expectation,
	)
	cleanupErr := consumed.cleanup()
	if resolveErr != nil {
		retryErr := fmt.Errorf(
			"review reply receipt was consumed before the resolution attempt; " +
				"post a fresh reply before another attempt",
		)
		if cleanupErr != nil {
			return nil, errors.Join(resolveErr, retryErr, cleanupErr)
		}
		return nil, errors.Join(resolveErr, retryErr)
	}
	if cleanupErr != nil {
		return nil, fmt.Errorf(
			"review thread resolution succeeded, but cleaning the consumed "+
				"reply receipt failed: %w",
			cleanupErr,
		)
	}
	return inspection, nil
}

func (d *delivery) requestReview(
	ctx context.Context,
	options reviewRequestOptions,
) (*reviewInspection, error) {
	pullRequest, capability, err := d.expectedReviewTarget(
		ctx,
		options.reviewTargetOptions,
	)
	if err != nil {
		return nil, err
	}
	reviewers, err := normalizeReviewers(options.Reviewers)
	if err != nil {
		return nil, err
	}
	return capability.RequestReview(
		ctx,
		d.remoteRepository,
		*pullRequest,
		reviewers,
	)
}

func (d *delivery) expectedReviewTarget(
	ctx context.Context,
	options reviewTargetOptions,
) (*pullRequest, reviewForge, error) {
	if err := validateOpaqueID("--pull-request-id", options.PullRequestID); err != nil {
		return nil, nil, err
	}
	if !isObjectID(options.ExpectedHeadOID) {
		return nil, nil, fmt.Errorf("--expected-head must be a full Git object ID")
	}
	if err := validateSHA256Digest(
		"--expected-pull-request-digest",
		options.ExpectedPullRequestDigest,
	); err != nil {
		return nil, nil, err
	}
	pullRequest, capability, err := d.reviewTarget(ctx)
	if err != nil {
		return nil, nil, err
	}
	if pullRequest.ID != options.PullRequestID ||
		pullRequest.HeadRefOID != options.ExpectedHeadOID ||
		reviewPullRequestDigest(d.remoteRepository, *pullRequest) !=
			options.ExpectedPullRequestDigest {
		return nil, nil, fmt.Errorf(
			"pull request identity, head, or context changed after review inspection",
		)
	}
	return pullRequest, capability, nil
}

func (d *delivery) reviewTarget(
	ctx context.Context,
) (*pullRequest, reviewForge, error) {
	capability, ok := d.forge.(reviewForge)
	if !ok {
		return nil, nil, fmt.Errorf(
			"forge adapter %q does not support review operations",
			d.forge.Name(),
		)
	}
	branch, err := d.repository.currentBranch(ctx)
	if err != nil {
		return nil, nil, err
	}
	all, err := d.forge.PullRequests(ctx, d.remoteRepository, branch)
	if err != nil {
		return nil, nil, err
	}
	exact, err := exactPullRequests(all, d.remoteRepository, branch)
	if err != nil {
		return nil, nil, err
	}
	pullRequest, refusals := selectOpenPullRequest(exact)
	if len(refusals) != 0 {
		return nil, nil, fmt.Errorf(
			"cannot select exact open pull request: %s",
			strings.Join(refusals, "; "),
		)
	}
	if pullRequest == nil {
		return nil, nil, fmt.Errorf(
			"no open pull request exists for the exact repository and head",
		)
	}
	return pullRequest, capability, nil
}

func validateThreadExpectation(expectation reviewThreadExpectation) error {
	if err := validateOpaqueID("--thread-id", expectation.ThreadID); err != nil {
		return err
	}
	if err := validateOpaqueID(
		"--expected-last-comment-id",
		expectation.ExpectedLastCommentID,
	); err != nil {
		return err
	}
	return validateSHA256Digest(
		"--expected-thread-digest",
		expectation.ExpectedDigest,
	)
}

func validateResolutionThreadExpectation(
	expectation reviewThreadExpectation,
) error {
	if err := validateThreadExpectation(expectation); err != nil {
		return err
	}
	if err := validateSHA256Digest(
		"reply receipt body digest",
		expectation.RequiredReplyBodyDigest,
	); err != nil {
		return err
	}
	if err := validateSHA256Digest(
		"reply receipt review inventory digest",
		expectation.RequiredInventoryDigest,
	); err != nil {
		return err
	}
	if _, err := time.Parse(time.RFC3339Nano, expectation.AuthorityExpiresAt); err != nil {
		return fmt.Errorf("reply receipt authority expiration must be RFC3339")
	}
	return nil
}

func validateSHA256Digest(name, value string) error {
	decoded, err := hex.DecodeString(value)
	if err != nil || len(decoded) != sha256.Size || value != strings.ToLower(value) {
		return fmt.Errorf("%s must be a lowercase SHA-256 digest", name)
	}
	return nil
}

func reviewPullRequestDigest(
	repository remoteRepository,
	pullRequest pullRequest,
) string {
	// UpdatedAt is intentionally excluded: every review mutation updates it.
	// All caller-relevant identity, topology, base/head, and editable metadata
	// remains bound so a same-head human edit cannot pass an old guard.
	snapshot := struct {
		Repository          remoteRepository `json:"repository"`
		ID                  string           `json:"id"`
		Number              int              `json:"number"`
		URL                 string           `json:"url"`
		State               string           `json:"state"`
		Title               string           `json:"title"`
		Body                string           `json:"body"`
		AuthorLogin         string           `json:"author_login"`
		BaseRefName         string           `json:"base_ref_name"`
		BaseRefOID          string           `json:"base_ref_oid"`
		HeadRefName         string           `json:"head_ref_name"`
		HeadRefOID          string           `json:"head_ref_oid"`
		HeadRepositoryOwner string           `json:"head_repository_owner"`
		HeadRepositoryName  string           `json:"head_repository_name"`
		IsCrossRepository   bool             `json:"is_cross_repository"`
		IsDraft             bool             `json:"is_draft"`
	}{
		Repository:          repository,
		ID:                  pullRequest.ID,
		Number:              pullRequest.Number,
		URL:                 pullRequest.URL,
		State:               strings.ToUpper(pullRequest.State),
		Title:               pullRequest.Title,
		Body:                pullRequest.Body,
		AuthorLogin:         pullRequest.AuthorLogin,
		BaseRefName:         pullRequest.BaseRefName,
		BaseRefOID:          pullRequest.BaseRefOID,
		HeadRefName:         pullRequest.HeadRefName,
		HeadRefOID:          pullRequest.HeadRefOID,
		HeadRepositoryOwner: strings.ToLower(pullRequest.HeadRepositoryOwner),
		HeadRepositoryName:  strings.ToLower(pullRequest.HeadRepositoryName),
		IsCrossRepository:   pullRequest.IsCrossRepository,
		IsDraft:             pullRequest.IsDraft,
	}
	encoded, err := json.Marshal(snapshot)
	if err != nil {
		panic(fmt.Sprintf("encode pull-request review context: %v", err))
	}
	digest := sha256.Sum256(encoded)
	return hex.EncodeToString(digest[:])
}

func reviewReplyBodyDigest(body string) string {
	digest := sha256.Sum256([]byte(
		"repo_delivery review reply v1\x00" + normalizeText(body),
	))
	return hex.EncodeToString(digest[:])
}

func reviewThreadDigest(thread reviewThread) string {
	snapshot := struct {
		ID                string          `json:"id"`
		IsResolved        bool            `json:"is_resolved"`
		IsOutdated        bool            `json:"is_outdated"`
		Path              string          `json:"path"`
		Line              *int            `json:"line"`
		OriginalLine      *int            `json:"original_line"`
		StartLine         *int            `json:"start_line"`
		OriginalStartLine *int            `json:"original_start_line"`
		Comments          []reviewComment `json:"comments"`
	}{
		ID:                thread.ID,
		IsResolved:        thread.IsResolved,
		IsOutdated:        thread.IsOutdated,
		Path:              thread.Path,
		Line:              thread.Line,
		OriginalLine:      thread.OriginalLine,
		StartLine:         thread.StartLine,
		OriginalStartLine: thread.OriginalStartLine,
		Comments:          thread.Comments,
	}
	encoded, err := json.Marshal(snapshot)
	if err != nil {
		panic(fmt.Sprintf("encode review thread snapshot: %v", err))
	}
	digest := sha256.Sum256(encoded)
	return hex.EncodeToString(digest[:])
}

func reviewInventoryDigest(inspection *reviewInspection) string {
	// Bind the complete bounded review inventory projection.
	// PullRequest.UpdatedAt is the only excluded field because GitHub may
	// advance it asynchronously for side effects whose actual review records
	// are bound below.
	pullRequestSnapshot := inspection.PullRequest
	pullRequestSnapshot.UpdatedAt = ""
	comments := append([]reviewComment(nil), inspection.Comments...)
	reviews := append([]pullRequestReview(nil), inspection.Reviews...)
	threads := append([]reviewThread(nil), inspection.Threads...)
	requested := append([]requestedReviewer(nil), inspection.RequestedReviewers...)
	if comments == nil {
		comments = []reviewComment{}
	}
	if reviews == nil {
		reviews = []pullRequestReview{}
	}
	if threads == nil {
		threads = []reviewThread{}
	}
	if requested == nil {
		requested = []requestedReviewer{}
	}
	for index := range threads {
		threads[index].Comments = append(
			[]reviewComment(nil),
			threads[index].Comments...,
		)
	}
	sort.Slice(threads, func(left, right int) bool {
		return threads[left].ID < threads[right].ID
	})
	sort.Slice(requested, func(left, right int) bool {
		return requested[left].RequestID < requested[right].RequestID
	})
	snapshot := struct {
		PullRequest                  pullRequest         `json:"pull_request"`
		PullRequestExpectationDigest string              `json:"pull_request_expectation_digest"`
		Comments                     []reviewComment     `json:"top_level_comments"`
		Reviews                      []pullRequestReview `json:"reviews"`
		Threads                      []reviewThread      `json:"review_threads"`
		RequestedReviewers           []requestedReviewer `json:"requested_reviewers"`
	}{
		PullRequest:                  pullRequestSnapshot,
		PullRequestExpectationDigest: inspection.PullRequestExpectationDigest,
		Comments:                     comments,
		Reviews:                      reviews,
		Threads:                      threads,
		RequestedReviewers:           requested,
	}
	encoded, err := json.Marshal(snapshot)
	if err != nil {
		panic(fmt.Sprintf("encode review inventory snapshot: %v", err))
	}
	digest := sha256.Sum256(encoded)
	return hex.EncodeToString(digest[:])
}

func validateReviewInventoryUnique(inspection *reviewInspection) error {
	seen := func(kind string, values []string) error {
		known := make(map[string]struct{}, len(values))
		for _, value := range values {
			if _, exists := known[value]; exists {
				return fmt.Errorf("review inventory contains duplicate %s %q", kind, value)
			}
			known[value] = struct{}{}
		}
		return nil
	}
	values := func(length int, value func(int) string) []string {
		result := make([]string, length)
		for index := range result {
			result[index] = value(index)
		}
		return result
	}
	if err := seen("top-level comment", values(len(inspection.Comments), func(i int) string { return inspection.Comments[i].ID })); err != nil {
		return err
	}
	if err := seen("review", values(len(inspection.Reviews), func(i int) string { return inspection.Reviews[i].ID })); err != nil {
		return err
	}
	if err := seen("thread", values(len(inspection.Threads), func(i int) string { return inspection.Threads[i].ID })); err != nil {
		return err
	}
	threadCommentIDs := []string{}
	for _, thread := range inspection.Threads {
		if thread.ExpectationDigest != reviewThreadDigest(thread) {
			return fmt.Errorf("review thread %q has an inconsistent expectation digest", thread.ID)
		}
		for _, comment := range thread.Comments {
			threadCommentIDs = append(threadCommentIDs, comment.ID)
		}
	}
	if err := seen("thread comment", threadCommentIDs); err != nil {
		return err
	}
	return seen("review request", values(len(inspection.RequestedReviewers), func(i int) string {
		return inspection.RequestedReviewers[i].RequestID
	}))
}

func validateTopLevelCommentExpectation(
	expectation topLevelCommentExpectation,
) error {
	if expectation.ExpectedLastCommentID != noTopLevelCommentSentinel {
		if err := validateOpaqueID(
			"--expected-last-top-level-comment",
			expectation.ExpectedLastCommentID,
		); err != nil {
			return err
		}
	}
	return validateSHA256Digest(
		"--expected-top-level-comments-digest",
		expectation.ExpectedDigest,
	)
}

func reviewCommentsDigest(comments []reviewComment) string {
	if len(comments) == 0 {
		comments = []reviewComment{}
	}
	encoded, err := json.Marshal(comments)
	if err != nil {
		panic(fmt.Sprintf("encode review comment inventory: %v", err))
	}
	digest := sha256.Sum256(encoded)
	return hex.EncodeToString(digest[:])
}

func expectedLastTopLevelComment(comments []reviewComment) string {
	if len(comments) == 0 {
		return noTopLevelCommentSentinel
	}
	return comments[len(comments)-1].ID
}

func (r reviewReplyReceipt) validate() error {
	if r.Schema != reviewReplyReceiptSchema {
		return fmt.Errorf("unsupported review reply receipt schema %q", r.Schema)
	}
	if _, _, err := r.authorityWindow(); err != nil {
		return err
	}
	if !validSHA256Digest(r.RepositoryFingerprint) {
		return fmt.Errorf("review reply receipt has an invalid repository fingerprint")
	}
	if r.RemoteRepository.Host == "" || r.RemoteRepository.Owner == "" ||
		r.RemoteRepository.Name == "" || r.Forge == "" {
		return fmt.Errorf("review reply receipt has incomplete provider identity")
	}
	if err := validateOpaqueID("receipt pull-request ID", r.PullRequestID); err != nil {
		return err
	}
	if r.PullRequestNumber <= 0 {
		return fmt.Errorf("review reply receipt has an invalid pull-request number")
	}
	if _, err := time.Parse(time.RFC3339Nano, r.PullRequestUpdatedAt); err != nil {
		return fmt.Errorf(
			"review reply receipt has an invalid pull-request updated-at floor",
		)
	}
	if !isObjectID(r.HeadOID) {
		return fmt.Errorf("review reply receipt has an invalid head OID")
	}
	for name, value := range map[string]string{
		"pull-request digest":     r.PullRequestDigest,
		"prior thread digest":     r.PriorThreadDigest,
		"reply body digest":       r.ReplyBodyDigest,
		"result thread digest":    r.ResultThreadDigest,
		"review inventory digest": r.ReviewInventoryDigest,
	} {
		if err := validateSHA256Digest("receipt "+name, value); err != nil {
			return err
		}
	}
	if err := validateOpaqueID("receipt thread ID", r.ThreadID); err != nil {
		return err
	}
	if err := validateOpaqueID("receipt reply comment ID", r.ReplyCommentID); err != nil {
		return err
	}
	if r.PriorThreadDigest == r.ResultThreadDigest {
		return fmt.Errorf("review reply receipt does not record an appended reply")
	}
	return nil
}

func parseCanonicalReviewReceiptTime(name, value string) (time.Time, error) {
	parsed, err := time.Parse(time.RFC3339Nano, value)
	if err != nil || parsed.Location() != time.UTC ||
		parsed.Format(time.RFC3339Nano) != value {
		return time.Time{}, fmt.Errorf(
			"review reply receipt has a non-canonical UTC %s",
			name,
		)
	}
	return parsed, nil
}

func (r reviewReplyReceipt) authorityWindow() (time.Time, time.Time, error) {
	issuedAt, err := parseCanonicalReviewReceiptTime("issued_at", r.IssuedAt)
	if err != nil {
		return time.Time{}, time.Time{}, err
	}
	expiresAt, err := parseCanonicalReviewReceiptTime("expires_at", r.ExpiresAt)
	if err != nil {
		return time.Time{}, time.Time{}, err
	}
	duration := expiresAt.Sub(issuedAt)
	if duration <= 0 || duration > reviewReplyAuthorityLimit {
		return time.Time{}, time.Time{}, fmt.Errorf(
			"review reply receipt authority must expire after issuance within %s",
			reviewReplyAuthorityLimit,
		)
	}
	return issuedAt, expiresAt, nil
}

func (r reviewReplyReceipt) validateAuthorityAt(now time.Time) error {
	issuedAt, expiresAt, err := r.authorityWindow()
	if err != nil {
		return err
	}
	if now.Before(issuedAt) {
		return fmt.Errorf("review reply receipt authority is not yet active")
	}
	if !now.Before(expiresAt) {
		return fmt.Errorf(
			"review reply receipt authority expired; leave a fresh reasoned reply " +
				"before resolving the thread",
		)
	}
	return nil
}

func (d *delivery) newReviewReplyReceipt(
	ctx context.Context,
	options reviewTargetOptions,
	threadID string,
	priorThreadDigest string,
	body string,
	inspection *reviewInspection,
) (reviewReplyReceipt, error) {
	if inspection == nil {
		return reviewReplyReceipt{}, fmt.Errorf("review reply inspection is absent")
	}
	if err := validateReviewInventoryUnique(inspection); err != nil {
		return reviewReplyReceipt{}, err
	}
	if inspection.PullRequest.ID != options.PullRequestID ||
		inspection.PullRequest.HeadRefOID != options.ExpectedHeadOID ||
		inspection.PullRequestExpectationDigest != options.ExpectedPullRequestDigest {
		return reviewReplyReceipt{}, fmt.Errorf(
			"review reply result has a different pull-request context",
		)
	}
	if inspection.PullRequest.UpdatedAt == "" {
		return reviewReplyReceipt{}, fmt.Errorf(
			"review reply result omitted the pull-request updated-at snapshot",
		)
	}
	thread, err := findReviewThread(inspection, threadID)
	if err != nil {
		return reviewReplyReceipt{}, err
	}
	if thread.IsResolved || len(thread.Comments) == 0 {
		return reviewReplyReceipt{}, fmt.Errorf(
			"review reply result does not contain an unresolved replied-to thread",
		)
	}
	if thread.ExpectationDigest != reviewThreadDigest(*thread) {
		return reviewReplyReceipt{}, fmt.Errorf(
			"review reply result contains an inconsistent thread digest",
		)
	}
	reply := thread.Comments[len(thread.Comments)-1]
	if normalizeText(reply.Body) != normalizeText(body) {
		return reviewReplyReceipt{}, fmt.Errorf(
			"review reply result does not contain the exact tool reply",
		)
	}
	fingerprint, err := d.repository.repositoryFingerprint(ctx)
	if err != nil {
		return reviewReplyReceipt{}, err
	}
	issuedAt := reviewReplyReceiptNow(ctx).UTC()
	receipt := reviewReplyReceipt{
		Schema:                reviewReplyReceiptSchema,
		IssuedAt:              issuedAt.Format(time.RFC3339Nano),
		ExpiresAt:             issuedAt.Add(reviewReplyAuthorityLimit).Format(time.RFC3339Nano),
		RepositoryFingerprint: fingerprint,
		RemoteRepository:      d.remoteRepository,
		Forge:                 d.forge.Name(),
		PullRequestID:         inspection.PullRequest.ID,
		PullRequestNumber:     inspection.PullRequest.Number,
		PullRequestDigest:     inspection.PullRequestExpectationDigest,
		PullRequestUpdatedAt:  inspection.PullRequest.UpdatedAt,
		ReviewInventoryDigest: reviewInventoryDigest(inspection),
		HeadOID:               inspection.PullRequest.HeadRefOID,
		ThreadID:              thread.ID,
		PriorThreadDigest:     priorThreadDigest,
		ReplyCommentID:        reply.ID,
		ReplyBodyDigest:       reviewReplyBodyDigest(reply.Body),
		ResultThreadDigest:    thread.ExpectationDigest,
	}
	if err := receipt.validate(); err != nil {
		return reviewReplyReceipt{}, err
	}
	return receipt, nil
}

func findReviewThread(
	inspection *reviewInspection,
	threadID string,
) (*reviewThread, error) {
	var result *reviewThread
	for index := range inspection.Threads {
		candidate := &inspection.Threads[index]
		if candidate.ID != threadID {
			continue
		}
		if result != nil {
			return nil, fmt.Errorf("review result contains duplicate thread %q", threadID)
		}
		result = candidate
	}
	if result == nil {
		return nil, fmt.Errorf("review result omitted thread %q", threadID)
	}
	return result, nil
}

func (d *delivery) writeReviewReplyReceipt(
	ctx context.Context,
	path string,
	receipt reviewReplyReceipt,
) error {
	absolute, err := d.receiptPath(ctx, path, false)
	if err != nil {
		return err
	}
	if err := receipt.validate(); err != nil {
		return err
	}
	contents, err := json.MarshalIndent(receipt, "", "  ")
	if err != nil {
		return fmt.Errorf("encode review reply receipt: %w", err)
	}
	contents = append(contents, '\n')
	if len(contents) > receiptFileLimit {
		return fmt.Errorf("review reply receipt exceeds 256 KiB")
	}
	temporary, err := os.CreateTemp(
		filepath.Dir(absolute),
		"."+filepath.Base(absolute)+".tmp-",
	)
	if err != nil {
		return fmt.Errorf("create atomic review reply receipt: %w", err)
	}
	temporaryPath := temporary.Name()
	cleanup := true
	defer func() {
		_ = temporary.Close()
		if cleanup {
			_ = os.Remove(temporaryPath)
		}
	}()
	if err := temporary.Chmod(0o600); err != nil {
		return fmt.Errorf("set review reply receipt permissions: %w", err)
	}
	if _, err := temporary.Write(contents); err != nil {
		return fmt.Errorf("write review reply receipt: %w", err)
	}
	if err := temporary.Sync(); err != nil {
		return fmt.Errorf("sync review reply receipt: %w", err)
	}
	if err := temporary.Close(); err != nil {
		return fmt.Errorf("close review reply receipt: %w", err)
	}
	if err := os.Rename(temporaryPath, absolute); err != nil {
		return fmt.Errorf("install review reply receipt atomically: %w", err)
	}
	cleanup = false
	return nil
}

func (d *delivery) readReviewReplyReceipt(
	ctx context.Context,
	path string,
) (reviewReplyReceipt, error) {
	absolute, err := d.receiptPath(ctx, path, true)
	if err != nil {
		return reviewReplyReceipt{}, err
	}
	return readReviewReplyReceiptFile(absolute)
}

func readReviewReplyReceiptFile(absolute string) (reviewReplyReceipt, error) {
	pathBefore, err := os.Lstat(absolute)
	if err != nil {
		return reviewReplyReceipt{}, fmt.Errorf("inspect review reply receipt: %w", err)
	}
	file, err := os.Open(absolute)
	if err != nil {
		return reviewReplyReceipt{}, fmt.Errorf("open review reply receipt: %w", err)
	}
	defer file.Close()
	openedBefore, err := file.Stat()
	if err != nil {
		return reviewReplyReceipt{}, fmt.Errorf("inspect opened review reply receipt: %w", err)
	}
	if !openedBefore.Mode().IsRegular() || openedBefore.Mode().Perm() != 0o600 ||
		!stableFileInfo(pathBefore, openedBefore) {
		return reviewReplyReceipt{}, fmt.Errorf(
			"review reply receipt changed while it was being opened",
		)
	}
	first, err := io.ReadAll(io.LimitReader(file, receiptFileLimit+1))
	if err != nil {
		return reviewReplyReceipt{}, fmt.Errorf("read review reply receipt: %w", err)
	}
	if len(first) > receiptFileLimit {
		return reviewReplyReceipt{}, fmt.Errorf("review reply receipt exceeds 256 KiB")
	}
	afterFirst, err := file.Stat()
	if err != nil {
		return reviewReplyReceipt{}, fmt.Errorf(
			"reinspect opened review reply receipt: %w",
			err,
		)
	}
	if !stableFileInfo(openedBefore, afterFirst) {
		return reviewReplyReceipt{}, fmt.Errorf(
			"review reply receipt changed while it was being read",
		)
	}
	if _, err := file.Seek(0, io.SeekStart); err != nil {
		return reviewReplyReceipt{}, fmt.Errorf("rewind review reply receipt: %w", err)
	}
	second, err := io.ReadAll(io.LimitReader(file, receiptFileLimit+1))
	if err != nil {
		return reviewReplyReceipt{}, fmt.Errorf("reread review reply receipt: %w", err)
	}
	openedAfter, err := file.Stat()
	if err != nil {
		return reviewReplyReceipt{}, fmt.Errorf("reinspect opened review reply receipt: %w", err)
	}
	pathAfter, err := os.Lstat(absolute)
	if err != nil {
		return reviewReplyReceipt{}, fmt.Errorf("reinspect review reply receipt path: %w", err)
	}
	if len(second) > receiptFileLimit || !bytes.Equal(first, second) ||
		!stableFileInfo(afterFirst, openedAfter) ||
		!stableFileInfo(openedAfter, pathAfter) ||
		pathAfter.Mode()&os.ModeSymlink != 0 ||
		int64(len(first)) != openedAfter.Size() {
		return reviewReplyReceipt{}, fmt.Errorf(
			"review reply receipt changed while it was being read",
		)
	}
	if err := validateReviewReplyReceiptJSON(first); err != nil {
		return reviewReplyReceipt{}, err
	}
	decoder := json.NewDecoder(bytes.NewReader(first))
	decoder.DisallowUnknownFields()
	var receipt reviewReplyReceipt
	if err := decoder.Decode(&receipt); err != nil {
		return reviewReplyReceipt{}, fmt.Errorf("decode review reply receipt: %w", err)
	}
	var extra any
	if err := decoder.Decode(&extra); err != io.EOF {
		if err == nil {
			return reviewReplyReceipt{}, fmt.Errorf(
				"review reply receipt contains multiple JSON values",
			)
		}
		return reviewReplyReceipt{}, fmt.Errorf(
			"finish decoding review reply receipt: %w",
			err,
		)
	}
	if err := receipt.validate(); err != nil {
		return reviewReplyReceipt{}, err
	}
	return receipt, nil
}

type consumedReviewReplyReceipt struct {
	directory       string
	movedPath       string
	parentDirectory string
}

// consumeReviewReplyReceipt atomically removes the verified receipt from its
// public path before the remote mutation. This prevents replay after an
// attempted resolution. It cannot reveal a provider-side resolve/unresolve
// that restored identical state before the first use of the receipt.
func (d *delivery) consumeReviewReplyReceipt(
	ctx context.Context,
	path string,
	expected reviewReplyReceipt,
) (*consumedReviewReplyReceipt, error) {
	absolute, err := d.receiptPath(ctx, path, true)
	if err != nil {
		return nil, err
	}
	current, err := readReviewReplyReceiptFile(absolute)
	if err != nil {
		return nil, err
	}
	if current != expected {
		return nil, fmt.Errorf("review reply receipt changed before consumption")
	}
	parent := filepath.Dir(absolute)
	directory, err := os.MkdirTemp(
		parent,
		"."+filepath.Base(absolute)+".consuming-",
	)
	if err != nil {
		return nil, fmt.Errorf("create review reply receipt consumption directory: %w", err)
	}
	movedPath := filepath.Join(directory, "receipt")
	if err := os.Rename(absolute, movedPath); err != nil {
		_ = os.Remove(directory)
		return nil, fmt.Errorf("consume review reply receipt atomically: %w", err)
	}
	consumed := &consumedReviewReplyReceipt{
		directory:       directory,
		movedPath:       movedPath,
		parentDirectory: parent,
	}
	moved, readErr := readReviewReplyReceiptFile(movedPath)
	if readErr != nil || moved != expected {
		cleanupErr := consumed.cleanup()
		if readErr == nil {
			readErr = fmt.Errorf("review reply receipt changed during consumption")
		}
		return nil, errors.Join(readErr, cleanupErr)
	}
	if _, err := os.Lstat(absolute); !errors.Is(err, os.ErrNotExist) {
		cleanupErr := consumed.cleanup()
		if err == nil {
			err = fmt.Errorf("review reply receipt path was recreated during consumption")
		}
		return nil, errors.Join(err, cleanupErr)
	}
	if err := syncReceiptDirectory(directory); err != nil {
		cleanupErr := consumed.cleanup()
		return nil, errors.Join(
			fmt.Errorf("sync consumed review reply receipt: %w", err),
			cleanupErr,
		)
	}
	if err := syncReceiptDirectory(parent); err != nil {
		cleanupErr := consumed.cleanup()
		return nil, errors.Join(
			fmt.Errorf("sync review reply receipt consumption: %w", err),
			cleanupErr,
		)
	}
	return consumed, nil
}

func (c *consumedReviewReplyReceipt) cleanup() error {
	var cleanupErrors []error
	if err := os.Remove(c.movedPath); err != nil && !errors.Is(err, os.ErrNotExist) {
		cleanupErrors = append(cleanupErrors, fmt.Errorf(
			"remove consumed review reply receipt: %w",
			err,
		))
	}
	if err := os.Remove(c.directory); err != nil && !errors.Is(err, os.ErrNotExist) {
		cleanupErrors = append(cleanupErrors, fmt.Errorf(
			"remove review reply receipt consumption directory: %w",
			err,
		))
	}
	if err := syncReceiptDirectory(c.parentDirectory); err != nil {
		cleanupErrors = append(cleanupErrors, fmt.Errorf(
			"sync review reply receipt cleanup: %w",
			err,
		))
	}
	return errors.Join(cleanupErrors...)
}

func validateReviewReplyReceiptJSON(contents []byte) error {
	topLevel := map[string]bool{
		"schema":                  true,
		"issued_at":               true,
		"expires_at":              true,
		"repository_fingerprint":  true,
		"remote_repository":       true,
		"forge":                   true,
		"pull_request_id":         true,
		"pull_request_number":     true,
		"pull_request_digest":     true,
		"pull_request_updated_at": true,
		"review_inventory_digest": true,
		"head_oid":                true,
		"thread_id":               true,
		"prior_thread_digest":     true,
		"reply_comment_id":        true,
		"reply_body_digest":       true,
		"result_thread_digest":    true,
	}
	remoteRepositoryFields := map[string]bool{
		"host":  true,
		"owner": true,
		"name":  true,
	}
	decoder := json.NewDecoder(bytes.NewReader(contents))
	var walk func(string) error
	walk = func(location string) error {
		token, err := decoder.Token()
		if err != nil {
			return err
		}
		delimiter, ok := token.(json.Delim)
		if !ok {
			return nil
		}
		switch delimiter {
		case '{':
			seen := map[string]bool{}
			for decoder.More() {
				keyToken, err := decoder.Token()
				if err != nil {
					return err
				}
				key, ok := keyToken.(string)
				if !ok {
					return fmt.Errorf("review reply receipt contains a non-string object key")
				}
				if seen[key] {
					return fmt.Errorf(
						"review reply receipt contains duplicate key %q",
						key,
					)
				}
				seen[key] = true
				allowed := map[string]bool(nil)
				switch location {
				case "":
					allowed = topLevel
				case "/remote_repository":
					allowed = remoteRepositoryFields
				}
				if allowed == nil || !allowed[key] {
					return fmt.Errorf(
						"review reply receipt contains non-canonical key %q",
						key,
					)
				}
				if err := walk(location + "/" + key); err != nil {
					return err
				}
			}
			closing, err := decoder.Token()
			if err != nil || closing != json.Delim('}') {
				return fmt.Errorf("review reply receipt contains an unterminated object")
			}
		case '[':
			return fmt.Errorf("review reply receipt contains an unexpected array")
		default:
			return fmt.Errorf("review reply receipt contains unexpected JSON structure")
		}
		return nil
	}
	if err := walk(""); err != nil {
		return fmt.Errorf("decode review reply receipt shape: %w", err)
	}
	if _, err := decoder.Token(); err != io.EOF {
		if err == nil {
			return fmt.Errorf("review reply receipt contains multiple JSON values")
		}
		return fmt.Errorf("finish decoding review reply receipt shape: %w", err)
	}
	return nil
}

func (d *delivery) validateReviewReplyReceiptContext(
	ctx context.Context,
	receipt reviewReplyReceipt,
	options reviewTargetOptions,
	pullRequest pullRequest,
	expectation reviewThreadExpectation,
) error {
	if err := receipt.validateAuthorityAt(reviewReplyReceiptNow(ctx)); err != nil {
		return err
	}
	fingerprint, err := d.repository.repositoryFingerprint(ctx)
	if err != nil {
		return err
	}
	if receipt.RepositoryFingerprint != fingerprint ||
		!sameRemoteRepository(receipt.RemoteRepository, d.remoteRepository) ||
		receipt.Forge != d.forge.Name() ||
		receipt.PullRequestID != options.PullRequestID ||
		receipt.PullRequestID != pullRequest.ID ||
		receipt.PullRequestNumber != pullRequest.Number ||
		receipt.PullRequestDigest != options.ExpectedPullRequestDigest ||
		receipt.PullRequestDigest !=
			reviewPullRequestDigest(d.remoteRepository, pullRequest) ||
		!reviewUpdatedAtAtOrAfter(
			receipt.PullRequestUpdatedAt,
			pullRequest.UpdatedAt,
		) ||
		receipt.HeadOID != options.ExpectedHeadOID ||
		receipt.HeadOID != pullRequest.HeadRefOID ||
		receipt.ThreadID != expectation.ThreadID ||
		receipt.ReplyCommentID != expectation.ExpectedLastCommentID ||
		receipt.ResultThreadDigest != expectation.ExpectedDigest {
		return fmt.Errorf(
			"review reply receipt does not match the exact repository, pull request, head, or thread state",
		)
	}
	return nil
}

func reviewUpdatedAtAtOrAfter(floor, current string) bool {
	floorTime, floorErr := time.Parse(time.RFC3339Nano, floor)
	currentTime, currentErr := time.Parse(time.RFC3339Nano, current)
	return floorErr == nil && currentErr == nil && !currentTime.Before(floorTime)
}

func validateOpaqueID(name, value string) error {
	if !utf8.ValidString(value) || value == "" ||
		strings.TrimSpace(value) != value ||
		strings.ContainsAny(value, "\x00\r\n\t") {
		return fmt.Errorf("%s must be a nonempty opaque ID", name)
	}
	return nil
}

func normalizeReviewers(input []string) ([]string, error) {
	if len(input) == 0 {
		return nil, fmt.Errorf("at least one --reviewer is required")
	}
	seen := make(map[string]bool, len(input))
	result := make([]string, 0, len(input))
	for _, candidate := range input {
		candidate = strings.TrimSpace(candidate)
		if !utf8.ValidString(candidate) || candidate == "" ||
			strings.ContainsAny(candidate, "\x00\r\n\t") {
			return nil, fmt.Errorf("reviewer accounts must be nonempty single-line values")
		}
		key := strings.ToLower(candidate)
		if seen[key] {
			return nil, fmt.Errorf("reviewer %q was supplied more than once", candidate)
		}
		seen[key] = true
		result = append(result, candidate)
	}
	return result, nil
}

func withCommentDisclaimer(body string) (string, error) {
	if !utf8.ValidString(body) {
		return "", fmt.Errorf("review reply body is not valid UTF-8")
	}
	body = normalizeText(body)
	if strings.TrimSpace(body) == "" {
		return "", fmt.Errorf("review reply body is empty")
	}
	lines := strings.Split(body, "\n")
	last := lines[len(lines)-1]
	for index, line := range lines {
		if strings.HasPrefix(strings.TrimSpace(line), "LLM-disclaimer:") &&
			(index != len(lines)-1 || line != commentDisclaimer) {
			return "", fmt.Errorf(
				"review reply body contains the wrong disclaimer or non-canonical padding",
			)
		}
	}
	if last == commentDisclaimer {
		if !hasSubstantiveReviewText(strings.Join(lines[:len(lines)-1], "\n")) {
			return "", fmt.Errorf("review reply body has no substantive content")
		}
		return body, nil
	}
	if !hasSubstantiveReviewText(body) {
		return "", fmt.Errorf("review reply body has no substantive content")
	}
	return body + "\n\n" + commentDisclaimer, nil
}

func requireReasonedToolComment(body string) error {
	if !utf8.ValidString(body) {
		return fmt.Errorf("the last review-thread comment is not valid UTF-8")
	}
	normalized := normalizeText(body)
	lines := strings.Split(normalized, "\n")
	if len(lines) < 2 || lines[len(lines)-1] != commentDisclaimer {
		return fmt.Errorf(
			"the last review-thread comment is not a tool reply with the exact disclaimer",
		)
	}
	reason := strings.TrimSpace(strings.Join(lines[:len(lines)-1], "\n"))
	if !hasSubstantiveReviewText(reason) {
		return fmt.Errorf("the last review-thread comment has no reasoned reply")
	}
	return nil
}

func hasSubstantiveReviewText(value string) bool {
	for _, character := range value {
		if unicode.IsLetter(character) || unicode.IsNumber(character) {
			return true
		}
	}
	return false
}
