load("@rules_docs//docs:defs.bzl", "docs_filegroup")
load("//tools/ansible/main/bzl:al_ansible_role.bzl", "al_ansible_role")

docs_filegroup(
    name = "docs",
    srcs = glob(["*.md"]),
    visibility = ["//projects/ansible_collection/roles:__pkg__"],
    deps = [
        ":role.docs",
    ],
)

al_ansible_role(
    name = "role",
    srcs = [
        "//third_party/io_k3s_k3s:bin",
        "//third_party/io_k3s_k3s:install",
    ] + glob(["**"]),
    renames = {
        "//third_party/io_k3s_k3s:bin": "files/k3s",
        "//third_party/io_k3s_k3s:install": "files/k3s_install",
    },
    visibility = ["//:__subpackages__"],
)
