[[Submissions]]
  Id = 1018285235
  StatusDisplay = "Accepted"
  Lang = "python3"
  QuestionId = 238
  TitleSlug = "product-of-array-except-self"
  Code = "class Solution:\n    def productExceptSelf(self, nums: List[int]) -> List[int]:\n        nums_count = len(nums)\n        result = [1] * nums_count\n        prefix = 1\n        postfix = 1\n        for i in range(nums_count):\n            result[i] *= prefix\n            prefix *= nums[i]\n            result[nums_count-i-1] *= postfix\n            postfix *= nums[nums_count-i-1]\n        \n        return result"
  Title = "Product of Array Except Self"
  Url = "/submissions/detail/1018285235/"
  LangName = "Python3"
  Timestamp = 1691744510
  Status = 10
  Runtime = "199 ms"
  IsPending = "Not Pending"
  Memory = "24.2 MB"
  CompareResult = "1111111111111111111111"
  HasNotes = false
  FlagType = 1
