[[Submissions]]
  Id = 1717305233
  StatusDisplay = "Accepted"
  Lang = "python3"
  QuestionId = 776
  TitleSlug = "n-ary-tree-postorder-traversal"
  Code = "\"\"\"\n# Definition for a Node.\nclass Node:\n    def __init__(self, val: Optional[int] = None, children: Optional[List['Node']] = None):\n        self.val = val\n        self.children = children\n\"\"\"\n\nclass Solution:\n    def postorder(self, root: 'Node') -> List[int]:\n        if root is None:\n            return []\n        res = []\n        queue = [root]\n        while queue:\n            node = queue.pop()\n            res.append(node.val)\n            for child in node.children:\n                queue.append(child)\n        res.reverse()\n        return res"
  Title = "N-ary Tree Postorder Traversal"
  Url = "/submissions/detail/1717305233/"
  LangName = "Python3"
  Timestamp = 1753891198
  Status = 10
  Runtime = "50 ms"
  IsPending = "Not Pending"
  Memory = "19.2 MB"
  CompareResult = "11111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
