apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-gateway-websecure-tls
  namespace: traefik
spec:
  issuerRef:
    name: vault
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - flux.alwaldend.com
    - "*.flux.alwaldend.com"
  privateKey:
    algorithm: RSA
    size: 4096
  secretName: traefik-gateway-websecure-tls
