load("@rules_docs//docs:defs.bzl", "docs_filegroup")
load("//tools/git/main/bzl:al_git_info_file.bzl", "al_git_info_file")

docs_filegroup(
    name = "docs",
    srcs = glob(["*.md"]),
    visibility = ["//tools:__pkg__"],
    deps = [
        "//tools/git/main/bzl:docs",
        "//tools/git/main/proto:docs",
    ],
)

alias(
    name = "git",
    actual = "@com_alwaldend_src_tools_git//:git",
    visibility = ["//:__subpackages__"],
)

al_git_info_file(
    name = "git_info",
    visibility = ["//:__subpackages__"],
)
