load("//tools/docs:defs.bzl", "docs_filegroup")
load("//tools/terraform:defs.bzl", "terraform_binary_map", "terraform_test_map")

docs_filegroup(
    name = "docs",
    srcs = glob(["*.md"]),
    visibility = ["//users/simeonwarren/t3code:__pkg__"],
    deps = subpackages(
        include = ["*"],
        allow_empty = True,
    ),
)

_CONFIGS = ["//users/simeonwarren/t3code:al"]

_RUN_ARGS = [
    "--plugin_label",
    "tf=setup",
]

_DATA = glob(["*.tf"]) + [
    ".terraform.lock.hcl",
    "//users/simeonwarren/t3code/ansible:inventory",
    "//infra/pve/ansible:cloud_init",
    "//tools/vault/tf_backend",
    "//tools/vault/injector",
]

terraform_binary_map(
    name = "tf_setup",
    configs = _CONFIGS,
    data = _DATA,
    run_args = _RUN_ARGS,
)

terraform_test_map(
    name = "tf_tests",
    configs = _CONFIGS,
    data = _DATA,
)
