note_id = 1520716966743
guid = "C20~F)bwL#"
note_type_id = 1496733135171
note_type = "chinese"
tags = ["A2", "Adverbs", "Comparisons"]

[[cards]]
id = 1520716972607
ordinal = 0

[fields]
article-title = 'Comparing "bu" and "mei"'
english = 'Is your girlfriend not going with you?'
example-sentence = ''
example-type = ''
grammar-construct = 'Subj. + 不 + Verb'
hanzi = '你女朋友不跟你一起去吗？'
notes = ''
pinyin = 'Nǐ nǚpéngyou bù gēn nǐ yīqǐ qù ma?'
source = 'https://resources.allsetlearning.com/chinese/grammar/ASGRJ1BI'
