load("@rules_docs//docs:defs.bzl", "docs_filegroup")
load("@rules_go//go:def.bzl", "go_binary", "go_library")

docs_filegroup(
    name = "docs",
    srcs = glob(["*.md"]),
    visibility = ["//infra/threexui:__pkg__"],
    deps = subpackages(
        include = ["*"],
        allow_empty = True,
    ),
)

go_library(
    name = "sub_lib",
    srcs = ["main.go"],
    importpath = "git.alwaldend.com/alwaldend/src/infra/threexui/sub",
    visibility = ["//:__subpackages__"],
)

go_binary(
    name = "sub",
    embed = [":sub_lib"],
    visibility = ["//:__subpackages__"],
)
