note_id = 1520716968460
guid = "d.W7N#sZU6"
note_type_id = 1496733135171
note_type = "chinese"
tags = ["B1", "Complements", "Grammatical_Structures"]

[[cards]]
id = 1520716974324
ordinal = 0

[fields]
article-title = 'Direction complement'
english = 'When are you coming back?'
example-sentence = ''
example-type = ''
grammar-construct = 'Verb + 来 / 去'
hanzi = '你什么时候回来？'
notes = ''
pinyin = 'Nǐ shénme shíhou huílái?'
source = 'https://resources.allsetlearning.com/chinese/grammar/ASG8LWBJ'
