[[Submissions]]
  Id = 1087553185
  StatusDisplay = "Accepted"
  Lang = "python3"
  QuestionId = 34
  TitleSlug = "find-first-and-last-position-of-element-in-sorted-array"
  Code = "class Solution:\n    def searchRange(self, nums: List[int], target: int) -> List[int]:\n        def binary_search(nums, target, left):\n            low, high = 0, len(nums) - 1\n            index = -1\n            while low <= high:\n                mid = (low + high) // 2\n                if nums[mid] == target:\n                    index = mid\n                    if left:\n                        high = mid - 1\n                    else:\n                        low = mid + 1\n                elif nums[mid] < target:\n                    low = mid + 1\n                else:\n                    high = mid - 1\n            return index\n\n        left_index = binary_search(nums, target, left=True)\n        right_index = binary_search(nums, target, left=False)\n\n        return [left_index, right_index]"
  Title = "Find First and Last Position of Element in Sorted Array"
  Url = "/submissions/detail/1087553185/"
  LangName = "Python3"
  Timestamp = 1698671798
  Status = 10
  Runtime = "82 ms"
  IsPending = "Not Pending"
  Memory = "17.7 MB"
  CompareResult = "1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
