[[Submissions]]
  Id = 1719828214
  StatusDisplay = "Accepted"
  Lang = "python3"
  QuestionId = 1041
  TitleSlug = "available-captures-for-rook"
  Code = "class Solution:\n    def numRookCaptures(self, board: List[List[str]]) -> int:\n        bishop_row, bishop_col = -1, -1\n        length = len(board)\n        delta = (\n            (0, 1), (0, -1), (1, 0), (-1, 0)            \n        )\n        for row in range(length):\n            for col in range(length):\n                if board[row][col] == \"R\":\n                    bishop_row, bishop_col = row, col\n                    break\n            if bishop_row != -1:\n                break\n        count = 0\n        for delta_row, delta_col in delta:\n            row, col = bishop_row, bishop_col\n            while 0 <= row < length and 0 <= col < length:\n                char = board[row][col]\n                if char == \"p\":\n                    count += 1\n                    break\n                elif char == \"B\":\n                    break\n                row, col = row + delta_row, col + delta_col\n        return count"
  Title = "Available Captures for Rook"
  Url = "/submissions/detail/1719828214/"
  LangName = "Python3"
  Timestamp = 1754070593
  Status = 10
  Runtime = "0 ms"
  IsPending = "Not Pending"
  Memory = "18 MB"
  CompareResult = "111111111111111111111111"
  HasNotes = false
  FlagType = 1
