- name: Deploy Host Bot proxy
  hosts: host_bot
  force_handlers: true
  become: true
  tasks:
    - name: Install firewalld
      ansible.builtin.package:
        name: firewalld
        state: present
    - name: Open firewall ports
      loop:
        - 22/tcp
        - 80/tcp
        - 443/tcp
      ansible.posix.firewalld:
        port: "{{ item }}"
        permanent: true
        immediate: true
        offline: true
        state: enabled
    - name: Enable firewalld
      ansible.builtin.systemd_service:
        name: firewalld
        enabled: true
        state: started
    - name: Setup CA
      ansible.builtin.import_role:
        name: alwaldend.main.install_ca
    - name: Setup Traefik
      ansible.builtin.import_role:
        name: alwaldend.main.traefik
