- name: Deploy Host Bot proxy
  hosts: host_bot
  force_handlers: true
  become: true
  tasks:
    - name: Setup CA
      ansible.builtin.import_role:
        name: alwaldend.main.install_ca
    - name: Setup Traefik
      ansible.builtin.import_role:
        name: alwaldend.main.traefik
