load("@rules_docs//docs:defs.bzl", "docs_filegroup")
load("//tools/terraform:defs.bzl", "terraform_binary_map", "terraform_test_map")

_DATA = [
    ".terraform.lock.hcl",
] + glob(["*.tf"])

terraform_binary_map(
    name = "tf",
    configs = ["//infra/xcp_ng:al"],
    data = _DATA + [
        "//infra/xcp_ng/cmd/xo_config",
        "//tools/vault/injector",
        "//tools/vault/tf_backend",
    ],
    run_args = [
        "--plugin_label",
        "xcp_ng_tf=1",
        "--plugin_label",
        "xoa=1",
        "--plugin_label",
        "vault_env=xcp_ng",
    ],
)

terraform_test_map(
    name = "tf_tests",
    data = _DATA,
)

docs_filegroup(
    name = "docs",
    visibility = ["//infra/xcp_ng:__pkg__"],
)
