load("@rules_docs//docs:defs.bzl", "docs_filegroup")
load("//tools/terraform:defs.bzl", "terraform_binary_map", "terraform_target_binary_map", "terraform_test_map")

_CONFIGS = ["//infra/xcp_ng:al"]

_DATA = [
    ".terraform.lock.hcl",
    "//infra/xcp_ng:dnsconfig",
    "//projects/tf_modules/dns_records:dns_records",
] + glob(["*.tf"])

_RUNTIME_DATA = _DATA + [
    "//infra/xcp_ng/cmd/xo_config",
    "//tools/vault/injector",
    "//tools/vault/tf_backend",
]

terraform_binary_map(
    name = "tf",
    configs = _CONFIGS,
    data = _RUNTIME_DATA,
    run_args = [
        "--plugin_label",
        "xcp_ng_tf=1",
        "--plugin_label",
        "xoa=1",
        "--plugin_label",
        "vault_env=xcp_ng",
    ],
)

terraform_target_binary_map(
    name = "dns",
    configs = _CONFIGS,
    data = _RUNTIME_DATA,
    run_args = [
        "--plugin_label",
        "dns=1",
    ],
    target = "module.dns",
)

terraform_test_map(
    name = "tf_tests",
    data = _DATA,
)

docs_filegroup(
    name = "docs",
    visibility = ["//infra/xcp_ng:__pkg__"],
)
