[[Submissions]]
  Id = 1095852311
  StatusDisplay = "Accepted"
  Lang = "golang"
  QuestionId = 1866
  TitleSlug = "restore-the-array-from-adjacent-pairs"
  Code = "func restoreArray(adjacentPairs [][]int) []int {\n    // [[2,1],[3,4],[3,2]]\n    // 1: [2]\n    // 2: [1, 3]\n    // 3: [2, 4]\n    // 4: [3]\n    // Output: [1,2,3,4]\n    graph := map[int][]int{}\n    for _, pair := range adjacentPairs {\n        num1, num2 := pair[0], pair[1]\n        graph[num1] = append(graph[num1], num2)\n        graph[num2] = append(graph[num2], num1)\n    }\n    length := len(adjacentPairs) + 1\n    ans := make([]int, length)\n    for node, edges := range graph {\n        if len(edges) == 1 {\n            ans[0], ans[1] = node, edges[0]\n            break\n        }\n    }\n    for i := 2; i < length; i++ {\n        cur, prev := ans[i-1], ans[i-2]\n        for _, target := range graph[cur] {\n            if target != prev {\n                ans[i] = target\n            }\n        }\n    }\n    return ans\n}"
  Title = "Restore the Array From Adjacent Pairs"
  Url = "/submissions/detail/1095852311/"
  LangName = "Go"
  Timestamp = 1699611896
  Status = 10
  Runtime = "184 ms"
  IsPending = "Not Pending"
  Memory = "34.6 MB"
  CompareResult = "1111111111111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
