note_id = 1520716967502
guid = "sZf2r+uw(n"
note_type_id = 1496733135171
note_type = "chinese"
tags = ["AuxiliaryWords", "B1", "Parts_of_Speech"]

[[cards]]
id = 1520716973366
ordinal = 0

[fields]
article-title = 'Non-exhaustive lists with "dengdeng"'
english = 'Food safety, environmental protection, peace and so on are all hot topics.'
example-sentence = ''
example-type = ''
grammar-construct = 'A1，A2 ⋯⋯ 等 + [Category] + Predicate'
hanzi = '食品安全、环保、和平等话题都是热点话题。'
notes = ''
pinyin = 'Shípǐn ānquán, huánbǎo, hépíng děng huàtí dōu shì rèdiǎn huàtí.'
source = 'https://resources.allsetlearning.com/chinese/grammar/ASGF763H'
