note_id = 1520716967464
guid = "mc@jH15UWy"
note_type_id = 1496733135171
note_type = "chinese"
tags = ["AuxiliaryWords", "B1", "Parts_of_Speech"]

[[cards]]
id = 1520716973328
ordinal = 0

[fields]
article-title = 'Non-exhaustive lists with "dengdeng"'
english = 'Watermelons, pineapples, apples, grapes and so on are all the fruits that I like.'
example-sentence = ''
example-type = ''
grammar-construct = 'A1，A2⋯⋯等 / 等等'
hanzi = '西瓜、菠萝、苹果、葡萄等等都是我喜欢的水果。'
notes = ''
pinyin = 'Xīguā, bōluó, píngguǒ, pútáo děngděng dōu shì wǒ xǐhuan de shuǐguǒ.'
source = 'https://resources.allsetlearning.com/chinese/grammar/ASGF763H'
