load("@rules_docs//docs:defs.bzl", "docs_filegroup")
load("@rules_pkg//pkg:mappings.bzl", "pkg_files")

docs_filegroup(
    name = "docs",
    srcs = glob(["*.md"]),
    visibility = ["//projects/ansible_collection:__pkg__"],
)

pkg_files(
    name = "playbooks",
    srcs = glob(["*.yaml"]),
    prefix = "playbooks",
    visibility = ["//:__subpackages__"],
)
