load("@rules_docs//docs:defs.bzl", "docs_filegroup")
load("//tools/bzl/main/bzl:al_bzl_library_map.bzl", "al_bzl_library_map")

docs_filegroup(
    name = "docs",
    srcs = glob(["*.md"]),
    visibility = ["//tools/install_file:__pkg__"],
    deps = [
        ":libs.stardoc",
    ],
)

al_bzl_library_map(
    name = "libs",
    libs = {
        "al_install_file": [
            "@rules_python//python:py_binary_bzl",
        ],
    },
    visibility = ["//:__subpackages__"],
)
