note_id = 1520716970575
guid = "jlL}`+XT60"
note_type_id = 1496733135171
note_type = "chinese"
tags = ["B2", "Grammatical_Structures", "Letalone"]

[[cards]]
id = 1520716976439
ordinal = 0

[fields]
article-title = 'Expressing "let alone" with "bie shuo"'
english = "Don't even mention baijiu, I can't even stand the taste of beer."
example-sentence = ''
example-type = ''
grammar-construct = '别说 + A ， 连  / 就是+ B + 也 / 都 + Verb'
hanzi = '别说白酒，连啤酒的味道我都受不了。'
notes = ''
pinyin = ''
source = 'https://resources.allsetlearning.com/chinese/grammar/ASGR6Q2J'
