note_id = 1520716965970
guid = "ySr;A8Ylpb"
note_type_id = 1496733135171
note_type = "chinese"
tags = ["A2", "Conjunctions", "Parts_of_Speech"]

[[cards]]
id = 1520716971834
ordinal = 0

[fields]
article-title = 'Expressing "with" with "gen"'
english = 'I want to meet with you.'
example-sentence = ''
example-type = 'valid'
grammar-construct = 'Subj. + 跟 + Person + 一起 + Verb + Obj.'
hanzi = '我要跟你见面。'
notes = ''
pinyin = 'Wǒ yào gēn nǐ jiànmiàn.'
source = 'https://resources.allsetlearning.com/chinese/grammar/ASGSZ0HP'
