note_id = 1520716967510
guid = "G8>xtC-,F("
note_type_id = 1496733135171
note_type = "chinese"
tags = ["B1", "Conjunctions", "Parts_of_Speech"]

[[cards]]
id = 1520716973374
ordinal = 0

[fields]
article-title = 'Expressing "how about" with "yaobu"'
english = "How about we go together? It's no fun to go by myself."
example-sentence = ''
example-type = ''
grammar-construct = '要不 + Option B + 吧 ，Reason / Situation'
hanzi = '要不我们一起去吧，一个人去没意思。'
notes = ''
pinyin = 'Yàobù wǒmen yīqǐ qù ba, yīgèrén qù méi yìsi.'
source = 'https://resources.allsetlearning.com/chinese/grammar/ASGDFQP7'
