[[Submissions]]
  Id = 1710795194
  StatusDisplay = "Accepted"
  Lang = "python3"
  QuestionId = 1560
  TitleSlug = "number-of-students-doing-homework-at-a-given-time"
  Code = "class Solution:\n    def busyStudent(self, startTime: List[int], endTime: List[int], queryTime: int) -> int:\n        count = 0\n        for start, end in zip(startTime, endTime):\n            if queryTime >= start and queryTime <= end:\n                count += 1\n        return count"
  Title = "Number of Students Doing Homework at a Given Time"
  Url = "/submissions/detail/1710795194/"
  LangName = "Python3"
  Timestamp = 1753436259
  Status = 10
  Runtime = "0 ms"
  IsPending = "Not Pending"
  Memory = "17.7 MB"
  CompareResult = "111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
