[[Submissions]]
  Id = 1248311894
  StatusDisplay = "Accepted"
  Lang = "golang"
  QuestionId = 165
  TitleSlug = "compare-version-numbers"
  Code = "func compareVersion(version1 string, version2 string) int {\n\n\trev1 := strings.Split(version1, \".\")\n\trev2 := strings.Split(version2, \".\")\n    // fmt.Println(rev1, rev2)\n\n\trevInt1 := make([]int, len(rev1))\n\trevInt2 := make([]int, len(rev2))\n\n\tfor i := 0; i < len(rev1); i++ {\n\t\trevInt1[i], _ = strconv.Atoi(rev1[i])\n\t}\n\tfor i := 0; i < len(rev2); i++ {\n\t\trevInt2[i], _ = strconv.Atoi(rev2[i])\n\t}\n    // fmt.Println(revInt1, revInt2)\n\n\ti := 0\n\tj := 0\n\n\tfor i < len(revInt1) && j < len(revInt2) {\n\n\t\tif revInt1[i] < revInt2[j] {\n\t\t\treturn -1\n\t\t} else if revInt1[i] > revInt2[j] {\n\t\t\treturn 1\n\t\t}\n\t\ti++\n\t\tj++\n\t}\n\n\tfor i < len(revInt1) {\n\t\tif revInt1[i] > 0 {\n\t\t\treturn 1\n\t\t}\n\t\ti++\n\t}\n\tfor j < len(revInt2) {\n\t\tif revInt2[j] > 0 {\n\t\t\treturn -1\n\t\t}\n\t\tj++\n\t}\n\treturn 0\n}\n"
  Title = "Compare Version Numbers"
  Url = "/submissions/detail/1248311894/"
  LangName = "Go"
  Timestamp = 1714747311
  Status = 10
  Runtime = "1 ms"
  IsPending = "Not Pending"
  Memory = "2.2 MB"
  CompareResult = "111111111111111111111111111111111111111111111111111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
