[[Submissions]]
  Id = 692736039
  StatusDisplay = "Accepted"
  Lang = "golang"
  QuestionId = 1018
  TitleSlug = "largest-perimeter-triangle"
  Code = "\nfunc largestPerimeter(numbers []int) int {\n\tsort.Ints(numbers)\n\tfor index := len(numbers) - 1; index > 1; index-- {\n\t\tcurrent, sum_previous := numbers[index], numbers[index-1]+numbers[index-2]\n\t\tif current >= sum_previous {\n\t\t\tcontinue\n\t\t}\n\t\treturn current + sum_previous\n\t}\n\treturn 0\n}"
  Title = "Largest Perimeter Triangle"
  Url = "/submissions/detail/692736039/"
  LangName = "Go"
  Timestamp = 1651635569
  Status = 10
  Runtime = "57 ms"
  IsPending = "Not Pending"
  Memory = "6.9 MB"
  CompareResult = "111111111111111111111111111111111111111111111111111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
