load("@rules_docs//docs:defs.bzl", "docs_filegroup")
load("@rules_oci//oci:defs.bzl", "oci_image")

docs_filegroup(
    name = "docs",
    srcs = select({
        "//tools/bazel_configs:harbor": [
            "README.md",
            ":image_index_json_cp",
        ],
        "//conditions:default": [],
    }),
    visibility = ["//projects/cgit/images:__pkg__"],
)

oci_image(
    name = "image",
    base = "@io_docker_library_alpine",
    target_compatible_with = select({
        "//tools/bazel_configs:harbor": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
)
