[[Submissions]]
  Id = 1087485265
  StatusDisplay = "Accepted"
  Lang = "golang"
  QuestionId = 102
  TitleSlug = "binary-tree-level-order-traversal"
  Code = "/**\n * Definition for a binary tree node.\n * type TreeNode struct {\n *     Val int\n *     Left *TreeNode\n *     Right *TreeNode\n * }\n */\nfunc levelOrder(root *TreeNode) [][]int {\n    queue, answer := []*TreeNode{root}, [][]int{}\n\n    for length := len(queue); length != 0; length = len(queue) {\n        answerRow := []int{}\n        for i := 0; i < length; i++ {\n            node := queue[0]\n            queue = queue[1:]\n            if node == nil {\n                continue\n            }\n            answerRow = append(answerRow, node.Val)\n            queue = append(queue, node.Left, node.Right)\n        }\n        if len(answerRow) != 0 {\n            answer = append(answer, answerRow)\n        }\n    }\n\n    return answer\n}"
  Title = "Binary Tree Level Order Traversal"
  Url = "/submissions/detail/1087485265/"
  LangName = "Go"
  Timestamp = 1698663563
  Status = 10
  Runtime = "3 ms"
  IsPending = "Not Pending"
  Memory = "3.6 MB"
  CompareResult = "11111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
