load("@rules_docs//docs:defs.bzl", "docs_filegroup")

filegroup(
    name = "res",
    srcs = glob(
        ["**"],
        exclude = [
            "BUILD.bazel",
            "README.md",
        ],
    ),
    visibility = ["//:__subpackages__"],
)

docs_filegroup(
    name = "docs",
    srcs = glob(["*.md"]),
    visibility = ["//projects/android_launcher:__pkg__"],
)
