note_id = 1520716965706
guid = "L1&LjR6Mp4"
note_type_id = 1496733135171
note_type = "chinese"
tags = ["A2", "Adverbs", "Parts_of_Speech"]

[[cards]]
id = 1520716971570
ordinal = 0

[fields]
article-title = 'Expressing "already" with "yijing"'
english = 'The baby can already speak.'
example-sentence = ''
example-type = ''
grammar-construct = '已经 + [Verb Phrase] + 了'
hanzi = '宝宝已经会说话了。'
notes = 'with a verb phrase'
pinyin = 'Bǎobao yǐjīng huì shuōhuà le.'
source = 'https://resources.allsetlearning.com/chinese/grammar/ASGNXI27'
