note_id = 1520716969638
guid = "FJMHahuDhO"
note_type_id = 1496733135171
note_type = "chinese"
tags = ["Adverbs", "B2", "Parts_of_Speech"]

[[cards]]
id = 1520716975502
ordinal = 0

[fields]
article-title = 'Assessing situations with "kanlai"'
english = "It seems he's not coming. It's already so late."
example-sentence = ''
example-type = ''
grammar-construct = '看来 + Perspective'
hanzi = '看来他不来了，都这么晚了。'
notes = ''
pinyin = ''
source = 'https://resources.allsetlearning.com/chinese/grammar/ASGJPQ0Q'
