apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
  - ../../../../projects/kustomization/traefik/remote
patches:
  - target:
      kind: Certificate
      group: cert-manager.io
      name: traefik-gateway-websecure-tls
    patch: |
      - op: replace
        path: /spec/commonName
        value: flux.alwaldend.com
      - op: replace
        path: /spec/dnsNames
        value:
          - flux.alwaldend.com
          - "*.flux.alwaldend.com"
