[[Submissions]]
  Id = 1000160504
  StatusDisplay = "Accepted"
  Lang = "python3"
  QuestionId = 66
  TitleSlug = "plus-one"
  Code = "class Solution:\n    def plusOne(self, digits: List[int]) -> List[int]:\n        carry = 1\n        for i in reversed(range(len(digits))):\n            new_digit = digits[i] + carry\n            if new_digit > 9:\n                carry = 1\n                new_digit %= 10\n            else:\n                carry = 0\n            digits[i] = new_digit\n        \n        if carry:\n            digits.insert(0, carry)\n        \n        return digits"
  Title = "Plus One"
  Url = "/submissions/detail/1000160504/"
  LangName = "Python3"
  Timestamp = 1689942805
  Status = 10
  Runtime = "42 ms"
  IsPending = "Not Pending"
  Memory = "16.3 MB"
  CompareResult = "111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
