load("@bazel_skylib//rules:build_test.bzl", "build_test")
load("@rules_docs//docs:defs.bzl", "docs_filegroup")

build_test(
    name = "build_test",
    targets = [
        "@com_alwaldend_com_github_infinitimeorg_infinitime//:dfu",
    ],
)

docs_filegroup(
    name = "docs",
    srcs = glob(["*.md"]),
    visibility = ["//projects:__pkg__"],
    deps = [
        "//projects/infinitime/releases:docs",
    ],
)
