[[Submissions]]
  Id = 1091200359
  StatusDisplay = "Accepted"
  Lang = "golang"
  QuestionId = 106
  TitleSlug = "construct-binary-tree-from-inorder-and-postorder-traversal"
  Code = "func buildTree(inorder []int, postorder []int) *TreeNode {\n\tn := len(postorder)\n\tif n == 0 {\n\t\treturn nil\n\t}\n\n\tpivotId := 0\n\tfor pivotId < n && inorder[pivotId] != postorder[n-1] {\n\t\tpivotId++\n\t}\n\n\troot := new(TreeNode)\n\troot.Val = postorder[n-1]\n\troot.Left = buildTree(inorder[:pivotId], postorder[:pivotId])\n\troot.Right = buildTree(inorder[pivotId+1:], postorder[pivotId:n-1])\n\treturn root\n}\n"
  Title = "Construct Binary Tree from Inorder and Postorder Traversal"
  Url = "/submissions/detail/1091200359/"
  LangName = "Go"
  Timestamp = 1699093649
  Status = 10
  Runtime = "7 ms"
  IsPending = "Not Pending"
  Memory = "3.7 MB"
  CompareResult = "1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
