note_id = 1634427796417
guid = "kM+XfmV@=9"
note_type_id = 1630447360003
note_type = "python-basic-and-reversed"
tags = []

[[cards]]
id = 1634427796419
ordinal = 0

[fields]
additional-info = ''
answer = '<b>Keyword</b> to define a new class.'
example = ''
question = '<b>Keyword: </b>class'
version = ''
with-options = ''
