note_id = 1634431332889
guid = "L!GthvP)$R"
note_type_id = 1630447360003
note_type = "python-basic-and-reversed"
tags = []

[[cards]]
id = 1634431332891
ordinal = 0

[fields]
additional-info = ''
answer = '<b>Keyword</b> used to include code from other modules.'
example = ''
question = '<b>Keyword:</b> import'
version = ''
with-options = ''
