note_id = 1634432593401
guid = "zM@-=jP_iD"
note_type_id = 1630447360003
note_type = "python-basic-and-reversed"
tags = []

[[cards]]
id = 1634432593401
ordinal = 0

[fields]
additional-info = ''
answer = '<b>Keyword</b> used to exit a function and return a value.'
example = ''
question = '<b>Keyword:</b> return&nbsp;'
version = ''
with-options = ''
