note_id = 1634431744434
guid = "hoel?E|;BD"
note_type_id = 1630447360003
note_type = "python-basic-and-reversed"
tags = []

[[cards]]
id = 1634431744435
ordinal = 0

[fields]
additional-info = ''
answer = '<b>Keyword</b> for the ! logical operator. Evaluates False to True, and True to False.'
example = ''
question = '<b>Keyword:</b> not'
version = ''
with-options = ''
