## hardening
ssh_allow_tcp_forwarding: local
sysctl_overwrite:
  net.ipv4.ip_forward: 1
  net.ipv6.conf.all.forwarding: 1

## firewall
firewall_allow_port_from:
  - src: "any"
    port: 443
    comment: Any 443
  - src: "any"
    port: 22
    comment: ssh

## k3s
k3s_config:
  cluster-init: true
  token: "{{ lookup('ansible.builtin.env', 'RANCHER_ALWALDEND_COM_K3S_TOKEN') | mandatory }}"
