note_id = 1520716968396
guid = "kok2#>+A-b"
note_type_id = 1496733135171
note_type = "chinese"
tags = ["B1", "Grammatical_Structures", "IfStatements"]

[[cards]]
id = 1520716974260
ordinal = 0

[fields]
article-title = 'Expressing "if…, then…" with "ruguo…, jiu…"'
english = 'If you go, tell her I say hello.'
example-sentence = ''
example-type = ''
grammar-construct = 'Statement + 的话，(就) Result'
hanzi = '你去的话，帮我跟她问好。'
notes = ''
pinyin = 'Nǐ qù de huà, bāng wǒ gēn tā wènhǎo.'
source = 'https://resources.allsetlearning.com/chinese/grammar/ASGGIVT0'
