load("@bazel_skylib//lib:shell.bzl", "shell")
load("@rules_pkg//pkg:providers.bzl", "PackageFilegroupInfo", "PackageFilesInfo")
load("//tools/make_install/main/bzl:al_make_install_filegroup_info.bzl", "AlMakeInstallFilegroupInfo")

_HEADER = """
# Autogenerated, do not edit

.PHONY: help
help: ## Show help
\t@sed -ne '/@sed/!s/## //p' $(MAKEFILE_LIST)

.PHONY: install
install: ## Install files from the archive

.PHONY: diff
diff: ## Show diff between archive files and system files
"""

_FILEGROUP_HEADER = """
# Targets for {filegroup_origin}

.PHONY: {filegroup_install}
install: {filegroup_install}
{filegroup_install}: ## Install {filegroup_prefix} files

.PHONY: {filegroup_diff}
diff: {filegroup_diff}
{filegroup_diff}: ## Diff {filegroup_prefix} files
"""

_TARGET = """
.PHONY: {install_name}
{filegroup_install}: {install_name}
{install_name}:
\tinstall {install_args} "{src}" "{dest}"

.PHONY: {diff_name}
{filegroup_diff}: {diff_name}
{diff_name}:
\tdiff {diff_args} "{src}" "{dest}" || true
"""

def _impl(ctx):
    makefile = ctx.actions.declare_file("{}.Makefile".format(ctx.label.name))
    package_files_info = PackageFilesInfo(
        attributes = {},
        dest_src_map = {"Makefile": makefile},
    )
    pkg_files = [(package_files_info, ctx.label)]
    pkg_dirs = []
    pkg_symlinks = []
    content = [_HEADER]
    filegroups = []
    for src in ctx.attr.srcs:
        filegroups.append(src[AlMakeInstallFilegroupInfo])
        filegroups.extend(src[AlMakeInstallFilegroupInfo].deps.to_list())

    for filegroup in filegroups:
        filegroup_install = "install/{}".format(filegroup.pkg_prefix)
        filegroup_diff = "diff/{}".format(filegroup.pkg_prefix)
        content.append(_FILEGROUP_HEADER.format(
            filegroup = filegroup,
            filegroup_origin = filegroup.origin,
            filegroup_install = filegroup_install,
            filegroup_prefix = filegroup.pkg_prefix,
            filegroup_diff = filegroup_diff,
        ))
        for src in filegroup.srcs.to_list():
            filegroup_pkg_files = src.pkg_files
            pkg_files.extend(filegroup_pkg_files)
            pkg_dirs.extend(src.pkg_dirs)
            pkg_symlinks.extend(src.pkg_symlinks)
            for filegroup_pkg_files, _ in filegroup_pkg_files:
                for path in filegroup_pkg_files.dest_src_map.keys():
                    content.append(_TARGET.format(
                        filegroup_install = filegroup_install,
                        install_name = "install/{}".format(path),
                        install_args = " ".join([shell.quote(arg) for arg in filegroup.install_args]),
                        filegroup_diff = filegroup_diff,
                        diff_name = "diff/{}".format(path),
                        diff_args = " ".join([shell.quote(arg) for arg in filegroup.diff_args]),
                        src = path,
                        dest = "{}/{}".format(filegroup.install_dir, path.removeprefix("{}/".format(filegroup.pkg_prefix))),
                    ))

    content.append("")
    ctx.actions.write(
        output = makefile,
        content = "\n".join(content),
    )
    return [
        DefaultInfo(
            files = depset([makefile] + ctx.files.srcs),
        ),
        PackageFilegroupInfo(
            pkg_files = pkg_files,
            pkg_dirs = pkg_dirs,
            pkg_symlinks = pkg_symlinks,
        ),
    ]

al_make_install = rule(
    doc = "Create the make install executable and a filegroup",
    implementation = _impl,
    provides = [PackageFilegroupInfo],
    attrs = {
        "srcs": attr.label_list(
            providers = [AlMakeInstallFilegroupInfo],
            doc = "Make install filegroups",
        ),
    },
)
