---
apiVersion: v1
kind: Namespace
metadata:
  name: src-infra-harbor-cl
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: src-infra-harbor-cl-kubeconfig
  labels:
    reconcile.fluxcd.io/watch: Enabled
data:
  provider: generic
  address: https://harbor.alwaldend.com:6443
  audiences: |
    WQ8TMsm9Q5ai87x1l902M8-gFxfIJ3O51nB3f-Du4Uk
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIBdjCCAR2gAwIBAgIBADAKBggqhkjOPQQDAjAjMSEwHwYDVQQDDBhrM3Mtc2Vy
    dmVyLWNhQDE3ODM3MDYxMTkwHhcNMjYwNzEwMTY1NTE5WhcNMzYwNzA3MTY1NTE5
    WjAjMSEwHwYDVQQDDBhrM3Mtc2VydmVyLWNhQDE3ODM3MDYxMTkwWTATBgcqhkjO
    PQIBBggqhkjOPQMBBwNCAARByCoeS3gbKsbU21GkE9lmkDLp9TZmpaTtcRbvXkEs
    4PsUNpLVcKDJYl39zvSslIcJ3rjAE/vdaeGNsODysckMo0IwQDAOBgNVHQ8BAf8E
    BAMCAqQwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUeVi7u1XOdMSWAl4tlu43
    kljIHqQwCgYIKoZIzj0EAwIDRwAwRAIgc0wEhmVdUyU51IaN4T4IMLCll2gmQxym
    iM1INJpEdRICIAIn/qg7h5n3MAKGsFFmmIrwRudYY+NdKweFKXnuy7h4
    -----END CERTIFICATE-----
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: src-infra-harbor-cl
spec:
  path: ./infra/harbor/cl/flux
  sourceRef:
    kind: GitRepository
    name: flux-git-src
  decryption:
    provider: sops
    secretRef:
      name: flux-sops-secret
  interval: 60m0s
  wait: true
  timeout: 3m0s
  retryInterval: 2m0s
  prune: true
  force: false
  patches:
  - target:
      kind: "(HelmRelease|Kustomization)"
    patch: |
      - op: add
        path: /spec/kubeConfig
        value:
          configMapRef:
            name: src-infra-harbor-cl-kubeconfig
---
