"""
This is an example toolchain that will be generated by the rules
"""

load("@rules_binary_toolchain//main/bzl:binary_toolchain_binary.bzl", "binary_toolchain_binary")
load("@rules_binary_toolchain//main/bzl:binary_toolchain_resolved_toolchain.bzl", "binary_toolchain_resolved_toolchain")
load("@rules_binary_toolchain//main/bzl:binary_toolchain_run_binary.bzl", "binary_toolchain_run_binary")
load("@rules_binary_toolchain//main/bzl:binary_toolchain_test.bzl", "binary_toolchain_test")
load("@rules_binary_toolchain//main/bzl:binary_toolchain_toolchain.bzl", "binary_toolchain_toolchain")

example_toolchain_type = str(Label("//:example_toolchain_type"))
example_toolchain = binary_toolchain_toolchain
example_binary = binary_toolchain_binary(example_toolchain_type)
example_run_binary = binary_toolchain_run_binary(example_toolchain_type)
example_test = binary_toolchain_test(example_toolchain_type)
example_resolved_toolchain = binary_toolchain_resolved_toolchain(example_toolchain_type)
