[[Submissions]]
  Id = 1087427052
  StatusDisplay = "Accepted"
  Lang = "python3"
  QuestionId = 199
  TitleSlug = "binary-tree-right-side-view"
  Code = "# Definition for a binary tree node.\n# class TreeNode:\n#     def __init__(self, val=0, left=None, right=None):\n#         self.val = val\n#         self.left = left\n#         self.right = right\nclass Solution:\n    def rightSideView(self, root: Optional[TreeNode]) -> List[int]:\n        if not root:\n            return []\n        cur, nxt = [root], []\n        answer = []\n        \n        while cur:\n            last_node = cur.pop()\n            if last_node.right:\n                nxt.append(last_node.right)\n            if last_node.left:\n                nxt.append(last_node.left)\n            answer.append(last_node.val)\n            \n            while cur:\n                node = cur.pop()\n                if node.right:\n                    nxt.append(node.right)\n                if node.left:\n                    nxt.append(node.left)\n            \n            cur.clear()\n            nxt.reverse()\n            cur, nxt = nxt, cur\n\n        return answer"
  Title = "Binary Tree Right Side View"
  Url = "/submissions/detail/1087427052/"
  LangName = "Python3"
  Timestamp = 1698657035
  Status = 10
  Runtime = "48 ms"
  IsPending = "Not Pending"
  Memory = "16.3 MB"
  CompareResult = "111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
