load("@rules_docs//docs:defs.bzl", "docs_filegroup")
load("@rules_kotlin//kotlin:android.bzl", "kt_android_local_test")
load("@rules_shell//shell:sh_binary.bzl", "sh_binary")

[
    kt_android_local_test(
        name = "{}_test".format(file.replace(".kt", "")),
        size = "small",
        srcs = [file],
        manifest = "//projects/android_launcher:manifest",
        test_class = "com.alwaldend.src.projects.android_launcher.{}".format(file.replace(".kt", "")),
        deps = [
            "//projects/android_launcher/main/java:launcher_library",
            "@com_alwaldend_src_projects_android_launcher_maven//:junit_junit",
            "@com_alwaldend_src_projects_android_launcher_maven//:org_robolectric_robolectric",
            "@rules_robolectric//bazel:android-all",
        ],
    )
    for file in glob(["**/*.kt"])
]

sh_binary(
    name = "launcher_smoke_test",
    srcs = ["launcher_smoke_test.sh"],
    data = ["//projects/android_launcher/main/java:launcher_binary"],
    env = {
        "ACTIVITY_NAME": "com.alwaldend.src.projects.android_launcher.MainActivity",
        "PACKAGE_NAME": "com.alwaldend.src.projects.android_launcher",
    },
    tags = [
        "external",
        "manual",
        "no-cache",
        "no-sandbox",
    ],
    visibility = ["//projects/android_launcher:__subpackages__"],
)

docs_filegroup(
    name = "docs",
    srcs = glob(["*.md"]),
    visibility = ["//projects/android_launcher:__subpackages__"],
)
