[[Submissions]]
  Id = 1291224277
  StatusDisplay = "Accepted"
  Lang = "python3"
  QuestionId = 633
  TitleSlug = "sum-of-square-numbers"
  Code = "from math import sqrt\n\nclass Solution:\n    def judgeSquareSum(self, c: int) -> bool:\n        for a in range(int(sqrt(c)) + 1):  # Iterate through all possible values of `a`\n            b = sqrt(c - a * a)  # Compute `b` as the square root of `c - a^2`\n            if b == int(b):  # Check if `b` is an integer\n                return True  # If `b` is an integer, return true\n        return False  # If no such pair `(a, b)` is found, return false"
  Title = "Sum of Square Numbers"
  Url = "/submissions/detail/1291224277/"
  LangName = "Python3"
  Timestamp = 1718627997
  Status = 10
  Runtime = "124 ms"
  IsPending = "Not Pending"
  Memory = "16.6 MB"
  CompareResult = "1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
