note_id = 1526927509139
guid = "d_q1wkwp+-"
note_type_id = 1520550989354
note_type = "basic"
tags = ["WorkingWithMultipleFiles"]

[[cards]]
id = 1526927520172
ordinal = 0

[[cards]]
id = 1668965796712
ordinal = 1

[fields]
Back = '^w s'
Front = 'Split window horizontally'
