note_id = 1526925933320
guid = "h%cxK11eTl"
note_type_id = 1520550989354
note_type = "basic"
tags = ["Cursor", "Movement"]

[[cards]]
id = 1526925945469
ordinal = 0

[[cards]]
id = 1668965796613
ordinal = 1

[fields]
Back = 'Fx'
Front = 'Jump to previous occurence of character x on the current line'
