note_id = 1526926471546
guid = "CWr}D[7H4O"
note_type_id = 1520550989354
note_type = "basic"
tags = ["Editing"]

[[cards]]
id = 1526926495256
ordinal = 0

[[cards]]
id = 1668965796644
ordinal = 1

[fields]
Back = 'xp'
Front = 'Transpose two letters'
