note_id = 1668637099374
guid = "v`CC4~`II4"
note_type_id = 1520550989354
note_type = "basic"
tags = []

[[cards]]
id = 1668637099374
ordinal = 0

[[cards]]
id = 1668965796733
ordinal = 1

[fields]
Back = ':tabo[nly]'
Front = 'Close all other tabs'
