note_id = 1692978550423
guid = "M<yj<Av>(u"
note_type_id = 1520550989354
note_type = "basic"
tags = []

[[cards]]
id = 1692978550423
ordinal = 0

[[cards]]
id = 1692978550424
ordinal = 1

[fields]
Back = ':cq[uit]'
Front = 'Exit vim with an error code'
