note_id = 1520716969041
guid = "dE.,azsQUu"
note_type_id = 1496733135171
note_type = "chinese"
tags = ["B1", "Grammatical_Structures", "SentencePatterns"]

[[cards]]
id = 1520716974905
ordinal = 0

[fields]
article-title = 'Indicating purpose or intent using "shi...de"'
english = 'We are all going on business trips.'
example-sentence = ''
example-type = ''
grammar-construct = 'Person + 是 + 来 / 去 + Verb+ 的'
hanzi = '我们都是去出差的。'
notes = ''
pinyin = 'Wǒmen dōu shì qù chūchāi de.'
source = 'https://resources.allsetlearning.com/chinese/grammar/ASG0UFR4'
