note_id = 1520716969040
guid = "n*(m9aY$tm"
note_type_id = 1496733135171
note_type = "chinese"
tags = ["B1", "Grammatical_Structures", "SentencePatterns"]

[[cards]]
id = 1520716974904
ordinal = 0

[fields]
article-title = 'Indicating purpose or intent using "shi...de"'
english = 'I came for traveling.'
example-sentence = ''
example-type = ''
grammar-construct = 'Person + 是 + 来 / 去 + Verb+ 的'
hanzi = '我是来旅游的。'
notes = ''
pinyin = 'Wǒ shì lái lǚyóu de.'
source = 'https://resources.allsetlearning.com/chinese/grammar/ASG0UFR4'
