[[Submissions]]
  Id = 1719621054
  StatusDisplay = "Accepted"
  Lang = "python3"
  QuestionId = 981
  TitleSlug = "delete-columns-to-make-sorted"
  Code = "class Solution:\n    def minDeletionSize(self, strs: List[str]) -> int:\n        res = 0\n        for col in range(len(strs[0])):\n            prev = 0\n            for row in range(len(strs)):\n                char = ord(strs[row][col])\n                if char >= prev:\n                    prev = char\n                else:\n                    res += 1\n                    break\n        return res"
  Title = "Delete Columns to Make Sorted"
  Url = "/submissions/detail/1719621054/"
  LangName = "Python3"
  Timestamp = 1754059586
  Status = 10
  Runtime = "48 ms"
  IsPending = "Not Pending"
  Memory = "18.5 MB"
  CompareResult = "11111111111111111111111111111111111111111111111111111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
