[[Submissions]]
  Id = 1713565200
  StatusDisplay = "Accepted"
  Lang = "python3"
  QuestionId = 2316
  TitleSlug = "count-hills-and-valleys-in-an-array"
  Code = "class Solution:\n    def countHillValley(self, nums: List[int]) -> int:\n        res = 0\n        length = len(nums)\n        for i in range(1, length - 1):\n            if nums[i] == nums[i - 1]:\n                continue\n            left = 0\n            for j in range(i - 1, -1, -1):\n                if nums[j] > nums[i]:\n                    left = 1\n                    break\n                elif nums[j] < nums[i]:\n                    left = -1\n                    break\n            right = 0\n            for j in range(i + 1, length):\n                if nums[j] > nums[i]:\n                    right = 1\n                    break\n                elif nums[j] < nums[i]:\n                    right = -1\n                    break\n            if left == right and left != 0:\n                res += 1\n        return res"
  Title = "Count Hills and Valleys in an Array"
  Url = "/submissions/detail/1713565200/"
  LangName = "Python3"
  Timestamp = 1753632218
  Status = 10
  Runtime = "0 ms"
  IsPending = "Not Pending"
  Memory = "17.8 MB"
  CompareResult = "1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
