[[Submissions]]
  Id = 1091200483
  StatusDisplay = "Accepted"
  Lang = "golang"
  QuestionId = 124
  TitleSlug = "binary-tree-maximum-path-sum"
  Code = "/**\n * Definition for a binary tree node.\n * type TreeNode struct {\n *     Val int\n *     Left *TreeNode\n *     Right *TreeNode\n * }\n */\nfunc maxPathSum(root *TreeNode) int {\n    ans := -1 << 63\n    maxPath(root, &ans)\n    return ans\n}\n\nfunc maxPath(root *TreeNode, ans *int) int {\n    if root == nil {\n        return 0\n    }\n    leftPathSum := maxPath(root.Left, ans)\n    rightPathSum := maxPath(root.Right, ans)\n    *ans = max(*ans, leftPathSum + rightPathSum + root.Val)\n    return max(max(leftPathSum+root.Val, rightPathSum+root.Val), 0)\n}\n\nfunc max(a int, b int) int {\n    if (a >= b) {\n        return a\n    }\n    return b\n}\n"
  Title = "Binary Tree Maximum Path Sum"
  Url = "/submissions/detail/1091200483/"
  LangName = "Go"
  Timestamp = 1699093668
  Status = 10
  Runtime = "11 ms"
  IsPending = "Not Pending"
  Memory = "8.3 MB"
  CompareResult = "11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
