load("@bazel_skylib//:bzl_library.bzl", "bzl_library")
load("@rules_docs//docs:defs.bzl", "docs_filegroup")

toolchain_type(
    name = "toolchain_type",
    visibility = ["//visibility:public"],
)

docs_filegroup(
    name = "docs",
    srcs = glob(
        ["*.md"],
        allow_empty = True,
    ),
    prefix = "content/docs/projects/rules_hugo/main/bzl",
    visibility = ["//:__pkg__"],
)

bzl_library(
    name = "al_hugo_archives",
    srcs = ["al_hugo_archives.bzl"],
    visibility = ["//visibility:public"],
)

bzl_library(
    name = "al_hugo_extension",
    srcs = ["al_hugo_extension.bzl"],
    visibility = ["//visibility:public"],
    deps = [
        ":al_hugo_archives",
        "@bazel_tools//tools/build_defs/repo:cache.bzl",
        "@bazel_tools//tools/build_defs/repo:http.bzl",
        "@bazel_tools//tools/build_defs/repo:utils.bzl",
    ],
)

bzl_library(
    name = "al_hugo_site_info",
    srcs = ["al_hugo_site_info.bzl"],
    visibility = ["//visibility:public"],
)

bzl_library(
    name = "al_hugo_site",
    srcs = ["al_hugo_site.bzl"],
    visibility = ["//visibility:public"],
    deps = [":al_hugo_site_info"],
)

bzl_library(
    name = "al_hugo_binary",
    srcs = ["al_hugo_binary.bzl"],
    visibility = ["//visibility:public"],
    deps = [
        ":al_hugo_site_info",
        "@bazel_skylib//lib:shell",
        "@rules_pkg//pkg:bzl_srcs",
    ],
)

bzl_library(
    name = "al_hugo_run_binary",
    srcs = ["al_hugo_run_binary.bzl"],
    visibility = ["//visibility:public"],
    deps = [
        ":al_hugo_site_info",
        "@bazel_skylib//lib:shell",
    ],
)

bzl_library(
    name = "al_hugo_worker",
    srcs = ["al_hugo_worker.bzl"],
    visibility = ["//visibility:public"],
    deps = [
        ":al_hugo_site_info",
        "@bazel_skylib//lib:shell",
    ],
)

bzl_library(
    name = "al_hugo_theme",
    srcs = ["al_hugo_theme.bzl"],
    visibility = ["//visibility:public"],
    deps = [
        ":al_hugo_module_info",
        ":al_hugo_theme_info",
    ],
)

bzl_library(
    name = "al_hugo_module",
    srcs = ["al_hugo_module.bzl"],
    visibility = ["//visibility:public"],
    deps = [":al_hugo_module_info"],
)

bzl_library(
    name = "al_hugo_module_info",
    srcs = ["al_hugo_module_info.bzl"],
    visibility = ["//visibility:public"],
)

bzl_library(
    name = "al_hugo_theme_info",
    srcs = ["al_hugo_theme_info.bzl"],
    visibility = ["//visibility:public"],
)

bzl_library(
    name = "al_hugo_toolchain",
    srcs = ["al_hugo_toolchain.bzl"],
    visibility = ["//visibility:public"],
)
