load("@rules_docs//docs:defs.bzl", "docs_filegroup")
load("@rules_terraform//terraform:defs.bzl", "terraform_binary_map", "terraform_target_binary_map", "terraform_test_map")
load("//projects/al/rules/al:al_binary.bzl", "al_binary_run")

docs_filegroup(
    name = "docs",
    srcs = glob(["*.md"]),
    visibility = ["//infra/ingress:__pkg__"],
    deps = subpackages(
        include = ["*"],
        allow_empty = True,
    ),
)

_PROVIDERS = [
    "@terraform_provider_cloudflare_cloudflare//:provider",
    "@terraform_provider_terraform_routeros_routeros//:provider",
    "@terraform_provider_yandex_cloud_yandex//:provider",
]

_CONFIGS = ["//infra/ingress:al"]

_DATA = glob(["*.tf"]) + [
    "//projects/tf_modules/dns_records:dns_records",
    "//infra/ingress:dnsconfig",
    "//infra/ingress/ansible:inventory",
    "//tools/vault/tf_backend",
    "//tools/vault/injector",
    "//infra/cloud_init:cloud_init",
]

terraform_binary_map(
    name = "tf",
    data = _DATA,
    providers = _PROVIDERS,
    wrapper = al_binary_run,
    wrapper_kwargs = {
        "configs": _CONFIGS,
        "run_args": [
            "--plugin_label",
            "tf",
        ],
    },
)

terraform_target_binary_map(
    name = "dns",
    data = _DATA,
    providers = _PROVIDERS,
    target = "module.dns",
    wrapper = al_binary_run,
    wrapper_kwargs = {
        "configs": _CONFIGS,
        "run_args": [
            "--plugin_label",
            "dns=1",
        ],
    },
)

terraform_test_map(
    name = "tf_tests",
    data = _DATA,
    providers = _PROVIDERS,
)
