note_id = 1520716968710
guid = "qd#uIwAiq["
note_type_id = 1496733135171
note_type = "chinese"
tags = ["B1", "Grammatical_Structures", "SentencePatterns"]

[[cards]]
id = 1520716974574
ordinal = 0

[fields]
article-title = 'Expressing "double negation"'
english = "There is no way he's not coming."
example-sentence = ''
example-type = ''
grammar-construct = 'Subj. + 不 + 会 / 能 / 可能 + 不 / 没 + Predicate'
hanzi = '他不会不来的。'
notes = ''
pinyin = 'Tā bù huì bù lái  de.'
source = 'https://resources.allsetlearning.com/chinese/grammar/ASGEEA2D'
