[[Submissions]]
  Id = 1107276458
  StatusDisplay = "Accepted"
  Lang = "cpp"
  QuestionId = 972
  TitleSlug = "knight-dialer"
  Code = "class Solution {\npublic:\n    vector<vector<int>> memo;\n    int n;\n    int MOD = 1e9 + 7;\n    vector<vector<int>> jumps = {\n        {4, 6},\n        {6, 8},\n        {7, 9},\n        {4, 8},\n        {3, 9, 0},\n        {},\n        {1, 7, 0},\n        {2, 6},\n        {1, 3},\n        {2, 4}\n    };\n    \n    int dp(int remain, int square) {\n        if (remain == 0) {\n            return 1;\n        }\n        \n        if (memo[remain][square] != 0) {\n            return memo[remain][square];\n        }\n        \n        int ans = 0;\n        for (int nextSquare : jumps[square]) {\n            ans = (ans + dp(remain - 1, nextSquare)) % MOD;\n        }\n        \n        memo[remain][square] = ans;\n        return ans;\n    }\n    \n    int knightDialer(int n) {\n        this->n = n;\n        memo = vector(n + 1, vector(10, 0));\n        int ans = 0;\n        for (int square = 0; square < 10; square++) {\n            ans = (ans + dp(n - 1, square)) % MOD;\n        }\n        \n        return ans;\n    }\n};"
  Title = "Knight Dialer"
  Url = "/submissions/detail/1107276458/"
  LangName = "C++"
  Timestamp = 1701070333
  Status = 10
  Runtime = "160 ms"
  IsPending = "Not Pending"
  Memory = "39.4 MB"
  CompareResult = "1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
