load("//tools/docs:defs.bzl", "docs_filegroup")

alias(
    name = "install_file",
    actual = "//tools/install_file/main/py:install_file",
    visibility = ["//:__subpackages__"],
)

docs_filegroup(
    name = "docs",
    srcs = glob(["*.md"]),
    visibility = ["//tools:__pkg__"],
    deps = [
        "//tools/install_file/main/bzl:docs",
    ],
)
