[[Submissions]]
  Id = 1157205765
  StatusDisplay = "Accepted"
  Lang = "python3"
  QuestionId = 576
  TitleSlug = "out-of-boundary-paths"
  Code = "class Solution:\n\n    def findPaths(self, m: int, n: int, N: int, x: int, y: int) -> int:\n\n        M = 1000000000 + 7\n\n        dp = [[0] * n for _ in range(m)]\n\n        dp[x][y] = 1\n\n        count = 0\n\n\n\n        for moves in range(1, N + 1):\n\n            temp = [[0] * n for _ in range(m)]\n\n\n\n            for i in range(m):\n\n                for j in range(n):\n\n                    if i == m - 1:\n\n                        count = (count + dp[i][j]) % M\n\n                    if j == n - 1:\n\n                        count = (count + dp[i][j]) % M\n\n                    if i == 0:\n\n                        count = (count + dp[i][j]) % M\n\n                    if j == 0:\n\n                        count = (count + dp[i][j]) % M\n\n                    temp[i][j] = (\n\n                        ((dp[i - 1][j] if i > 0 else 0) + (dp[i + 1][j] if i < m - 1 else 0)) % M +\n\n                        ((dp[i][j - 1] if j > 0 else 0) + (dp[i][j + 1] if j < n - 1 else 0)) % M\n\n                    ) % M\n\n\n\n            dp = temp\n\n\n\n        return count\n\n\n\n\n\n"
  Title = "Out of Boundary Paths"
  Url = "/submissions/detail/1157205765/"
  LangName = "Python3"
  Timestamp = 1706256135
  Status = 10
  Runtime = "107 ms"
  IsPending = "Not Pending"
  Memory = "16.7 MB"
  CompareResult = "1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111"
  HasNotes = false
  FlagType = 1
