load("@rules_docs//docs:defs.bzl", "docs_filegroup")

docs_filegroup(
    name = "docs",
    srcs = glob(["*.md"]),
    visibility = [
        "//projects:__pkg__",
        "//projects/cgit/landing:__pkg__",
    ],
    deps = ["//{}/{}:docs".format(
        package_name(),
        package,
    ) for package in subpackages(include = ["*"])],
)

filegroup(
    name = "dnsconfig",
    srcs = ["dnsconfig.json"],
    visibility = [
        "//infra:__pkg__",
        "//infra/dns:__pkg__",
        "//projects/alwaldend.com:__subpackages__",
    ],
)
