load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "v1alpha1",
    srcs = [
        "digest.go",
        "graph.go",
        "normalization.go",
        "types.go",
        "validation.go",
    ],
    importpath = "git.alwaldend.com/alwaldend/src/projects/goal/api/v1alpha1",
    visibility = ["//projects/goal:__subpackages__"],
)

go_test(
    name = "go_test",
    size = "small",
    srcs = [
        "graph_test.go",
        "validation_test.go",
    ],
    embed = [":v1alpha1"],
)
