load("@rules_docs//docs:defs.bzl", "docs_filegroup")
load("@rules_go//go:def.bzl", "TOOLS_NOGO", "nogo")

docs_filegroup(
    name = "docs",
    srcs = glob(["*.md"]),
    visibility = ["//tools:__pkg__"],
)

nogo(
    name = "nogo",
    visibility = ["//visibility:public"],  # must have public visibility
    deps = TOOLS_NOGO,
)
