note_id = 1520716970990
guid = "t/aB/S}kb+"
note_type_id = 1496733135171
note_type = "chinese"
tags = ["C1", "Comparisons"]

[[cards]]
id = 1520716976854
ordinal = 0

[fields]
article-title = 'Comparing "genju" and "ju"'
english = 'It is rumoured that the Prime Minister is about to resign.'
example-sentence = ''
example-type = 'valid'
grammar-construct = ''
hanzi = '据传首相将要辞职。'
notes = ''
pinyin = 'Jù zhuàn shǒuxiàng jiāngyào cízhí.'
source = 'https://resources.allsetlearning.com/chinese/grammar/ASGXJYJD'
