// Command gradle_lock_gen converts a rules_jvm_external maven_install.json
// lock file into one Gradle build input file per invocation, so both build
// systems can share the same pinned dependency set.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"sort"
	"strings"
)

type lockArtifact struct {
	Version string            `json:"version"`
	Shasums map[string]string `json:"shasums"`
}

type lockFile struct {
	Artifacts map[string]lockArtifact `json:"artifacts"`
}

// gradleDep is one library that Gradle should depend on.
type gradleDep struct {
	group   string
	name    string
	version string
	sha256  string
	isAAR   bool
}

func main() {
	format := flag.String("format", "", "output format: toml or verification-xml")
	out := flag.String("out", "", "output file path")
	flag.Parse()

	if *format == "" || *out == "" || flag.NArg() != 1 {
		fatal("usage: gradle_lock_gen --format=<toml|verification-xml> --out=<path> <maven_lock.json>")
	}

	lockPath := flag.Arg(0)
	lockData, err := os.ReadFile(lockPath)
	if err != nil {
		fatal("read lock file: %v", err)
	}
	var lock lockFile
	if err := json.Unmarshal(lockData, &lock); err != nil {
		fatal("parse lock file: %v", err)
	}

	deps := extractDeps(&lock)
	if len(deps) == 0 {
		fatal("no buildable artifacts found in lock file")
	}

	var content string
	switch *format {
	case "toml":
		content = renderVersionsToml(deps)
	case "verification-xml":
		content = renderVerificationXML(deps)
	default:
		fatal("unknown format %q (want toml or verification-xml)", *format)
	}

	if err := os.WriteFile(*out, []byte(content), 0o644); err != nil {
		fatal("write output: %v", err)
	}
}

// extractDeps converts the lock file's artifact map into a flat set of
// Gradle dependencies, one per group:name. It prefers the AAR variant when
// both a plain-jar and an AAR key exist for the same coordinate, because
// that is what an Android Gradle build needs.
func extractDeps(lock *lockFile) map[string]gradleDep {
	deps := map[string]gradleDep{}

	for key, art := range lock.Artifacts {
		parts := strings.SplitN(key, ":", 4)
		if len(parts) < 2 {
			continue
		}
		group, name := parts[0], parts[1]
		ga := group + ":" + name

		if len(parts) >= 4 && parts[2] == "jar" && (parts[3] == "sources" || parts[3] == "javadoc") {
			continue
		}

		sha := art.Shasums["jar"]
		isAAR := len(parts) >= 3 && parts[2] == "aar"

		existing, ok := deps[ga]
		if !ok {
			deps[ga] = gradleDep{group: group, name: name, version: art.Version, sha256: sha, isAAR: isAAR}
		} else if isAAR && !existing.isAAR && sha != "" {
			existing.version = art.Version
			existing.sha256 = sha
			existing.isAAR = true
			deps[ga] = existing
		} else if sha != "" && existing.sha256 == "" {
			existing.version = art.Version
			existing.sha256 = sha
			existing.isAAR = isAAR
			deps[ga] = existing
		}
	}

	return deps
}

func gradleAlias(group, name string) string {
	return strings.NewReplacer(".", "-", ":", "-").Replace(group + ":" + name)
}

func renderVersionsToml(deps map[string]gradleDep) string {
	keys := make([]string, 0, len(deps))
	for k := range deps {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var buf strings.Builder
	buf.WriteString("# Generated by //projects/android_launcher/cmd/gradle_lock_gen. Do not edit.\n")
	buf.WriteString("# Source: projects/android_launcher/maven_lock.json (rules_jvm_external)\n\n")
	buf.WriteString("[libraries]\n")
	for _, ga := range keys {
		d := deps[ga]
		alias := gradleAlias(d.group, d.name)
		fmt.Fprintf(&buf, "%s = { module = %q, version = %q }\n", alias, ga, d.version)
	}
	return buf.String()
}

func renderVerificationXML(deps map[string]gradleDep) string {
	keys := make([]string, 0, len(deps))
	for k := range deps {
		if deps[k].sha256 != "" {
			keys = append(keys, k)
		}
	}
	sort.Strings(keys)

	var buf strings.Builder
	buf.WriteString("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n")
	buf.WriteString("<verification-metadata version=\"1.3\" xmlns=\"https://schema.gradle.org/dependency-verification\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"https://schema.gradle.org/dependency-verification https://schema.gradle.org/dependency-verification/dependency-verification-1.3.xsd\">\n")
	buf.WriteString("  <configuration>\n")
	buf.WriteString("    <verify-metadata>false</verify-metadata>\n")
	buf.WriteString("    <verify-signatures>false</verify-signatures>\n")
	buf.WriteString("  </configuration>\n")
	buf.WriteString("  <components>\n")
	for _, ga := range keys {
		d := deps[ga]
		ext := "jar"
		if d.isAAR {
			ext = "aar"
		}
		filename := d.name + "-" + d.version + "." + ext
		fmt.Fprintf(&buf, "    <component group=%q name=%q version=%q>\n", d.group, d.name, d.version)
		fmt.Fprintf(&buf, "      <artifact name=%q>\n", filename)
		fmt.Fprintf(&buf, "        <sha256 value=%q/>\n", d.sha256)
		fmt.Fprintf(&buf, "      </artifact>\n")
		fmt.Fprintf(&buf, "    </component>\n")
	}
	buf.WriteString("  </components>\n")
	buf.WriteString("</verification-metadata>\n")
	return buf.String()
}

func fatal(format string, args ...interface{}) {
	fmt.Fprintf(os.Stderr, "gradle_lock_gen: "+format+"\n", args...)
	os.Exit(1)
}
