note_id = 1520716970826
guid = "FOa=>/SpM^"
note_type_id = 1496733135171
note_type = "chinese"
tags = ["B2", "Comparisons", "SeparateFunctions"]

[[cards]]
id = 1520716976690
ordinal = 0

[fields]
article-title = 'Comparing "shihe" and "heshi"'
english = 'Although iPads are fun to use, I think the price is not suitable.'
example-sentence = ''
example-type = ''
grammar-construct = 'Subj. + Adv. + 合适'
hanzi = 'iPad虽然好用，但是对我来说价格不太合适！'
notes = ''
pinyin = ''
source = 'https://resources.allsetlearning.com/chinese/grammar/ASGVDOXL'
