note_id = 1520716967941
guid = "QUv+<&RsT^"
note_type_id = 1496733135171
note_type = "chinese"
tags = ["B1", "Parts_of_Speech", "Verbs"]

[[cards]]
id = 1520716973805
ordinal = 0

[fields]
article-title = 'Appearance with "kanqilai"'
english = 'This restaurant looks good.'
example-sentence = ''
example-type = ''
grammar-construct = 'Subj. + 看起来 + Adj.'
hanzi = '这家餐厅看起来不错。'
notes = ''
pinyin = 'Zhè jiā cāntīng kàn qǐlái bùcuò.'
source = 'https://resources.allsetlearning.com/chinese/grammar/ASG9K0F8'
