load("@rules_pkg//pkg:mappings.bzl", "pkg_files")
load("//tools/docs:defs.bzl", "docs_filegroup")

docs_filegroup(
    name = "docs",
    srcs = glob(["*.md"]),
    visibility = ["//data/ssl:__pkg__"],
    deps = [":docs_certificates"] + subpackages(
        include = ["*"],
        allow_empty = True,
    ),
)

pkg_files(
    name = "docs_certificates",
    srcs = [":alwaldend.com"],
    prefix = "content/docs/{}".format(package_name()),
)

filegroup(
    name = "alwaldend.com",
    srcs = [
        ":ica1",
        ":ica_clients",
        ":ica_servers",
        ":root_ca",
        ":simeonwarren",
    ],
    visibility = ["//:__subpackages__"],
)

filegroup(
    name = "ica_clients",
    srcs = ["//infra/vault/tf/output:pki_ca_clients"],
    visibility = ["//:__subpackages__"],
)

filegroup(
    name = "ica_servers",
    srcs = ["//infra/vault/tf/output:pki_ca_servers"],
    visibility = ["//:__subpackages__"],
)

filegroup(
    name = "simeonwarren",
    srcs = ["simeonwarren.crt"],
    visibility = ["//:__subpackages__"],
)

filegroup(
    name = "ica1",
    srcs = ["ica1.crt"],
    visibility = ["//:__subpackages__"],
)

filegroup(
    name = "root_ca",
    srcs = ["root_ca.crt"],
    visibility = ["//:__subpackages__"],
)
