note_id = 1520716968230
guid = "sN7`R-,vD?"
note_type_id = 1496733135171
note_type = "chinese"
tags = ["B1", "Parts_of_Speech", "Verbs"]

[[cards]]
id = 1520716974094
ordinal = 0

[fields]
article-title = 'Verbs followed by "gei"'
english = 'The landlord rented a very cheap house to me.'
example-sentence = ''
example-type = ''
grammar-construct = 'Subj. + Verb + 给 + [Recipient] + Obj.'
hanzi = '房东租给了我一个很便宜的房子。'
notes = ''
pinyin = 'Fángdōng zū gěi le wǒ yīgè hěn piányi de fángzi.'
source = 'https://resources.allsetlearning.com/chinese/grammar/ASGMMHTQ'
