[versions]
agp = "8.9.1"
kotlin = "2.1.21"
protobuf = "0.9.4"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
google-protobuf = { id = "com.google.protobuf", version.ref = "protobuf" }
